### ISSUE TITLE
[Help] Possible to hide a message whether it does not match my script filter ?

### ISSUE THREAD

**Issue by Moret84** [emqx/MQTTX#1005]
#### Describe the problem you Confuse

Hello, thanks for your work on MQTTX. I would like to know if it is possible to hide a message if it does not match against my filter defined in a custom script. If so, how can i achieve that ? 

Thanks for your help.

**Comment by ysfscream** [comment]
Hello, can you describe more about the specific application scenario? For example, what is your current data like and what is the desired result?

**Comment by ysfscream** [comment]
Oh, good! Thanks for the detailed description!

But sorry currently the script feature is relatively simple to use in MQTT X. You can only set the message template, there is no way to ignore the message, so perhaps here you can only return an empty string or a prompt "No matched"

```js
function filterBanana(value) {
  if (value.msgType == "banana") {
	 return JSON.stringify(value);
  }
  // return ''
  // Don't know what to write here to make the message ignored
  return 'No matched!'
}

execute(filterBanana)
```

**Comment by Moret84** [comment]
Year, that's what I used to do, but I was wondering if there was a better way.
Anyway thanks for your response, I will close the issue.

**Comment by ysfscream** [comment]
Thank you for your feedback, we will continue to optimize this feature!
