### ISSUE TITLE
[Feature] Want to add topic import and export function.

### ISSUE THREAD

**Issue by bambuo** [emqx/MQTTX#1017]
In some scenarios, topics are often added manually one by one, which is too inefficient. Therefore, we hope to support the ability of import and export, which is much more convenient

**Comment by ysfscream** [comment]
Hi! There is no dedicated topic import and export function, but the data currently supported for export include topics.

For scenarios where you need to add topics one at a time, perhaps you could use the multi-topic subscription feature.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/21299158/181914866-06b430a2-9a9b-4db8-a8ed-cb40bef84cc8.png">

**Comment by ysfscream** [comment]
Hi, thanks for your feedback. I will close the issue first, if it still exists, please don't hesitate to reopen it.
