### ISSUE TITLE
[BUG] $ symbol in publish topic name 

### ISSUE THREAD

**Issue by DimaSes99** [emqx/MQTTX#1021]
In the latest 1.8.1 release it is said:

> **MQTT X:** Topic is validated before publishing (Cannot contain #, +, $, etc.)

But, for example, AWS IOT core uses the **$** symbol in topic names for a Device shadow and some other functionality.
Is it possible to disable this validation? Or should I switch to a previous version?

**Comment by ysfscream** [comment]
Thanks for your feedback, it was a design mistake and we have fixed it in this PR: https://github.com/emqx/MQTTX/pull/1022, maybe you can wait for v1.8.2 or fall back to 1.8.0 ban b

**Comment by ysfscream** [comment]
Fixed in https://github.com/emqx/MQTTX/releases/tag/v1.8.2

Thanks for your feedback!
