### ISSUE TITLE
[Bug] Can't subscribe topic after connect success

### ISSUE THREAD

**Issue by bachbonglong** [emqx/MQTTX#1024]
#### What did I do

I have successfully connected mqtt in MQTTX, and I created a new subscribe topic but got an error

#### What happened

Get an error. Topic: subscribe error, Unexpected QoS, SubACK failed, Please check MQTT broker configuration 

#### Expected

Expect : subscribe topic success. 

#### Environment

- OS: macOS Big Sur 11.6
- MQTTX version: Version: v1.8.1

#### More detail

More detail include `log` information or screenshot
![Screen Shot 2022-08-03 at 15 11 15](https://user-images.githubusercontent.com/42697834/182558154-0ad3eb05-92f7-4b84-adf8-e54ef85ff4c7.png)

**Comment by ysfscream** [comment]
Hi, this should not be a bug, the tips in this have been very clear, is the problem of authentication failure of permissions.

**Comment by ysfscream** [comment]
Here we have optimized the error message in https://github.com/emqx/MQTTX/releases/tag/v1.8.2, maybe you should check the ACL configuration of the MQTT broker, if I don't have the problem I will close the issue now.
