### ISSUE TITLE
[Feature] Winget installation is still on 1.7.3

### ISSUE THREAD

**Issue by RaphaelBarabas** [emqx/MQTTX#1035]
#### Motivation

Installed MQTTX via winget, first thing after start is a "new version available" message. Winget installed 1.7.3 while 1.8.2 is available. That's inconvenient.

#### Detailed design

Please add 1.8.2 to the winget registry

#### More detail (optional)

To reproduce start _cmd_ as administrator, then type _winget install emqx.mqttx_

**Comment by ysfscream** [comment]
Hello, the installation package of Winget is unofficially maintained, we do not know how to update the package here, you can directly download the package on https://mqttx.app or on GitHub, after the automatic update has been supported, maybe you only need to download it once!

**Comment by ysfscream** [comment]
Thanks for the feedback, if there are no more questions, I will close the issue.

**Comment by andy778** [comment]
Would be better if one would create a github action on release to create this, that gives better trust to the winget package
