### ISSUE TITLE
Support WebSocket

### ISSUE THREAD

**Issue by ysfscream** [emqx/MQTTX#104]

**Comment by windbender** [comment]
This is a pretty important feature.

Given uptight nature of many corporate firewalls, using WSS is the only reasonable approach to navigating them.   Our broker will ONLY talk WSS for this reason.

**Comment by ysfscream** [comment]
@windbender Thanks for your attention, I will support it as soon as possible.

**Comment by ysfscream** [comment]
Already supported in [v1.3.0](https://github.com/emqx/MQTTX/releases/tag/v1.3.0), thank you for your feedback
