### ISSUE TITLE
Connect fail, MQTT.js onError trigger, Error: self signed certificate

### ISSUE THREAD

**Issue by ToBeIronMan** [emqx/MQTTX#1052]
![image](https://user-images.githubusercontent.com/53281822/185534112-6efdc532-9125-4560-9e83-9faf6b4704f8.png)

**Comment by ToBeIronMan** [comment]
![image](https://user-images.githubusercontent.com/53281822/185595329-82bc8d87-4329-4f9b-a511-f960c6a49a99.png)
还有这个

**Comment by oceanlvr** [comment]
可以贴下具体建立连接的过程呢

**Comment by ysfscream** [comment]
应该是证书问题，先验证一下证书的正确性

**Comment by ysfscream** [comment]
Thank you for your use, if there are no problems, I will close the issue now!
