### ISSUE TITLE
Topic is required

### ISSUE THREAD

**Issue by DreamPWJ** [emqx/MQTTX#1055]
Can receive messages, but cannot send messages
![image](https://user-images.githubusercontent.com/16730031/186115456-8fdcd95b-301c-4aae-8d29-f13edd2b4ac7.png)

**Comment by ysfscream** [comment]
Hi, please input the topic here. Need to publish to a topic.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/21299158/186299529-76ff3e0c-66c0-4b6c-b8bb-f6a45f9262bb.png">

**Comment by DreamPWJ** [comment]
Why not fill in by default?

**Comment by ysfscream** [comment]
> Why not fill in by default?

Because we don't know what topic you will use. Thanks for using!

**Comment by DreamPWJ** [comment]
> > Why not fill in by default?
> 
> Because we don't know what topic you will use. Thanks for using it!

only one
