### ISSUE TITLE
[Feature] keep the same options choose between web client and windows destop client

### ISSUE THREAD

**Issue by WangLei1993** [emqx/MQTTX#1069]
#### Motivation

![1](https://user-images.githubusercontent.com/7637623/189978756-25a97cd0-ff92-4d60-abc5-a365957acdab.jpg)
![2](https://user-images.githubusercontent.com/7637623/189978771-413294ea-c959-407d-a677-a6d024afc53d.jpg)
![3](https://user-images.githubusercontent.com/7637623/189978787-7502efef-9036-4c8a-9d36-c664a7d70ea3.jpg)
![4](https://user-images.githubusercontent.com/7637623/189978798-434c0b27-aa3c-498d-94d5-a49410380b10.jpg)

Now the client version I used is v1.8.2(the latest), but I found some different options between web client and windows destop client. Some differences like the picture above. It make me confused. For example, I must use the windows destop client rather than the web client, because I need to close SSL Secure for test.

#### Detailed design

Like the title what I said, keep the same options choose between different clients. It will make same feeling for users.

**Comment by ysfscream** [comment]
Yes, @WangLei1993 thank you for your feedback, currently, our web client and desktop client are not fully synchronized, we will fix this issue immediately.

**Comment by ysfscream** [comment]
Now we've synced to the web, thanks for using it. http://www.emqx.io/online-mqtt-client
