### ISSUE TITLE
[Help] I get the following error when connecting to broker.emqx.io-ca.crt with MQTT5 using MQTTX.

### ISSUE THREAD

**Issue by minamiengine** [emqx/MQTTX#1076]
I get the following error when connecting to broker.emqx.io-ca.crt with MQTT5 using MQTTX.

```
Error: unable to get local issuer certificate
```

## Environment

- OS: macOS Monterey 12.5
- MQTTX version: v1.8.2

## Detail

I use the following CA certificate:

https://assets.emqx.com/data/broker.emqx.io-ca.crt

The MQTTX configuration is as follows

- Host: mqtts://broker.emqx.io
- Port: 8883
- SSL/TLS: enabled
- Certificate: Self signed
- SSL Secure: enabled
- CA File: <Path to broker.emqx.io-ca.crt>
- Client Certificate File: None
- Client key file: None

MQTTX has the following error log

```
[2022-09-20 11:22:37] [ERROR] emqx-mqtt5-public-broker connect fail, MQTT.js onError trigger, Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
```

The same is true for Mosquitto.

```
mosquitto_pub \
    --cafile ~/Downloads/broker.emqx.io-ca.crt \
    -V mqttv5 \
    -D publish correlation-data 'light' \ -V
    -D publish response-topic 'ack/1' \
    -m "${message}" \ -D publish correlation-data 'light' \ -D publish response-topic 'ack/1
    -h broker.emqx.io \ -h broker.emqx.io
    -p 8883 -q 0 -d \ -h broker.emqx.io
    --topic testtopic/light \
    -i mydev
Client mymac sending CONNECT
OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Error: Protocol error
```

This occurs on both MacOS Monterey and Windows 10 pro.

**Comment by minamiengine** [comment]
Screenshot of MQTTX configuration:

![connection-settings](https://user-images.githubusercontent.com/7357125/191175124-c27ca54f-cca4-46b7-a1b7-37295c8d13cd.png)

**Comment by ysfscream** [comment]
Hi, thanks for using it.

> Error: unable to get local issuer certificate

This error means that you are using the wrong CA file. `broker.emqx.io` already provides CA signed unless you have a need for two-way authentication, but it is not recommended to use it on `broker.emqx.io`.

**Comment by minamiengine** [comment]
Thanks for the confirmation.

When I used the same configuration in May 2021, I was able to connect to broker.emqx.io successfully.
I am waiting for the results of the certificate verification.

**Comment by ysfscream** [comment]
Is this still an issue at the moment? I will close the issue first, if it still exists, please don't hesitate to reopen it.

**Comment by minamiengine** [comment]
Thank you for contacting us. No problem.
