### ISSUE TITLE
[Feature] Suggest removing the menu bar at the top of the window

### ISSUE THREAD

**Issue by bambuo** [emqx/MQTTX#1079]
#### Motivation

Improve interface consistency

#### Detailed design

no

#### Alternatives

The menu bar is not synchronized with the localization when it is localized, but of course if it can be synchronized with the localization it also achieves interface consistency

#### More detail (optional)

no

**Comment by ysfscream** [comment]
Hi, thanks for your feedback. There is indeed a problem here, but it may not be removed, but rather synchronized with i18n.

**Comment by Red-Asuka** [comment]
@bambuo Hi, thanks for your feedback and suggestions, I just added translations to the menu and it will be synchronized with the localization. We will include it in the new release, please look forward to!

**Comment by ysfscream** [comment]
Thanks for your suggestion. Now available on https://github.com/emqx/MQTTX/releases/tag/v1.9.0, I will close this issue.
