### ISSUE TITLE
[Feature] It is recommended to improve the processing method of received messages

### ISSUE THREAD

**Issue by bambuo** [emqx/MQTTX#1080]
#### Motivation

I found that the program began to get stuck when receiving more than 3000+messages, and then became more and more serious until it could not be used normally, and it was still the same after restarting the program. Only when I was lucky enough to clear the messages could it be relieved

#### Alternatives

The same topic only displays the last n records. It is better to let n customize the value

**Comment by ysfscream** [comment]
Hi, welcome to use https://github.com/emqx/MQTTX/releases/tag/v1.9.1-beta.1. It solves part of the problem, not all, but it should be a little better.

**Comment by ysfscream** [comment]
Hi. thanks for your feedback. Apologies for the long wait, welcome to https://github.com/emqx/MQTTX/releases/tag/v1.9.1, that should solve the problem and I will close this issue.
