### ISSUE TITLE
You need to make sure that /snap/mqttx/x1/chrome-sandbox is owned by root and has mode 4755.

### ISSUE THREAD

**Issue by XxKavosxX** [emqx/MQTTX#109]
I have installed MQTTX 1.1.1 by snap file, but when i try to run it i get:

"The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/mqttx/x1/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)"

And, after try to:

> sudo chmod 4755 /snap/mqttx/x1/chrome-sandbox

i get these same message. Can you help-me?

**Comment by ysfscream** [comment]
Hi, @XxKavosxX. Actually I haven't used sanp file for real installation, but I found some ways that might be useful to you.

**Comment by ysfscream** [comment]
Thanks for your feedback, I will close this issue.

**Comment by XxKavosxX** [comment]
Thanks!!
