### ISSUE TITLE
[Feature] Scripting function to implement alternate command execution function

### ISSUE THREAD

**Issue by DreamPWJ** [emqx/MQTTX#1105]
Using Script, I found that it is not possible to alternate between two commands, for example, on and off. Need to keep sending alternate commands to test stability

**Comment by ysfscream** [comment]
Hello, thank you for your feedback and use, could you please provide your specific test scenarios and data? I'll see if I can help you to finish editing a script.

**Comment by DreamPWJ** [comment]
@ysfscream {"command":"raise"}  and {"command":"putdown"}

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/195744143-d02e8798-3676-40e4-8f4e-399a6973646c.png)
I originally wanted to use the parity num++ method to implement this judgment condition, but there was a syntax error

**Comment by ysfscream** [comment]
Sorry, I found that there is really no way to implement this function, maybe I should bring `index` information for each payload so that the index can be used to publish out different data each time.

**Comment by DreamPWJ** [comment]
有结果了吗？@ysfscream

**Comment by ysfscream** [comment]
@DreamPWJ Sorry about that. Not currently implemented on the MQTT X desktop, perhaps you could start by using the [MQTT X CLI](https://mqttx.app/cli) and editing an automation script to change your content.

**Comment by Red-Asuka** [comment]
@DreamPWJ Hi, I just added message type and index to the script function, which should do what you need. We will include it in the new release, please look forward to! 

```js
function handlePayload(value, msgType, index) {
  if (index % 2 === 0) {
    value.command = 'putdown'
  } else {
    value.command = 'raise'
  }
  return JSON.stringify(value, null, 2)
}

execute(handlePayload)
```

<img width="634" alt="image" src="https://user-images.githubusercontent.com/38158783/199142458-ccdb9d4f-3fa6-4d86-b468-66d2462fd944.png">

**Comment by ysfscream** [comment]
Hi, thanks. This now available on https://github.com/emqx/MQTTX/releases/tag/v1.9.0. I will close this issue. You can copy the above codes to test.

**Comment by DreamPWJ** [comment]
@ysfscream 
Can it support scheduled sending?

**Comment by ysfscream** [comment]
YES of course. From the menu in the upper right corner, select Timed Messages.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/21299158/201587738-16bb598b-ef0e-4a53-ad66-2334aed6d173.png">

**Comment by DreamPWJ** [comment]
@ysfscream  run script  Can it support scheduled sending?

**Comment by ysfscream** [comment]
YES, run the script first and then use the timed message.
