### ISSUE TITLE
[Feature] Display response data in HEX.

### ISSUE THREAD

**Issue by sanketwadekar** [emqx/MQTTX#1106]
#### Motivation

I'm working with cbor encoded data. There is a feature to send cbor encoded payload in hex, but there is no option to view data in HEX. Having a functionality to display response messages in hex/plaintext/base64/json would really help.

**Comment by sanketwadekar** [comment]
Yes. This is exactly what I was looking for. I must have missed it.
Thanks.

**Comment by ysfscream** [comment]
You are welcome!
