### ISSUE TITLE
[BUG] Optimize the number of messages received

### ISSUE THREAD

**Issue by ysfscream** [emqx/MQTTX#1131]
Not sure the issue is fixed. At least, I'm running v1.8.3 and for some reason, got the history filled with more than 44000 entries. Now the MQTTX.db weight 14MB (only), and the app is absolutely unusable. It's so unresponsive that it will disconnect before I can clear the history. BTW, clearing while disconnected won't work.
My only workaround is to delete MQTTX.db and start from scratch, not cool :(

_Originally posted by @Tazintosh in https://github.com/emqx/MQTTX/issues/533#issuecomment-1303303468_

**Comment by xpunch** [comment]
Could we use a virtualize list to display history messages?

**Comment by ysfscream** [comment]
@xpunch Hi! Actually, it is currently used. But it doesn't solve the main problem, we have too many synchronous rendering tasks, message events are piling up and the rendering process is lagging, database read/write is not synchronized, etc.

So there are actually many places to adjust, thank you for your suggestions.

**Comment by xpunch** [comment]
Thanks for your patient explanation.

**Comment by ysfscream** [comment]
Apologies for the long wait, welcome to https://github.com/emqx/MQTTX/releases/tag/v1.9.1, that should solve the problem and I will close this issue.
