### ISSUE TITLE
[Bug] Directly stuck when subscribing to a topic with a large amount of data

### ISSUE THREAD

**Issue by LiuDuanWw** [emqx/MQTTX#1141]
win11 mqttx1.9.0
cpu i710700 内存32g 
在订阅很大数据量的topic时直接卡死 
![image](https://user-images.githubusercontent.com/41569238/201251779-0a521794-e83f-4b7f-aa56-bb118c676864.png)
并且想禁用或者删除订阅时都需要先连接 一旦连接整个mqttx都会直接卡死

**Comment by Red-Asuka** [comment]
感谢反馈，这是一个已知问题，我们正在针对性能进行优化。对于大量的订阅和消息接收您可以试试 [MQTT X CLI](https://mqttx.app/zh/cli) 的 bench 命令。

**Comment by ysfscream** [comment]
Duplicate of #1131

**Comment by ysfscream** [comment]
Apologies for the long wait, welcome to https://github.com/emqx/MQTTX/releases/tag/v1.9.1, that should solve the problem and I will close this issue.
