### ISSUE TITLE
Full ......

### ISSUE THREAD

**Issue by Serjaru** [emqx/MQTTX#1149]
Add new connection and sub

close appp

run again. and push button connect. No connect app silent!

try delete saved connection - no delete!

full..................

BEFORE RELEASE DO CHECK YOU APP!!!!!!!!!!!!

**Comment by ysfscream** [comment]
Hi, of course, I checked before releasing.

I don't know what's going on. I tried it based on your feedback and there was no such problem. Could you please give me a video screen?
