### ISSUE TITLE
Support payload  pretty print

### ISSUE THREAD

**Issue by leaxoy** [emqx/MQTTX#116]
Now if the payload is JSON, it still displays plaintext. I hope it can support JSON display. It is better if it can support more types, such as base64, msgpack, protobuf, etc.

**Comment by ysfscream** [comment]
Hi, @leaxoy Thanks for your comments and suggestions, we will implement it in future versions. This is really a good suggestion, Thanks again!

**Comment by ysfscream** [comment]
JSON display is already supported in [v1.3.0](https://github.com/emqx/MQTTX/releases/tag/v1.3.0) and can also be converted to Base 64, Hex. Thanks for your feedback.

**Comment by gam2046** [comment]
Is there a plan to support protobuf, or is it allowed to support protobuf through script

**Comment by ysfscream** [comment]
@gam2046 Yes, sorry for my late reply. We have plans to support it. You can open a new feature optimization issue so that we can organize it into the feature plan. THANKS!
