### ISSUE TITLE
[Bug] Fix 'Add New Subscription' dialog box problems.

### ISSUE THREAD

**Issue by LucidEye** [emqx/MQTTX#1166]
Using the Linux app on Ubuntu MATE...

When trying to add a new subscription, it should NOT be possible to open the dialog box for creating a new subscription UNLESS you are already connected to the broker!  
It is extremely frustrating to get all the way through setting up the new subscription, only to click on 'confirm' and have the app tell you you are not connected to a broker and then have to click 'cancel' and lose all the settings you just entered!!!!

Either have the 'not connected' warning popup BEFORE opening the New Subscription dialog box and make it so that it does not open if you are not connected to a broker....
OR...
Make it so that you DON'T have to be connected to a broker in order to create new subscriptions!  (This would be the preferred option!)

Also, the first time you open the add new subscription dialog box, it is automatically filled in with information from a subscription I already added instead of being a blank template.  Closing the dialog box and reopening it clears it to a blank template. I believe this is another bug.  It needs to be fixed to help avoid accidentally overwriting the settings for the existing subscription.

Also, when typing names into the topic field, if you accidentally hit enter, it will automatically disconnect you from the broker?!?!?! Of course this again causes the loss of all the settings you just made in the new subscription dialog box!!!

Also, WHY does the app automatically remove any spaces I type when entering a name in the 'Alias' field?!?!?!  That is also extremely annoying.  Is there some reason we are not allowed to use spaces in the alias naming schema?

Seriously, do you guys do any testing before you declare an app to be a "stable release"?  I really expected MUCH more from an app that so many articles and tutorials are recommending as a 'top pick".

**Comment by ysfscream** [comment]
First of all, thank you very much for your feedback, and thanks for your expectations, too.

Your suggestions benefit us, and many are being worked on to fix and improve.

But finally, I want to say that I understand your feelings. We are making progress, and so is MQTT X. Thanks! Still, MQTT X is currently an open-source project, we have a limited number of developers and testers, and of course, we can only rely on community feedback to improve it. I appreciate your use; maybe you can help to participate in testing and maintenance by participating and listing some alteration plans or something, but we can not guarantee 100% that it will be the most stable and reliable software. I hope you can get a better experience when we update it step by step. If not, I am sorry. We try it.

**Comment by LucidEye** [comment]
Maybe you should do more thorough testing before you call your software a "stable release". 
I am not your beta tester. So sick of lazy devs like you who dump your buggy software on the public and expect them to do your testing work for you.
I have already wasted enough of my time with your buggy software.
The general public isn't here to be your beta tester. 
That is the responsibility of the software engineers and developers on your team, if you even have a team.
People need software that works, not software that wastes more of their time.
The reason it is upsetting is because your software is being advertised in so many articles and tutorials as a "top pick", but it is obviously not even ready to be out of beta yet.
Maybe you should make sure it actually works before advertising it?
     On Tuesday, December 13, 2022, 03:16:13 AM MST, YuShifan ***@***.***> wrote:  
 
 


First of all, thank you very much for your feedback, and thanks for your expectations, too.

Your suggestions benefit us, and many are being worked on to fix and improve.

But finally, I want to say that I understand your feelings. We are making progress, and so is MQTT X. Thanks! Still, MQTT X is currently an open-source project, we have a limited number of developers and testers, and of course, we can only rely on community feedback to improve it. I appreciate your use; maybe you can help to participate in testing and maintenance by participating and listing some alteration plans or something, but we can not guarantee 100% that it will be the most stable and reliable software. I hope you can get a better experience when we update it step by step. If not, I am sorry. We try it.

**Comment by ysfscream** [comment]
OK.

**Comment by ysfscream** [comment]
YES, you're right, thanks.

**Comment by Red-Asuka** [comment]
@LucidEye We apologize for the poor experience you encountered. The issues you reported have now been fixed. We invite you to upgrade and experience version 1.9.1.

- If the client is not connected, clicking the "New Subscription" button will now prompt you that the client is not connected.
- The bug that prevented the "add subscription" form from resetting correctly has also been fixed.
- In fact, topic alias are only trimmed of excess whitespace, but you can still use single spaces in the alias.

> Also, when typing names into the topic field, if you accidentally hit enter, it will automatically disconnect you from the broker?!?!?! Of course this again causes the loss of all the settings you just made in the new subscription dialog box!!!

We regret that we were unable to reproduce the issue. 

If you still experience this issue after upgrading to v1.9.1, please don't hesitate to provide further feedback.
