### ISSUE TITLE
Split message list view by subscriptions

### ISSUE THREAD

**Issue by leaxoy** [emqx/MQTTX#118]
The message list view is divided according to the subscription relationship. Now all the messages of the subscription are in the same view. If there are multiple subscriptions, it will be very inconvenient to view. You can consider putting the messages of different subscriptions in different message views.

**Comment by ysfscream** [comment]
@leaxoy Sorry for the late reply, after discussion we think this is a good suggestion for improvement. We will think about how to implement split messages, but now you can use search by topics to use it.

**Comment by ysfscream** [comment]
Hi, [v1.3.1](https://github.com/emqx/MQTTX/releases/tag/v1.3.1) version has realized the function of clicking the topic to split the message view, thank you very much for your suggestion, I will close this issue. :)
