### ISSUE TITLE
[Feature] DateTime on CLI output

### ISSUE THREAD

**Issue by cocoaway** [emqx/MQTTX#1192]
#### Motivation

Locate logs based on date and not just time. Being able to write CLI sessions for multiple days to a file.
Possibility to choose the date format.

#### Detailed design

Also add the date to the log time
[2023-01-11 08:39:17] ...Connecting...
[2023-01-11 08:39:18] ✔ Connected
[2023-01-11 08:39:19] … Subscribing to ...

**Comment by Red-Asuka** [comment]
Thank you for your suggestion! Logging feature is indeed currently lacking in MQTT X CLI, I will implement it in the next version.

**Comment by ysfscream** [comment]
Feel free to use https://github.com/emqx/MQTTX/releases/tag/v1.9.1, I will close the issue first, if it still exists you can reopen it.
