### ISSUE TITLE
[Feature] Saving output data to a file

### ISSUE THREAD

**Issue by vukmirovic98** [emqx/MQTTX#1210]
#### Motivation
Saving output data to a file ? 

#### Detailed design
Add a button to save data to csv/json file?

**Comment by Red-Asuka** [comment]
By clicking the action bar button at the top, you can import and export of current data, or import and export all data on the settings page.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/38158783/213354070-e3b2b9f5-6cda-4d6f-b6bb-4dd9864283c4.png">

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/38158783/213354280-e3042398-5b5a-49ea-82e0-3e81246ec2b5.png">

**Comment by ysfscream** [comment]
Is this still an issue at the moment? Feel free to use https://github.com/emqx/MQTTX/releases/tag/v1.9.1, I will close the issue first, if it still exists you can reopen it.
