### ISSUE TITLE
[Feature] Only mqtt and mqtts are supported

### ISSUE THREAD

**Issue by yayuntian** [emqx/MQTTX#1218]
#### Motivation

Can support ws and wss protocols

**Comment by Red-Asuka** [comment]
Do you mean the MQTT X CLI? This is a limitation due to different environments that we cannot support. If you want to use the ws or wss protocol, you can use MQTT X Web or MQTT X Desktop

**Comment by yayuntian** [comment]
> Do you mean the MQTT X CLI? This is a limitation due to different environments that we cannot support. If you want to use the ws or wss protocol, you can use MQTT X Web or MQTT X Desktop

It's a sad thing that I just have to accept
