### ISSUE TITLE
[Bug] Can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by niclascarlstedt** [emqx/MQTTX#1236]
#### What did I do

After installing MQTTX either by brew or by dmg file on MacOS Ventura 13.1 I get an error when trying to start the application. 
"**"MQTTX.app" can't be opened because Apple cannot check it for malicious software.**"
See attached screenshot.

#### Expected

The expected result is that the software should open.

#### Environment

- OS: macOS Ventura 13.1
- MQTTX v1.9.1

#### More detail

<img width="260" alt="image" src="https://user-images.githubusercontent.com/909479/217522190-2b2bc9d4-70be-4e09-9511-59d2896563ad.png">

**Comment by ysfscream** [comment]
@niclascarlstedt Hi. Thanks for using it. This part seems odd, we've already signed in with our Apple developer account, and by definition, there are no security issues.

But to fix this current problem, you need to go to System Preferences -> Privacy & Security -> Continue to open.

We'll keep an eye on this issue until it doesn't happen again.

**Comment by caraar12345** [comment]
Hey - just came here as I'm seeing the same thing and it looks like the app hasn't been notarised by Apple.

```bash
❯ spctl -a -vvv -t install /Applications/MQTTX.app
/Applications/MQTTX.app: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: Shifan Yu (72J4Z38V6Q)
```

In comparison to 1Password 8 for example:

```bash
❯ spctl -a -vvv -t install /Applications/1Password.app
/Applications/1Password.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: AgileBits Inc. (2BUA8C4S2C)
```

**Comment by ysfscream** [comment]
Hi all, the notarization issue with MQTTX for macOS has been resolved.

You can now safely download and install the latest version https://github.com/emqx/MQTTX/releases/tag/v1.9.2. Please try reinstalling the 1.9.2 version, and I will close this issue. Feel free to reach out if you have any more problems, and I'll reopen the case.

```shell
spctl -a -vvv -t install /Applications/MQTTX.app
/Applications/MQTTX.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: EMQ Sweden AB (26N6HYJLZA)
```

**Comment by martinscholz83** [comment]
Got it. It needs to be upload to the notarization service after it was signed.

**Comment by ysfscream** [comment]
@martinscholz83 Sorry for being late. YES, you gone be should upload the file like this:

```shell
xcrun altool --notarize-app --primary-bundle-id xxx.xxx.xxx --username xxx --password xxx --file xxx
```

**Comment by bj00rn** [comment]
Still an issue for me using homebrew installation.

**Comment by bj00rn** [comment]
> Still an issue i think using homebew [cask](https://github.com/Homebrew/homebrew-cask/blob/2ad70ee74fe872f001c922bcdcf94924a98d731e/Casks/m/mqttx.rb)

**Comment by bj00rn** [comment]
> Hi all, the notarization issue with MQTTX for macOS has been resolved.
> 
> You can now safely download and install the latest version https://github.com/emqx/MQTTX/releases/tag/v1.9.2. Please try reinstalling the 1.9.2 version, and I will close this issue. Feel free to reach out if you have any more problems, and I'll reopen the case.
> 
> ```shell
> spctl -a -vvv -t install /Applications/MQTTX.app
> /Applications/MQTTX.app: accepted
> source=Notarized Developer ID
> origin=Developer ID Application: EMQ Sweden AB (26N6HYJLZA)
> ```
> 
> Thanks for your feedback.

Still an issue I think using homebew [cask](https://github.com/Homebrew/homebrew-cask/blob/2ad70ee74fe872f001c922bcdcf94924a98d731e/Casks/m/mqttx.rb)

**Comment by robertorodriguezv** [comment]
I'm afraid this is still not working, using homebrew or installing from the downloaded .dmg

Tested on several m1 and m2 Macs using macOS between  13.6.3 and 14.2.1

spctl -a -vvv '/Applications/MQTTX.app' 
/Applications/MQTTX.app: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: EMQ Sweden AB (26N6HYJLZA)

**Comment by Red-Asuka** [comment]
@ysfscream, It seems that this issue still exists in version v1.9.10, https://askemq.com/t/topic/8075
