### ISSUE TITLE
[Bug] Linux cant save data...

### ISSUE THREAD

**Issue by g6094199** [emqx/MQTTX#1237]
#### What did I do
i tried to save the logged data as csv, xls

#### What happened

the data gets stored to my home folder where mqttx sees but my linux disto does NOT!

#### Expected
store the data to home or other folder.

#### Environment

- OS: Debian Bookworm
- MQTTX version: 1.9.1

#### More detail

do: export data-> choose csv or xls -> "where to save" gets opened in the home folder -> hit save.
now try to find that file...you wont find it. even with: sudo find / -name filename
next time you try to save some data mqttx sees the already existing file....must be another dimension!
hint: while the  "where to save" windows is open you wont see any already existiing data/folders in your home folder which also shows that there is a problem.

**Comment by JimMoen** [comment]
Hi. I've tried reproduce this issue on Arch Linux(snap installed from [aur/mqttx-bin](https://aur.archlinux.org/packages/mqttx-bin)).
But the files can be stored and read.

Could you provide more infomation such as _**electron version, installation method, etc..**_

**Comment by ysfscream** [comment]
Or could you please check your directory permissions for save data on MQTT X?

**Comment by ysfscream** [comment]
Or could you please check your directory permissions for save data on MQTT X?

**Comment by ysfscream** [comment]
Or could you please check your directory permissions for save data on MQTT X?

**Comment by ysfscream** [comment]
Or could you please check your directory permissions for save data on MQTT X?

**Comment by g6094199** [comment]
MQTTX was installed as snap from the store. maybe the problem is there?

**Comment by ysfscream** [comment]
@g6094199 YES, maybe. We will check it for flatpak.

**Comment by ysfscream** [comment]
If there are no issues, I will close this issue. If any issues still exist, please reopen it.
