### ISSUE TITLE
[Feature] Topics as a tree

### ISSUE THREAD

**Issue by ClemTB** [emqx/MQTTX#1244]
#### Motivation

The view of the messages on the subscribed topics is not readable

#### Detailed design

I'd like to have a tree view of the topics. The roots are the subscribed topics, the sub nodes are the direct sub topics, and so on.
The displayed messages are filtered by the selected node in the tree  so I can see only the messages from the branch I'm interested in

#### Alternatives

I don't see any

#### More detail (optional)

A plus would be a configurable summary of each nodes after the name of the sub topic (total messages since connection, count of subtopics, ...) 
Also making possible for the tree path to be higlight when a message comes would be great to identify the active branches of the server
In that case it would be also nice to click on a node to set the topic in the "send message" area

**Comment by ysfscream** [comment]
Hi. Thank you for your feedback.

You are having difficulty viewing messages on subscribed topics and would like a tree view. We understand that this would make it easier for you to filter messages based on the branch you are interested in. The mqtt-explorer has already supported the Topic tree. And this feature request will be planned for the next MQTT X release plan. 

We will consider your suggestion of clicking on a node to set the topic in the "send message" area and evaluate its feasibility. Thank you again for your feedback, and we will do our best to improve the user experience in future updates.

**Comment by ClemTB** [comment]
How can I get the Topic tree?
In case we are not in the same page, here is an exemple of implementation I have in mind:
![image](https://user-images.githubusercontent.com/29354251/222722067-035766e5-4cc6-40fa-90c8-16db3b0c59af.png)

**Comment by ysfscream** [comment]
YES. MQTT X has no support yet.

**Comment by hailwood** [comment]
This is the only thing stopping me switching from https://mqtt-explorer.com/

**Comment by ysfscream** [comment]
@hailwood This will be added in the upcoming graphical feature, although it may not be exactly the same, we just hope that users can get better debugging results and experience. Thank you very much for your feedback.

**Comment by adamalfath** [comment]
Nice, finally moving from backlog to target milestone

**Comment by woifes** [comment]
What is the status of this? It was moved from milestone to milestone for a while now.

**Comment by anth-git** [comment]
This app is unusable without this feature. In MQTT Explorer not only there is a tree, but also only the latest message is displayed, so it's far easier to see what's going on, for example, what parts of a message have changed. And if I really need history, I can access it too. The chat-like window for MQTT messages is extremely impractical. This is maybe good if you have one topic with small infrequent messages, but even then what do I need 10000 messages in the window for?

**Comment by ysfscream** [comment]
Topic Tree is available at https://github.com/emqx/MQTTX/releases/tag/v1.11.0

This feature is currently in the `Beta` version, and there may be some instabilities or inability to meet expectations. However, I think the basic function of viewing can be achieved.

Therefore, I will close this issue. We can discuss suggestions or bug reports for topic tree milestone 2 in the issue if there is new feedback or discussion. Thank you all.
