### ISSUE TITLE
[Bug] QoS always shows 0

### ISSUE THREAD

**Issue by eos1d3** [emqx/MQTTX#1245]
#### What did I do
Use MQTTX to receive messages

#### What happened
MQTTX receives all messages, but Qos is displayed as 0 even if msg is sent by QoS 1

#### Expected
Show 0 or 1 as per publish side

#### Environment
macOS 12.6.3

- MQTTX version, v1.6.0

#### More detail

I use eclipse.paho to verify what was sent. It can show Qos 0 or 1 correctly, but MQTTX just always shows 0.

**Comment by ysfscream** [comment]
@eos1d3 Hi, thanks for your using and providing the information. Please update the MQTT X version to 1.9.1 and ensure the config with eclipse.paho is the same. But you should sub a QoS 1 topic first, I think.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/21299158/223637935-c3c0e047-dd91-486c-bb84-89c4886bfaf7.png">

**Comment by eos1d3** [comment]
Latest version does not have this issue. Thanks!
