### ISSUE TITLE
[Bug] I can't send the message after I unchecked the User Properties

### ISSUE THREAD

**Issue by Seamain** [emqx/MQTTX#1246]
#### What did I do

I want to send a message without User Properties, so I unchecked the User Properties, then I find I can't send the message.

#### What happened

I can't send the message

#### Expected

I can send the message without the User Properties

#### Environment

- OS: Windows11 Pro for Workstations 22621.1344
- MQTTX version, v1.9.1

#### More detail

![](https://i.imgur.com/l5yVI1g.gif)

**Comment by ysfscream** [comment]
@Seamain Hi, thanks for your feedback. Yes, this is a BUG. we will fix it in the next release.

**Comment by ysfscream** [comment]
Fixed in https://github.com/emqx/MQTTX/releases/tag/v1.9.2
Thanks
