### ISSUE TITLE
[Bug] Subscriptions going from one connection to another

### ISSUE THREAD

**Issue by V4G4X** [emqx/MQTTX#1248]
#### What did I do

I had a few connections. This is regarding the cases where I'd quickly click on different connections one after the other.

#### What happened

When moving from one connection to another, one of the previous connection's subscription is moved to the new connection. 
Which causes a deadlock.  
Can't remove the subscription because it required the connection to be online.  
Can't bring the connection online because that connection can't subscribe to that newly transferred subscription.  

#### Expected

No such transfer should happen when quickly going through multiple connections.

#### Environment

- OS: macOS Ventura 13.2.1
- MQTTX version, e.g. v1.9.1

#### More detail

The topic `node/cQ2zcUQjiQkGpLux97wUMn/otaurl` does not belong in the connection: **cQ2zcUQjiQkGpLux97wUMn**.  
![image](https://user-images.githubusercontent.com/34249137/225316948-675a5012-bc06-458e-9fa4-9b4b2fd6ad51.png)

And the connection **cQ2zcUQjiQkGpLux97wUMn** is missing the topic `node/cQ2zcUQjiQkGpLux97wUMn/otaurl`.
![image](https://user-images.githubusercontent.com/34249137/225317086-3a0976de-01d7-4596-bf83-38e010f5186f.png)

Can't remove the topic because that required the connection online
![image](https://user-images.githubusercontent.com/34249137/225317446-42055609-b48e-4dee-a425-8b6bb0a0e22e.png)

Can't bring the connection online because it is not allowed to subscribe to that topic
```
[2023-03-15 18:36:39] [INFO] MQTTX client with ID 32809650-3835-4afa-a1c2-e04c54210fcd assigned
[2023-03-15 18:36:39] [INFO] Connect client cQ2zcUQjiQkGpLux97wUMn, MQTT/SSL connection: mqtts://a3jf85c407as92-ats.iot.us-east-1.amazonaws.com:8883
[2023-03-15 18:36:42] [INFO] cQ2zcUQjiQkGpLux97wUMn connect success, MQTT.js onConnect trigger
[2023-03-15 18:36:42] [INFO] Topic: node/e6LmmRJ7692rRNuWWD5Qq5/otaurl is resubscribing
[2023-03-15 18:36:42] [ERROR] Topic: subscribe error, Error: Connection closed 
[2023-03-15 18:36:42] [INFO] cQ2zcUQjiQkGpLux97wUMn connect close, MQTT.js onClose trigger
```

**Comment by ysfscream** [comment]
Hi, sorry about that. Based on your description, I can not reproduce this issue. Could you please provide more details? Is the step only the quick click on different connections one after the other?

**Comment by ysfscream** [comment]
If there are no issues, I will close this issue. If any issues still exist, please reopen it.
