### ISSUE TITLE
[Bug] Cannot connect without the path

### ISSUE THREAD

**Issue by ademyankov** [emqx/MQTTX#1257]
My host URL for the broker doesn't have a path. There is no way in the UI not to provide a path.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/13845895/230133819-8fda9238-802e-467d-8823-5c57b99cf354.png">

So if I try to use just `/` it does not connect. And there is no error whatsoever. It just shows nothing like it is connected. But if you try to send something or subscribe then it says 'client not connected'

<img width="805" alt="image" src="https://user-images.githubusercontent.com/13845895/230133511-3ab2727c-53e0-4c5c-b7af-f7daf023a254.png">

- OS: Windows 10 Enterprise 10.0.19045
- Chrome Version 112.0.5615.50 (Official Build) (64-bit)
- MQTTX v1.9.1

**Comment by ysfscream** [comment]
Hi. @ademyankov I understand that you're experiencing connection issues with MQTTX, and your broker may not have a path configured for MQTT over WebSocket. Usually, an MQTT over WebSocket connection has a path, such as `/mqtt`, which is used to specify the WebSocket endpoint on the server.

**Comment by ademyankov** [comment]
Yes, I guess it's because of the protocol `ws` or `wss.` My broker doesn't use WebSockets. I used the desktop version of MQTTX, and it all works like a charm! I guess you can close it and not consider it a bug if the online web version is not supposed to be used with any other protocols but `ws/s.`

Thanks, @ysfscream, for the prompt response!

**Comment by ysfscream** [comment]
Yes, the web version only supports WebSocket, which is due to browser limitations. Thank you for using it 🙌
