### ISSUE TITLE
[Feature] Can proxy network be supported? http, socks

### ISSUE THREAD

**Issue by yuanfanggo** [emqx/MQTTX#1283]
#### Detailed design

Describe the solution you'd like, a clear and concise description of what you want to happen.

#### Alternatives

Describe alternatives you've considered, what other designs have been considered? What is the impact of not doing this?

**Comment by ysfscream** [comment]
@yuanfanggo Thanks for opening this issue and suggesting the proxy network support feature. Unfortunately, proxy support is not implemented yet. We have planned for this feature previously but have not had the resources to complete it yet. We will let you know if and when proxy support is added soon.

Duplicate of #706

**Comment by yuanfanggo** [comment]
thank you
