### ISSUE TITLE
[Bug] UI - Wrong format of sub topic column

### ISSUE THREAD

**Issue by mokton** [emqx/MQTTX#1319]
I'w used many versions of mqttx, they all have an UI problem, that is the wrong format of subscription topic column shown as the image below.
<img width="962" alt="微信截图_20230626092758" src="https://github.com/emqx/MQTTX/assets/13097167/258dd848-3e4c-4a04-ad64-2eeb4009fca6">
Hopefully in the next version it's displayed in the correct format.
Thanks for your excellent work!

**Comment by ysfscream** [comment]
Hello, @mokton 

Thank you for your continued support and usage of our MQTTX software. We sincerely apologize for the issue you have encountered.

Your feedback is invaluable. We have noted the problem you mentioned regarding the subscription topic column display format. Our development team will work on this issue immediately and aim to fix it in the next version. We hope the new version can provide a better user experience for you.

**Comment by ni00** [comment]
Hello @mokton , could you please specify your MQTTX version and the operating system you are using? Additionally, could you provide a detailed explanation of how to reproduce this bug? Once I am able to replicate it, I will proceed with fixing the issue.

**Comment by mokton** [comment]
> Hello @mokton , could you please specify your MQTTX version and the operating system you are using? Additionally, could you provide a detailed explanation of how to reproduce this bug? Once I am able to replicate it, I will proceed with fixing the issue.

MQTTX Version： v1.9.3

**Comment by mokton** [comment]
> Hello @mokton , could you please specify your MQTTX version and the operating system you are using? Additionally, could you provide a detailed explanation of how to reproduce this bug? Once I am able to replicate it, I will proceed with fixing the issue.

MQTTX Version： v1.9.3
System: Windows 11 Pro 22H2
My topic names are long, the extra part is displayed as ... , so the "QoS x" is displayed on the next line.
Is it possible to allow users to customize the width of the topic column?
Topic examples:
terminalbox/+/system/disconnect
terminalbox/5b49d9d6c6333252bdccb4e4361a253d/data

**Comment by mokton** [comment]
> Hello @mokton , could you please specify your MQTTX version and the operating system you are using? Additionally, could you provide a detailed explanation of how to reproduce this bug? Once I am able to replicate it, I will proceed with fixing the issue.

Hi @ni00 , I guess it's probably the vertical scrollbar that's causing this problem. You can try to add more long topics.

**Comment by ysfscream** [comment]
Welcome to try the new MQTTX release at https://github.com/emqx/MQTTX/releases/tag/v1.9.5. If problems persist, please let us know and we will quickly address them.
