### ISSUE TITLE
[Help] How publish message with HEX payload using CLI?

### ISSUE THREAD

**Issue by LucasYao93** [emqx/MQTTX#1328]
#### Describe the problem you Confuse

A clear and concise description of what you are confusing about.

#### More detail (optional)

Add any other context or screenshots.

**Comment by ni00** [comment]
Hello! I have submitted some code. The link is: https://github.com/emqx/MQTTX/pull/1333

Based on your request, I add a ` -f ` parameter to the `  mqttx pub `  command, which will allow you to specify that the content you publish is in hexadecimal format (also supprot base64 or json).

```
mqttx pub -t ... -h ... -p ...  -m '68656c6c6f' -f "hex" 
```

**Comment by LucasYao93** [comment]
> Hello! I have submitted some code. The link is: #1333
> 
> Based on your request, I add a `-f` parameter to the ` mqttx pub` command, which will allow you to specify that the content you publish is in hexadecimal format (also supprot base64 or json).
> 
> ```
> mqttx pub -t ... -h ... -p ...  -m '68656c6c6f' -f "hex" 
> ```

Thanks for you response, But the `mqttx pub` not has -f parameter. It's exist in `mqttx sub`.

**Comment by LucasYao93** [comment]
> Hello! I have submitted some code. The link is: #1333
> 
> Based on your request, I add a `-f` parameter to the ` mqttx pub` command, which will allow you to specify that the content you publish is in hexadecimal format (also supprot base64 or json).
> 
> ```
> mqttx pub -t ... -h ... -p ...  -m '68656c6c6f' -f "hex" 
> ```
Has the code been released?

**Comment by ni00** [comment]
> > Hello! I have submitted some code. The link is: #1333
> > Based on your request, I add a `-f` parameter to the ` mqttx pub` command, which will allow you to specify that the content you publish is in hexadecimal format (also supprot base64 or json).
> > ```
> > mqttx pub -t ... -h ... -p ...  -m '68656c6c6f' -f "hex" 
> > ```
> 
> Has the code been released?
The code has not been released yet.
You can wait for the upcoming release (version 1.9.4, which will be available soon), or compile the code yourself from the 'cli' folder in the mqttx/main repository. Compiling the code is a simple process, and you can refer to [mqttx.app](https://mqttx.app/docs/cli/development)  for detailed instructions.

**Comment by ysfscream** [comment]
> Has the code been released?
@LucasYao93 Thank you for your feedback. Perhaps we will release version 1.9.4 next week.

**Comment by ysfscream** [comment]
Hi! Thank you for your feedback. Currently, we have added support for it in https://github.com/emqx/MQTTX/releases/tag/v1.9.4.
