### ISSUE TITLE
[Feature] A Way to Display the Reason Code when a Connection Is Terminated

### ISSUE THREAD

**Issue by p0fi** [emqx/MQTTX#1329]
#### Motivation
It's helpful for a client to know what was the exact reason for being disconnected by a server. MQTT has an extensive reason code list for this. Currently there does not seem to be a way for MQTTX to show this reason code.

#### Detailed design
When a connection is terminated provide a way to see the reason.

#### Alternatives
–

#### More detail (optional)
The reason code list from the MQTT 5 specification can be found [here](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901031)

**Comment by ysfscream** [comment]
Thank you for your feature request. @p0fi We agree that displaying the MQTT reason code when a connection is terminated canprettyuite beneficial. This suggestion has been noted, and we'll consider incorporating itour future updates. Your input is valuable in helping us improve MQTTX. Thank you!

**Comment by ysfscream** [comment]
Thanks for your feedback. It is now available at: https://github.com/emqx/MQTTX/releases/tag/v1.9.10. Welcome to try it.
