### ISSUE TITLE
[Bug] topic $sys is rejected

### ISSUE THREAD

**Issue by cppcoffee** [emqx/MQTTX#1338]
#### What did I do

I understand the topic rejecting `$SYS`, but lowercase `$sys` is rejected as well. the expectation is that `$sys` is allowed.

#### What happened

Get an error.

#### Expected

`$sys` topic is allowed.

#### Environment

- OS: OS version, e.g. macOS Big Sur 11.1
- MQTTX version, e.g. v1.5.0

#### More detail

location:

https://github.com/emqx/MQTTX/blob/3ce7e8c7478307f86333a2ce5cc6437a1181b14d/web/src/components/SubscriptionsList.vue#L437

**Comment by ysfscream** [comment]
Hi! Thank you for using MQTTX. `$SYS` is an allowed subscription and the code only intends to specifically handle metrics data within `$SYS` topics.

Additionally, I see that you are on an older version and I recommend upgrading to our latest version for an improved experience.

<img width="1137" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/76796e67-6d29-4732-89b6-af6ab5d6ccba">

**Comment by cppcoffee** [comment]
Hi @ysfscream . you are right, the version I am using is too old, I can subscribe to `$sys` prefix topic now after updating the version.

close issue.
