### ISSUE TITLE
[Bug] V1.9.4 escape "\n" in message type text

### ISSUE THREAD

**Issue by ThuanDoHung** [emqx/MQTTX#1355]
#### What did I do

I have send a message type text with one character \n ex: "send new message with \n in text"

#### What happened

Auto escape \n in text, it send :  "send new message with n in text" --> replace "\" to ""

#### Expected

What is the expected result.

#### Environment

- Ubuntu 22.04
- MQTTX version, e.g. v1.9.4

#### More detail

not bug in v1.9.3

**Comment by ni00** [comment]
Hello @ThuanDoHung , I appreciate your feedback. I have addressed the bug you reported in the [PR: fix text processing error](https://github.com/emqx/MQTTX/pull/1359), and it will be included in the upcoming version (1.9.5) of MQTTX. Thank you for bringing this to my attention.

**Comment by ysfscream** [comment]
Thanks for your feedback!

Welcome to try the new MQTTX release at https://github.com/emqx/MQTTX/releases/tag/v1.9.5. If problems persist, please let us know, and we will quickly address them.
