### ISSUE TITLE
[Bug] An error occurs when a received message contains a topic alias

### ISSUE THREAD

**Issue by tigercl** [emqx/MQTTX#1398]
#### What did I do

I use MQTTX CLI to subscribe to a topic. When the server forwards a message containing the topic alias to MQTTX CLI, the CLI will print the following error log:

![1161690970213_ pic](https://github.com/emqx/MQTTX/assets/15085956/533d6215-0176-4562-b9b2-0b0912568773)

And, when I set a topic alias, and send multiple messages with the `--multiline` option, each message will contain both the topic and the topic alias:

```
mqttx pub --topic mytopic --topic-alias 1 --stdin --multiline
```

In fact, except for the first message, all subsequent messages only need to contain the topic alias.

#### Expected

MQTTX CLI should receive messages with the topic alias normally.

#### Environment

- OS: OS version, e.g. macOS Big Sur 11.1
- MQTTX version, e.g. v1.9.4

**Comment by ysfscream** [comment]
Thank you for the feedback. The issue should be fixed in v1.9.7. Please feel free to test and provide additional feedback.
