### ISSUE TITLE
[Help] can't send empty retain payload after upgraded to v1.9.5

### ISSUE THREAD

**Issue by manhere** [emqx/MQTTX#1407]
can't send empty retain payload(to clean retain msg) after upgraded to v1.9.5
v1.9.3 is ok

**Comment by ysfscream** [comment]
@manhere,

Thank you for bringing this to our attention. We recognize the severity of this bug and have prioritized its fix. We aim to address it in the upcoming release.

Furthermore, we're considering implementing a simplified procedure for clearing retained messages to enhance user experience.

Again, we appreciate your feedback and support.

**Comment by ysfscream** [comment]
Thank you for being so patient!

We have addressed and resolved this issue in the https://github.com/emqx/MQTTX/releases/tag/v1.9.6

It helps us continually improve our product. If you encounter any issues while using the new version, please do not hesitate to let us know.

Thank you once again!
