### ISSUE TITLE
[Feature] Support for bigint on the JSON parsing

### ISSUE THREAD

**Issue by BinarSkugga** [emqx/MQTTX#1410]
#### Motivation

Support for 64bit numbers. Because JS uses a 52bit mantissa for all numbers, ids are truncated.

#### Detailed design

I know there is a couple of library in JS that do this:
https://www.npmjs.com/package/json-bigint (https://www.npmjs.com/package/@types/json-bigint)
https://www.npmjs.com/package/json-bigint-patch

#### Alternatives

Currently using the plaintext view.

#### More detail (optional)

With parsing:
![image](https://github.com/emqx/MQTTX/assets/7575628/24e8deb7-514b-45e9-bd6d-41fc4facef72)

Without:
![image](https://github.com/emqx/MQTTX/assets/7575628/5616462b-d998-4819-ad4d-9b9ca30869c5)

**Comment by ysfscream** [comment]
@BinarSkugga Thank you for the detailed information and suggestions! I noticed that this issue seems related to https://github.com/emqx/MQTTX/issues/740

We will address this in upcoming versions. Thanks again for your contribution and patience!

**Comment by ysfscream** [comment]
This issue has been fixed in the [MQTTX v1.9.7 release](https://github.com/emqx/MQTTX/releases/tag/v1.9.7). Thank you for your feedback.
