### ISSUE TITLE
[Help] only wss:// and ws:// no mqtt:// selection in new connection on Docker webclient

### ISSUE THREAD

**Issue by alwashe** [emqx/MQTTX#1416]
I've been facing an issue with the Docker version of the web client. When attempting to create a new connection, the only available options are wss:// and ws://. Unfortunately, there's no mqtt:// option.

Installation: docker run -d --name mqttx-web -p 80:80 emqx/mqttx-web

Host: x86_64, Linux Alpine

**Comment by ysfscream** [comment]
Hi @alwashe,

Thanks for reaching out!

The MQTTX web client, whether used online or through Docker, indeed only supports `ws://` and `wss://` connections. This is because browsers can only facilitate MQTT communications through WebSocket and do not permit direct TCP connections, which is typical for web MQTT applications.

I hope this clears up the confusion. Feel free to share any other questions or feedback.

**Comment by ysfscream** [comment]
Hi! If there are no other concerns, I will temporarily close this issue. Thank you for using MQTTX.

**Comment by audas** [comment]
> Hi @alwashe,
> 
> Thanks for reaching out!
> 
> The MQTTX web client, whether used online or through Docker, indeed only supports `ws://` and `wss://` connections. This is because browsers can only facilitate MQTT communications through WebSocket and do not permit direct TCP connections, which is typical for web MQTT applications.
> 
> I hope this clears up the confusion. Feel free to share any other questions or feedback.

Hi - there is limited information on how to make this connection between the web-interface and an mqtt broker.

I am setting up a Node.js web socket server to forward the mqtt-broker output to the mqttx is tis something you would suggest?


`const WebSocket = require('ws');
const mqtt = require('mqtt');

const brokerUrl = 'mqtt://192.168.20.37:1883';
const wsPort = 8090; // New WebSocket port

const wss = new WebSocket.Server({ port: wsPort });
const client = mqtt.connect(brokerUrl);

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(data) {
    client.publish('test/topic', data);
  });

  client.on('message', function (topic, message) {
    ws.send(message.toString());
  });
});

console.log(`WebSocket server is running on ws://192.168.20.37:${wsPort}`);
`

Then directing MQTTX Web and connect to ws://192.168.20.37:8090

Thanks.
