### ISSUE TITLE
[Bug] unable to decode JSON in output

### ISSUE THREAD

**Issue by vellanix** [emqx/MQTTX#1418]
The messages are not decoden in JSON on the output window.

#### Environment

- macOS Ventura 13.5.2
- Chrome 116.0.5845.187
- MQTTX Web version 1.9.5

In the screenshot the messages in plaintext (correct), in Base64 (correct), JSON (wrong), Hex (correct).

Same messages in the Mac client are displayd with the corrected JSON format.

<img width="701" alt="Screenshot 2023-09-14 alle 14 43 15" src="https://github.com/emqx/MQTTX/assets/72751032/a62db562-9a24-4241-af6c-01e31a47ee3e">

What's wrong?

Thank you

**Comment by ni00** [comment]
Fixes #1418 . This bug has been addressed in [this pull request](https://github.com/emqx/MQTTX/pull/1419) and will be included in our next release, Version 1.9.6. Thank you for bringing this to our attention.

**Comment by ysfscream** [comment]
Thank you for being so patient!

We have addressed and resolved this issue in the https://github.com/emqx/MQTTX/releases/tag/v1.9.6

It helps us continually improve our product. If you encounter any issues while using the new version, please do not hesitate to let us know.

Thank you once again!
