### ISSUE TITLE
[Bug] tests are not implemented

### ISSUE THREAD

**Issue by Rotzbua** [emqx/MQTTX#1433]
#### What did I do

Run tests.

#### What happened

No tests were run.

#### Expected

Run tests or remove the dependencies.

#### Environment

- OS: kali rolling
- node: 16

**Comment by ysfscream** [comment]
FYI: https://github.com/emqx/MQTTX/pull/1434#pullrequestreview-1645517381

**Comment by ysfscream** [comment]
tests works now.
