### ISSUE TITLE
Need to resize Publish area height myself and use hotkey to send.

### ISSUE THREAD

**Issue by shishirong** [emqx/MQTTX#148]
Need to be able to adjust the height of the send payload input box by yourself. The current height can display too little text. And it seems that it is not possible to send a message using Ctrl + Enter, which is inconvenient.

**Comment by ysfscream** [comment]
@shishirong Hi, I have planned for the next version. Thanks for your suggestion.

**Comment by ysfscream** [comment]
I have optimized it in [v1.3.0](https://github.com/emqx/MQTTX/releases/tag/v1.3.0), thank you for your feedback.
