### ISSUE TITLE
[Bug] Typo in installer

### ISSUE THREAD

**Issue by maggusscheppi** [emqx/MQTTX#1500]
#### What did I do

Installing newest version.

#### What happened

At the end a dialog told me to reload. Text in button sais "Install and Relunch"

#### Expected

Text in button shall be "Intall and Relaunch"
Relunch means "again having lunch"

#### Environment

- OS: Windows 11, Chrome
- MQTTX version, v1.9.6

#### More detail

![image](https://github.com/emqx/MQTTX/assets/74117288/7a840043-6ff8-4384-b883-0e6f36def587)

**Comment by ysfscream** [comment]
Hello @maggusscheppi,

Thank you for pointing out the typo in our installer. We apologize for this oversight, which was a simple but essential mistake 😂. We will address this issue immediately in the upcoming version v1.9.7. I would greatly appreciate your attention to detail.

**Comment by maggusscheppi** [comment]
😂👍🏻👍🏻👍🏻👍🏻MarkusAm 18.11.2023 um 16:59 schrieb YuShifan ***@***.***>:﻿
Hello @maggusscheppi,
Thank you for pointing out the typo in our installer. We apologize for this oversight, which was a simple but essential mistake 😂. We will address this issue immediately in the upcoming version v1.9.7. I would greatly appreciate your attention to detail.
