### ISSUE TITLE
[Feature] collapse "Connections" tab

### ISSUE THREAD

**Issue by ThuanDoHung** [emqx/MQTTX#1511]
Hi,
I use screen with "portrail" mode (1920x1080), when use tab "connections" can not collapse, i feel hard use. 

WANT:
- When connected with server, tab "Connections" close/collapse to left (may be show prefix domain/ip), show larger tab message.
- When hover topic subscribe, it show minipopup, but minipopup cover topic above can not click to topic above --> I want if mouse out topic then popup hidden.

![Screenshot from 2023-12-06 12-02-47](https://github.com/emqx/MQTTX/assets/95118800/654f14ea-70da-4570-ae8f-c719afb05b95)

**Comment by ysfscream** [comment]
@ThuanDoHung Hi. Indeed, this has been a long-requested feature. We have implemented flexible resizing and hiding in version 2.0, but as 2.0 has yet to be ready, I will work on optimizing this issue in the upcoming 1.9.x versions. Thank you for your feedback.

**Comment by ysfscream** [comment]
Waiting for a Long time, and thanks for the feedback. Try the https://github.com/emqx/MQTTX/releases/tag/v1.9.9
