### ISSUE TITLE
[Bug] If the server closes the ws connection, mqttx seems to ignore this event.

### ISSUE THREAD

**Issue by sdghchj** [emqx/MQTTX#1545]
#### What did I do

I used mqttx to connect my mqtt server on websocket connection with mqtt v5.
I published a message with  no topic but a topic alias, as a result, the server cannot recognize it and close the ws connection.

#### What happened

If the server closes the ws connection as a result of a protocol error, mqttx seems to ignore this event, and keep its connecting state.
Then if I clicks the red disconnect button, mqttx blocks.

#### Expected

mqttx receive the close event, and change its state from connecting to disconnecting, like tcp connection.

#### Environment

- OS:  windows 11
- MQTTX version: v1.9.8

**Comment by ysfscream** [comment]
Hi, thanks for your feedback!

I noticed that when using MQTT over WebSocket to connect to EMQX, the connection was closed normally after the server initiated the disconnection. Please specify which MQTT service you are using. This information could help you better understand the context of your issue. 

Additionally, you might want to try using MQTTX CLI with the `--debug` option. This will enable debug logging and could provide more insights into why the connection is not receiving disconnection messages during Ping Check. This detailed information could be crucial in diagnosing the issue you're experiencing.

<img width="963" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/b1e966d2-c5d5-4728-9a2b-8c365c841cf3">

**Comment by sdghchj** [comment]
Yes, my mistake.
