### ISSUE TITLE
[Feature] Pattern subscription show in left window by tree way

### ISSUE THREAD

**Issue by braveletsgo** [emqx/MQTTX#1579]
#### Motivation

I like MQTTX , It's just some my own experience not good. When i subscription with pattern topic, it's not convenient to show wich topic inculde in this subscription when a lot of message arrived.

#### Detailed design
![image](https://github.com/emqx/MQTTX/assets/135848617/17c5dc1e-4d2d-450b-8ad5-894618b1caec)

#### Alternatives

Like this other product:
![image](https://github.com/emqx/MQTTX/assets/135848617/7de202c0-c4e5-4f17-beb6-295fb924aab3)

**Comment by Red-Asuka** [comment]
This seems to duplicate issue #1244. Let's track it there.

**Comment by ysfscream** [comment]
Topic Tree is available at https://github.com/emqx/MQTTX/releases/tag/v1.11.0

This feature is currently in the `Beta` version, and there may be some instabilities or inability to meet expectations. However, I think the basic function of viewing can be achieved.

Therefore, I will close this issue. We can discuss suggestions or bug reports for topic tree **milestone 2** in the issue if there is new feedback or discussion. Thank you all.
