### ISSUE TITLE
[Feature] Add -L (limit) on simulate pub

### ISSUE THREAD

**Issue by golfvert** [emqx/MQTTX#1597]
#### Motivation

Now that bench as the option to set a limit (see https://github.com/emqx/MQTTX/issues/1360) I think it would be really good to also have this for the simulate situation.

At the moment:

```
/app # mqttx simulate -sc weather -c 10 -i 10 -im 500 --limit 100 -t benchmark/test%i
error: unknown option '--limit'

```
#### Detailed design

Having the -L with simulate.

Thanks for the great tool !

**Comment by Red-Asuka** [comment]
Thank you for your valuable suggestion. This only requires some minor adjustments. I will handle it as soon as possible and implement this feature.

**Comment by Red-Asuka** [comment]
@golfvert  We have added the `-L` (limit) option to the `simulate` command. The new version will be released shortly. Please stay tuned.
