### ISSUE TITLE
Adding my own scenario

### ISSUE THREAD

**Issue by golfvert** [emqx/MQTTX#1598]
#### Describe the problem you Confuse

Using mqttx-cli here. Home directory is cli where the source code of mqttx-xli can be found.

From the scenario in src/scenario, I have copied weather.ts to test.ts. I have edited test.ts to change its name and description. 
I understand that throughout the `install` procedure scenario from src/scenario in ts format are "compiled" to js format and copied into dist/src/scenario. In there I can see test.js. So, it seems to be OK.
However, the newly generated mqttx can find this scenario when I run `mqttx ls --scenarios`

When looking into `node_modules/mqttx-cli/dist/src/scenarios/`I can't find my nex test.js scenario.

I guess I am missing a step in adding my scenario in the list of known ones.

When I run `./node_modules/.bin/mqttx simulate -f ./dist/src/scenarios/test.js` is is OK though.

I am confused :) why the test.js is not seen in the list of built-in scenario... 

Is that doable to add my own ?
I intend later to produce a specific docker container embedding my own test scenario...

Thanks for any hints.

**Comment by ysfscream** [comment]
@golfvert Hi. Thanks for your use.

Currently, it's not possible to dynamically add a built-in test scenario at runtime within `mqttx-cli`. We might support this functionality in the future. For the time being, here's the recommended workaround to include your custom test scenario:

1. **Download the source code** and add a TypeScript (.ts) file to the `cli/scenarios` folder, mimicking the format of the existing built-in scenario files.

Then, proceed with either of the following steps based on your needs:

2. **For local development and packaging**:
   - Ensure Node.js and Yarn are installed.
   - Run `yarn build` in the project root to compile TypeScript files.
   - If needed, install the `pkg` package and use `pkg .` to generate an executable binary found in the release folder.

Or,

3. **For Docker deployment**:
   - Run `docker build -t mqttx-cli .` to create a Docker image with your custom scenario, and run `docker run -it mqttx-cli`
   
<img width="358" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/ffb19da5-9068-4953-80cd-91460327311a">

<img width="903" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/0bfe712f-fd57-44a5-be7d-dadfb8c70155">

**Comment by golfvert** [comment]
Hi,
Thank you for your answer. By looking into the code, I saw that it wasn't dynamic.
However, even after done the `yarn build` I can't find the new scenario. Do I need to package it ?
At runtime, which directory is used to find the scenario ? 
I can't see it in `node_modules/mqttx-cli/dist/src/scenarios/`
Not sure why, though...

**Comment by ysfscream** [comment]
Hi,

It's best not to modify anything directly in `node_modules/mqttx-cli. Instead, please follow these steps:

1. **Clone the `MQTTX` repo** and make changes in the cloned directory, not in `node_modules`.
2. **Add your scenario** in the `cli/scenarios` folder.
3. **Build** the project with `yarn build` or `npm run build` in the root directory of your cloned project.

This approach ensures your changes are saved and tracked correctly.

**Comment by golfvert** [comment]
This is what I have done... I have added my new scenario in my cloned directory is cli/src/scenario. I run `yarn build`. All seems to be fine:

``` 
laptop-2:cli me$ ls -l src/scenarios/
total 40
-rwxr-xr-x@ 1 me  staff  2195 Feb 29 03:53 IEM.ts
-rwxr-xr-x@ 1 me  staff  2620 Feb 29 03:53 smart_home.ts
-rwxr-xr-x@ 1 me  staff  3921 Feb 29 03:53 tesla.ts
-rwxr-xr-x@ 1 me  staff  3805 Feb 29 03:53 weather.ts
-rwxr-xr-x@ 1 me  staff  1068 Mar  3 19:49 test.ts
laptop-2:cli me$ touch src/scenarios/test.ts
laptop-2:cli me$ yarn build
yarn run v1.22.21
$ tsc
✨  Done in 2.12s.
laptop-2:cli me$ ls-l dist/src/scenarios/
-bash: ls-l: command not found
laptop-2:cli me$ ls -l dist/src/scenarios/
total 56
-rw-r--r--  1 me  staff  2944 Mar  3 15:18 IEM.js
-rw-r--r--  1 me  staff  2839 Mar  3 15:18 smart_home.js
-rw-r--r--  1 me  staff  4424 Mar  3 15:18 tesla.js
-rw-r--r--  1 me  staff  4788 Mar  3 15:18 weather.js
-rw-r--r--  1 me  staff  1762 Mar  3 19:49 test.js
laptop-2:cli me$ ./node_modules/.bin/mqttx ls --scenarios
You can use any of the above scenario names as a parameter to run the scenario.
┌───────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┐
│ Scenario Name │ Description                                                                                  │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ IEM           │ Simulation to generate Industrial Energy Monitoring data.                                    │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ smart_home    │ Simulation to generate Smart Home data.                                                      │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ tesla         │ Simulation to generate Tesla's data, reference form https://github.com/adriankumpf/teslamate │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ weather       │ Simulation to generate advanced weather station's data.                                      │
└───────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┘
laptop-2:cli me$
```

**Comment by ysfscream** [comment]
To run the `./node_modules/.bin/mqttx ls --scenarios` command, make sure to first run `yarn dev` in the development environment.

**Comment by golfvert** [comment]
I am totally ignorant on yarn... Sorry.

yarn dev gives me this: 

```
[11:06:15 AM] Starting compilation in watch mode...

[11:06:16 AM] Found 0 errors. Watching for file changes.
```
And done.

This is my lack of knowledge on yarn that present this to work, I guess...

**Comment by golfvert** [comment]
And running
```
laptop-2:cli remy$ pkg .
> pkg@5.8.1
> Warning Failed to make bytecode node16-x64 for file /snapshot/cli/node_modules/axios/index.js
> Warning Failed to make bytecode node16-x64 for file /snapshot/cli/node_modules/axios/lib/axios.js
> Warning Failed to make bytecode node16-x64 for file /snapshot/cli/node_modules/axios/lib/utils.js
> Warning Failed to make bytecode node16-x64 for file /snapshot/cli/node_modules/axios/lib/helpers/bind.js
...
```

which is apparently a known bug... https://github.com/axios/axios/issues/5650

:(

**Comment by golfvert** [comment]
Docker build works though:

```
docker run -it mqttx-cli
/app # mqttx ls --scenarios
You can use any of the above scenario names as a parameter to run the scenario.
┌───────────────┬──────────────────────────────────────────────────────────────────────────────────────────────┐
│ Scenario Name │ Description                                                                                  │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ IEM           │ Simulation to generate Industrial Energy Monitoring data.                                    │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ smart_home    │ Simulation to generate Smart Home data.                                                      │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ tesla         │ Simulation to generate Tesla's data, reference form https://github.com/adriankumpf/teslamate │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ weather       │ Simulation to generate advanced weather station's data.                                      │
├───────────────┼──────────────────────────────────────────────────────────────────────────────────────────────┤
│ test     │ test                                          │
└───────────────┴──────────────────────────────────────────────────────────────────────────────────────────────┘
/app #

```

**Comment by ysfscream** [comment]
Great to see you've successfully run your custom scenario in Docker!

You need to run `yarn dev` to initiate the development environment for local development. Afterward, you should use the command from the project's root directory, like `node ./bin/index.js conn -h broker.emqx.io`, instead of using anything from `node_modules`. This ensures your custom scenario is correctly recognized and executed. Hope this helps solve your issue!

**Comment by golfvert** [comment]
Thanks for the good advices. Super helpful.
Any comment on the `pkg .` issue above ?

**Comment by ysfscream** [comment]
I have no idea about this, but I can share my versions about Node.js and pkg.

```shell
pkg -v
5.8.1

node -v
v16.14.2
```

Hope helpful to you.

**Comment by golfvert** [comment]
Running same pkg version (5.8.1) but node 20.11.1.
Anyway, not related to this great tool. So, I'll close this.
Thanks for great help. Much appreciated.

**Comment by golfvert** [comment]
My questions were answered :)

**Comment by ysfscream** [comment]
Thanks for using it. I will colse this issue.
