### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by salmankhalid-plt** [emqx/MQTTX#1620]
#### What did I do

Something you have done.

#### What happened

Get an error.

#### Expected

What is the expected result.

#### Environment

- OS: OS version, e.g. macOS Big Sur 11.1
- MQTTX version, e.g. v1.5.0

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Thank you for reaching out. Unfortunately, the issue description is too vague to pinpoint the problem. I recommend upgrading from MQTTX version 1.5.0 to the latest version as a first step.

If the issue persists, please provide more detailed information, including steps to reproduce the error, the exact error message, and any relevant configurations. This will help us better understand and address your issue.
