### ISSUE TITLE
large TEXT as a publish starts to not obey a new line

### ISSUE THREAD

**Issue by riwalker** [emqx/MQTTX#1623]
#### What did I do

try and publish large data, using '/' as a new line
		esp_mqtt_client_publish(mqtt_client, "/menu/dmx",
				"1 - UDP -  Send DMX frame\
				2 - UDP -  Send DMX RAMP 4 colors\
				3 - UMAC - Send DMX frame\
				4 - UMAC - Send DMX RAMP 4 colors - 5B\
				5 - UMAC - Send DMX RAMP 4 colors - 400B\
				6 - UMAC - Send BLANK all LED\
				7 - Reset STATs\
				8 - Get STATs\
				a - Set Default PLC Setup\
				b - Set PLC Modulation type\
				c - Set Min/Max Intra-Frame Time\
				d - Discover Nodes\
				n - Send message to node x\
				u - Unicast - Multicast Address\
				v - START Unicast sACN Transmit\
				w - STOP unicast sACN Transmit\
				x - START Multicast sACN Receive\
				y - STOP Multicast sACN Receive", 0, 0, 0);

#### What happened

see here (it works for the first 6 lines, then 7 & 8 go crazy, then it works again !?
![image](https://github.com/emqx/MQTTX/assets/5286390/60f111c6-4aef-47ae-b04d-39cb4a2ae86e)

#### Expected

all lines should align

#### Environment

- OS: WIn11
- MQTTX version 1.9.10

**Comment by riwalker** [comment]
Im sending as rawtext

The / symbol is supposed to be a new line

 

So in MQTT, any format here ?

I just moved the page separator, and it gets worse

**Comment by ysfscream** [comment]
1. MQTT supports any data format, including UTF-8 text and binary data.
2. Using "/" as a separator is not a standard practice.
3. When MQTTX receives data and converts it to plaintext, it interprets it using UTF-8 encoding for standard text parsing.

**Comment by ysfscream** [comment]
If there is no update, I will close this issue; thanks for using it.
