### ISSUE TITLE
[Bug] Some subscription filters not showing published messages

### ISSUE THREAD

**Issue by archenovalis** [emqx/MQTTX#1637]
#### What did I do

Created subscriptions:
tele/tasmota_84F633/SENSOR
tele/tasmota_84F633/#
tele/#

#### What happened

Topic (tele/tasmota_84F633/SENSOR) messages appear in tele/# and when no subscriptions are selected

Topic (tele/tasmota_84F633/SENSOR) messages do not appear in:
tele/tasmota_84F633/SENSOR
tele/tasmota_84F633/#

#### Expected

Topic (tele/tasmota_84F633/SENSOR) messages should appear in:
tele/tasmota_84F633/SENSOR
tele/tasmota_84F633/#
tele/#

#### Environment

- OS: Windows 10
- MQTTX version: x86-64 v1.9.10 (v1.9.10.win64.exe)

#### More detail

![image](https://github.com/emqx/MQTTX/assets/141416512/4fa7d4aa-cdd1-4884-8951-1d306dce6961)

**Comment by ysfscream** [comment]
It's updated to https://github.com/emqx/MQTTX/releases/tag/v1.10.0, thanks again.
