### ISSUE TITLE
MQTTX Connection Issues with RabbitMQ MQTT

### ISSUE THREAD

**Issue by NullWan** [emqx/MQTTX#1646]
RabbitMQ Version: RabbitMQ 3.13.2
RabbitMQ MQTT Plugin Enabled
![image](https://github.com/emqx/MQTTX/assets/77950108/28d376a6-16cc-4a43-8c40-1e47d16870f5)
The IP and port are reachable, but there's an error when connecting to the RabbitMQ server using the mqtt:// protocol.
![image](https://github.com/emqx/MQTTX/assets/77950108/7e7849b7-03f6-4a63-b6fb-8787cbb9fb6d)
There's also an error when using the ws:// protocol to connect to the RabbitMQ server, despite the IP and port being reachable.
![image](https://github.com/emqx/MQTTX/assets/77950108/2e78fa85-c704-4091-8e76-ccc436738376)

**Comment by ysfscream** [comment]
Hello @NullWan 

I couldn't reproduce the issue you mentioned. I successfully enabled the MQTT plugin on RabbitMQ and connected both through MQTTX CLI and Desktop without any problems.

<img width="618" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/6f957ee0-f53b-415f-8383-bb0a6b5db4f0">

<img width="1357" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/a2ee3db6-99e7-4516-8fae-0d395e52b1ff">

<img width="1137" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/7fda3fe6-3631-4bf3-aff5-3462cd07c6bb">

From the error messages you've shared, the issue might be related to the mqtt_v5 plugin not being enabled on your RabbitMQ server. Alternatively, try changing the MQTT version in MQTTX to 3.1.1 and see if that resolves the issue.

Additionally, you might find this official RabbitMQ blog post helpful for more insights: https://www.rabbitmq.com/blog/2023/07/21/mqtt5

Thanks f.or using it. Please let me know if this helps or if you need further assistance.

**Comment by NullWan** [comment]
感谢回复并帮助我解决了困惑，MQTT版本切换成3.1后正常连接，再次感谢
![image](https://github.com/emqx/MQTTX/assets/77950108/6981f5ba-eb8c-4fe1-922f-7ef1c820e32d)
