### ISSUE TITLE
[Bug] Subscription Rejection Causes Subsequent Channels to Fail 

### ISSUE THREAD

**Issue by TheRiseOfDavid** [emqx/MQTTX#1690]
#### What did I do
I have ten channels. If the 5th channel rejects my subscription, other channels below the 5th channel cannot resubscribe.

#### What happened
When I restart MQTTX, connect to the broker, and resubscribe to the channels, if a specific channel rejects the subscription, the channels below the specified channel cannot resubscribe.

#### Expected
Other channels should be able to resubscribe even if a specific channel rejects my subscription.
And I appreciate to fix or solve this issue.

#### Environment

- OS: Sonoma 14.5 
- MQTTX version: v1.9.10

#### More detail
- The channel order is: chat/mika, auth/mika
- Line 851 is my operator to remove the channel. 
<img width="1316" alt="截圖 2024-06-12 上午11 44 26" src="https://github.com/emqx/MQTTX/assets/26361055/6574cdb7-662a-4c36-b7ec-bc667dcbf600">

- The channel order is: auth/mika, chat/mika
<img width="1346" alt="截圖 2024-06-12 上午11 45 41" src="https://github.com/emqx/MQTTX/assets/26361055/9c7ed164-52a7-485d-b1d5-24d699418f6c">

**Comment by ysfscream** [comment]
@TheRiseOfDavid Thanks for your feedback. We have fixed this issue and will release it in the next version.

**Comment by TheRiseOfDavid** [comment]
@ysfscream You're welcome! I'm glad I could help.

**Comment by ysfscream** [comment]
The issue has been fixed in https://github.com/emqx/MQTTX/releases/tag/v1.10.1. Please update and use it. Thank you.
