### ISSUE TITLE
MQTTX-CLI: timestamps, topics and qos values not readable 

### ISSUE THREAD

**Issue by svanharmelen** [emqx/MQTTX#1699]
#### What did I do

Use mqttx-cli to connect and test with an MQTT server (tried to see if I could somehow configure the ouput colors, but couldn't find a way to do so).

#### What happened

I cannot read the timestamps, topics and qos values due to the color they are printed in.

#### Expected

That I would be able to read the timestamps, topics and qos values on a dark CLI background.

#### Environment

- OS: macOS 14.5
- MQTTX-CLI: v1.10.0

#### More detail

As you can see with the highlighted part (in yellow) the values are there, just not readable:
<img width="1111" alt="image" src="https://github.com/emqx/MQTTX/assets/4171547/6db5242c-99c3-4ed0-b781-b4af382775e6">

**Comment by ysfscream** [comment]
Yes, I apologize for not testing on terminals with different color configurations. I didn’t encounter this display issue during development with my default terminal theme. However, I was able to reproduce the problem with various themes. We will fix this in the next version. Thank you for your feedback.

<img width="1354" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/11f2fbc4-13b7-4351-9406-c588f8d14baf">

**Comment by svanharmelen** [comment]
Thanks for the feedback! I'll keep an eye out for the upcomming version(s) 👍🏻

**Comment by ysfscream** [comment]
The issue has been fixed in https://github.com/emqx/MQTTX/releases/tag/v1.10.1. Please update and use it. Thank you.

**Comment by svanharmelen** [comment]
Works like a charm, thanks!
