### ISSUE TITLE
[Feature] Support custom http headers for websocket connections

### ISSUE THREAD

**Issue by msalajka** [emqx/MQTTX#1722]
#### Motivation

Authentication: Custom headers can include authentication tokens (e.g., JWTs, API keys) that are necessary to authenticate users or devices before establishing a connection.

Custom Protocols: In some use cases, clients and servers might follow proprietary or custom protocols that require specific headers to establish a connection or negotiate terms (for example vmware cloud director requires to set header Sec-WebSocket-Protocol to mqtt to establish a WebSocket connection).

**Comment by ysfscream** [comment]
This is a good suggestion. We will consider whether we can support it. Thank you!

**Comment by ysfscream** [comment]
Updated on https://github.com/emqx/MQTTX/releases/tag/v1.11.0

However, it should be noted that we can only support it in CLI. Use `mqttx sub -t test -wh "hello: test" -wh "auth: token" -l ws -p 8083`. 

Due to browser security restrictions, we cannot implement this function for Desktop and Web.
