### ISSUE TITLE
The connection name cannot be adjusted

### ISSUE THREAD

**Issue by engine100** [emqx/MQTTX#1723]
#### What did I do

create a connection , the name is long

#### What happened

The connection name on the left is not fully displayed and cannot be adjusted

macos  : 14.2.1 
emqx: Version: v1.10.1

**Comment by ysfscream** [comment]
Thanks for your feedback. We will fix it in the next version.

**Comment by ysfscream** [comment]
Updated on https://github.com/emqx/MQTTX/releases/tag/v1.11.0, thanks!
