### ISSUE TITLE
Version 1.10.1 cannot find the timed message button

### ISSUE THREAD

**Issue by xmsgd123** [emqx/MQTTX#1725]
#### What did I do

Something you have done.

#### What happened

Get an error.

#### Expected

What is the expected result.

#### Environment

- OS: OS version, e.g. macOS Big Sur 11.1
- MQTTX version, e.g. v1.5.0

#### More detail

More detail include `log` information or screenshot

**Comment by Red-Asuka** [comment]
Timed Message feature has been moved to the bottom right corner.
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/40799c7a-0043-4b54-abb8-ba8c3c082090">

**Comment by xmsgd123** [comment]
thank you
