### ISSUE TITLE
[Help] The client connot reveive server message

### ISSUE THREAD

**Issue by dfengpo** [emqx/MQTTX#1728]
I use mqttnet lib ,and build a mqtt server by mqttnet.
I use MqttServer.InjectApplicationMessage(...) to a topic subscribed to by the MqttClient.
but the mqttx client connot receive the server message.

**Comment by ysfscream** [comment]
Thank you for your inquiry. But to help diagnose the problem, could you please provide:

1. Confirmation that the MQTTX client is successfully connecting to your server
2. Verification that the client is subscribed to the correct topic
3. Any error messages from the server when injecting messages
4. A minimal code sample of your server setup and message injection

For MQTTnet-specific issues, you may also want to consult their community resources. If you can provide more details, we'll try to assist further or direct you to appropriate resources.

**Comment by ysfscream** [comment]
if no any updates. i will close this issue. thanks for using it.
