### ISSUE TITLE
MQTT  ports besides 1883 or 8883 in MQTTx client

### ISSUE THREAD

**Issue by Zeni241** [emqx/MQTTX#1732]
Hi 
While configuring a mqtt Un-encrypted connection, if I enter any port other than 1883, I get the error "Unknown property". Same with encrypted connecting setting with any port other than 8883.
Question is how to choose any port besides 1883 and 8883?
Thanks

**Comment by ysfscream** [comment]
Hi! Thank you for your report. The "Unknown property" error is likely due to a mismatch between MQTTX's MQTT version (default 5.0) and your MQTT Broker's supported version.

To resolve:

1. Check if your broker supports MQTT 5.0
2. Try switching to MQTT 3.1.1 in MQTTX connection settings
3. Ensure your broker configuration matches the MQTT version you're using

**Comment by Zeni241** [comment]
Hi
Thanks for response. I checked my mosquitto version and it supports mqtt v5.0.

> mosquitto version 2.0.15
> 
> mosquitto is an MQTT v5.0/v3.1.1/v3.1 broker.

MQTTx client has jno problem if the ports are 1883 or 8883.

**Comment by ysfscream** [comment]
Ah, I apologize for misunderstanding your question. You're asking how to modify custom ports, right? This isn't something you can do within MQTTX itself; it depends on your MQTT Broker configuration.

I'm not very familiar with this process, but it's typically done through the broker's configuration file. You might want to Google or check the Mosquitto documentation for specific instructions.

But if you are using EMQX, you would just need to modify the listener settings. Perhaps you could try that approach. Thanks.

**Comment by Zeni241** [comment]
I have set mosquitto broker on AWS EC2. Its just MQTTx not allowing any port other than 1883 or 8883 (for example 8880 or 2083).

**Comment by ysfscream** [comment]
MQTTX can change any ports. It will never limit this things..

<img width="686" alt="image" src="https://github.com/user-attachments/assets/7ddf52ea-4d5a-4a3a-9e5b-081d06aa6966">
