### ISSUE TITLE
[Bug] topic subscription merges foo/# with foobar/#

### ISSUE THREAD

**Issue by pinchy** [emqx/MQTTX#1734]
#### What did I do

Created a topic subscription in the format `tray/#` in order to subscribe to messages in the format `tray/abcd1234/state` `tray/12cbac123/ping` etc.  

Note we have a seperate subscriptions setup for `traybot/#`

#### What happened

Messages of the format `traybot/#` are also being subscribed to

#### Expected

Expected result would be that `traybot/#` messages are ignored as they do not conform to the pattern `tray/#` ~it appears that the trailing `/` character is being ignored and that the subscription is instead `tray#` which is unexpected behaviour.~ (edit, see comment below)

#### Environment

- OS: OS version, e.g. macOS Big Sur 11.1
- MQTTX version, e.g. v1.5.0

#### More detail

Screenshot showing subscription and also one correct and one incorrect message.  (Please note that the payloads, redacted as I don't have approval to share, do not contain the words "tray" anywhere)
![Screenshot 2024-08-16 at 3 11 15 PM](https://github.com/user-attachments/assets/897ef8ab-5bb9-4dd4-975f-8c97723fddd2)
![Screenshot 2024-08-16 at 3 10 31 PM](https://github.com/user-attachments/assets/a56a4a73-4fd8-47bb-a5f1-349a861b7065)

**Comment by pinchy** [comment]
I deleted the subscription to `traybot/#` and the offending messages were not shown in the `tray/#` subscription.  I recreated the `traybot/#` subscription and messages sent to the topic `traybot/#` were again shown in the `tray/#` subscription.  

So it looks like that they're being "merged" somehow.

**Comment by pinchy** [comment]
Yep confirmed.

can easily recreate the bug.

1.  create topic `foo/#`
2. send message to `foo/1/test` and it subscribes correctly
3. send message to `foobar/1/test` and it does not show (correct behaviour)

1. create seperate topic `foobar/#`
2. click on `foo/#` topic window
3. send message to `foobar/1/test` and message now shows in `foo/#` window

![Screenshot 2024-08-16 at 3 17 23 PM](https://github.com/user-attachments/assets/43560dd6-971a-4ed4-8e95-daf077b953ac)

**Comment by ysfscream** [comment]
Hi, sorry for my late reply. Thanks for your response, but I cannot reproduce your issue:

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/5ddb42ba-5c16-4e5f-b509-00e44e5f854a">

And I noticed your MQTTX version is **outdated**. Please upgrade to the latest version (https://mqttx.app/downloads) to use.

**Comment by pinchy** [comment]
(Just want to say first that we love the product!)
Version updated. Was able to recreate on a new subscription to a new local mosquitto server instance (running on my computer).  I've screenshotted each step.
![0  version](https://github.com/user-attachments/assets/bb457cf2-f2b1-4d7b-bb96-27b
![1  single subscription foo message](https://github.com/user-attachments/assets/1a06546d-0b75-4d63-8099-0c43bc37b7cd)
2bcab0d75)
![2  single subscription foobar message](https://github.com/user-attachments/assets/f4f9e0ba-2041-4c6b-be74-46c7fa64e02c)
![3  double subscription foo message](https://github.com/user-attachments/assets/6f86b47f-646b-486a-902d-1f51a988c0e3)
![4  double subscription foobar message](https://github.com/user-attachments/assets/2111b842-1ffb-42ce-890a-0ce314e0789f)


macOS `14.6.1`
mosquito version `2.0.18`
using mqtt version `3.1`

**Comment by pinchy** [comment]
> Hi, sorry for my late reply. Thanks for your response, but I cannot reproduce your issue:
> 
> <img alt="image" width="1093" src="https://private-user-images.githubusercontent.com/21299158/359135745-5ddb42ba-5c16-4e5f-b509-00e44e5f854a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDYwMDIsIm5iZiI6MTcyNDEwNTcwMiwicGF0aCI6Ii8yMTI5OTE1OC8zNTkxMzU3NDUtNWRkYjQyYmEtNWMxNi00ZTVmLWI1MDktMDBlNDRlNWY4NTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIyMTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMDhkNzk4ODJkNzRlOTliNThkY2YxZjA1NGVmNDMzNWM2YWZkNjNlZGM3NTc1Y2VlNDQyODU1YjhlYzVmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3hU90fWsBwAuXlB4W2IUvqEh_HoPpHXmv0VVSZpV4v4">
> And I noticed your MQTTX version is **outdated**. Please upgrade to the latest version (https://mqttx.app/downloads) to use.

Looks like you did recreate it... you've got the "tray/#" subscription selected in the subscription list, so you should only be seeing "tray/#" messages in the message stream.  However the "traybot/3/state" message appeared erroneously.
<img width="1093" alt="359135745-5ddb42ba-5c16-4e5f-b509-00e44e5f854a" src="https://github.com/user-attachments/assets/6b7cd1e3-1c80-4b8f-8435-3aecb70933b0">

**Comment by ysfscream** [comment]
> (Just want to say first that we love the product!)

Thanks so much! 💛

I'm sorry, I misunderstood this issue. I reproduced it, and it's caused by the filter function on the search method for the database. It's a BUG, and we will fix it in the next version. Thanks.

**Comment by pinchy** [comment]
Happy days!

**Comment by ysfscream** [comment]
Updated on https://github.com/emqx/MQTTX/releases/tag/v1.11.0. Thanks for your feedback.
