### ISSUE TITLE
[Help] Problem with MQTTX commands on Terminal Linux

### ISSUE THREAD

**Issue by Snak3in** [emqx/MQTTX#1737]
Hi, I just started using MQTTX so I'm not very experienced and I need some help.
I use HiveMQ as a broker and I can make the connection using the first command on the terminal "MQTTX conn" which gives me the response on the screen "Connected", however once the connection is made if I want to subscribe to a topic I send the command "mqttx sub -- protocol 'mqtts' -h '?' -p 8883 -t 'hello' " and it seems like it doesn't see it as a command, it doesn't give me a response.
Probably the command has never been started in the terminal and pressing enter simply makes me go back to write more text

**Comment by Snak3in** [comment]
Ok thanks, it works now but the problem remains that after I subscribe to a topic, for example if I want to subscribe to another topic it doesn't let me send commands, what can I do?

**Comment by Red-Asuka** [comment]
You can subscribe to multiple topics at once, like this:

```bash
mqttx sub -t t1 t2

# or

mqttx sub -t t1 -t t2
```

**Comment by Snak3in** [comment]
okay thank you very much for the help I have no further questions for now
