### ISSUE TITLE
[Feature] Replace gpt-3.5-turbo with gpt-4o mini

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [emqx/MQTTX#1763]
#### Motivation
OpenAI is deprecating the `gpt-3.5-turbo` model with the introduction of `gpt-4o-mini`, which is 60% cheaper and better in performance across various benchmarks.

Detailed Design
According to their [blogpost](https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/), `GPT-4o mini` surpasses `GPT-3.5 Turbo` in both textual and multimodal reasoning, supports the same languages as GPT-4o, and improves function calling and long-context handling (128K context window vs. 4K in GPT-3.5 Turbo).

There’s no reason to continue using gpt-3.5-turbo as it is more expensive and less capable.

**Comment by ysfscream** [comment]
Good suggestion, thanks.

**Comment by ysfscream** [comment]
Updated on https://github.com/emqx/MQTTX/releases/tag/v1.11.0; I will close the issue. Thanks for the feedback.
