### ISSUE TITLE
[Bug] data is lost when receiving data.

### ISSUE THREAD

**Issue by johnzhy** [emqx/MQTTX#1770]
#### What did I do

同时订阅2个主题，设备每次连续发布这两个主题的数据，mqttx接收并显示这两个主题的消息

#### What happened

结果会出现只接收到一条主题数据的情况。
mqtt服务器记录的两个主题数据条数一致，设备端显示所有主题发布成功，更换
mqtt.fx后，不再出现丢失数据的情况。
#### Expected

接收所有数据

#### Environment

- OS: Windows 11 23H2
- MQTTX version, e.g. v1.10.1

**Comment by ysfscream** [comment]
Hi there! Sorry for replying so late. I will reproduce this issue again. I am publishing different topics with 100 messages per topic and QoS 0. The broker is deployed in my cloud environment. MQTTX will receive a total of 200 messages from different topics. However, I still can't reproduce this issue. Could you please provide more detailed information about this bug? Thanks! 

<img width="765" alt="image" src="https://github.com/user-attachments/assets/50fcd883-1e64-4e5b-b0c9-5ca4802d500e">
<img width="754" alt="image" src="https://github.com/user-attachments/assets/a692ee2d-fde1-46d6-8406-9e930245d082">
<img width="489" alt="image" src="https://github.com/user-attachments/assets/53463746-460e-41ae-8f1b-90a40b5d4752">

**Comment by mobiusy** [comment]
Same issue, reproduce steps:
1. Subscribe two wildcards topic
![image](https://github.com/user-attachments/assets/6d7e10c1-f146-4c00-9376-659d9beeb38b)
![image](https://github.com/user-attachments/assets/9019131e-d587-4687-a22c-542300f9861c)
2. Send about 10 messages to one of the topics， e.g. wdp5-backend/+/delete-user-model-task-status/+
The first 5 messages are sent to "wdp5-backend/Team_13336_3a34b5/user-model-task-status/1a7c79c37f4845e3b3ef0e3c9d48acf6".
The latter 5 messages are sent to "wdp5-backend/Team_13336_3a34b5/user-model-task-status/afe469aa4a2d4a0a9c4e9e2bd10349a2".
 4. Message not fully displayed in the message box, only first 6 messages displayed
![image](https://github.com/user-attachments/assets/7639c470-1c02-4563-87e0-d9714aaa050a)
 6. Switch the tab to the left, the rest messages appeared
 
![image](https://github.com/user-attachments/assets/77ac644f-eda4-48c4-ad49-3250920e89ca)

So, I guess all the messages are received, but some of them are not displayed in the message box.

**Comment by ysfscream** [comment]
Hi! Thanks for the detailed reproduction steps. I've tried to reproduce this issue but haven't been successful. 

Could you provide a more detailed way to consistently reproduce this? For example:
- Message payload
- Publishing frequency
- QoS level
- Any specific broker settings

Also, I'd like to understand what's happening in MQTTX when the messages are not rendered. Could you try enabling debug logs when reproducing this issue? This would help us track down where exactly the rendering is failing.

Let me know if you can provide any additional details. Thanks for helping improve MQTTX!

**Comment by mobiusy** [comment]
> Hi! Thanks for the detailed reproduction steps. I've tried to reproduce this issue but haven't been successful.
> 
> Could you provide a more detailed way to consistently reproduce this? For example:
> 
> * Message payload
> * Publishing frequency
> * QoS level
> * Any specific broker settings
> 
> Also, I'd like to understand what's happening in MQTTX when the messages are not rendered. Could you try enabling debug logs when reproducing this issue? This would help us track down where exactly the rendering is failing.
> 
> Let me know if you can provide any additional details. Thanks for helping improve MQTTX!

OK, thanks for your reply, I will address more details:
1. Add MQTTX Connection
![image](https://github.com/user-attachments/assets/07e3be5e-dbb9-42a5-a65e-9a5a75ff0521)
2. Subscribe two wildcard topics:
![image](https://github.com/user-attachments/assets/e1459029-845a-4136-a45b-5538d7fc768b)
![image](https://github.com/user-attachments/assets/87ec017b-9fa5-427d-86c4-56eedf42a509)

3. In another mqtt client, connect the same emqx server
![image](https://github.com/user-attachments/assets/96f7dafb-ece8-447d-80a2-39b94549114d)
4. Send 6 messages to `wdp5-backend/100/delete-user-model-task-status/001` concurrently
5. Send 6 messages to `wdp5-backend/100/delete-user-model-v2-task-status/001` concurrently
Message  body of step 4 & 5:
```json
{
    "allModels": [
        {
            "folderId": "",
            "models": [
                "a5e192aa298ce6d64c21eaedb9918c79",
                "0bc53f7cbf781d9534da503bf81919a2",
                "ff213cf4cdb71ff46a9b1ce41e7b18df",
                "826be5644e29c33aa5fdb06c7c6f7092"
            ]
        },
        {
            "folderId": "54b3b49a3d775b914d18ecd9c8860d77",
            "models": [
                "ae511be1d40d88f0243030fe92a82880",
                "4378273065bf4a13846d465ba3242c57"
            ]
        },
        {
            "folderId": "44b3b49a3d775b914d18ecd9c8860d78",
            "models": [
                "459e09c285ec4a1d55a1d256625b70a7",
                "ec030638eebd2536e7f1bc701810caf8"
            ]
        }
    ],
    "modelProcessDetail": {
        "processed": [
            "a5e192aa298ce6d64c21eaedb9918c79",
            "0bc53f7cbf781d9534da503bf81919a2",
            "ff213cf4cdb71ff46a9b1ce41e7b18df",
            "826be5644e29c33aa5fdb06c7c6f7092",
            "ae511be1d40d88f0243030fe92a82880",
            "4378273065bf4a13846d465ba3242c57",
            "459e09c285ec4a1d55a1d256625b70a7",
            "ec030638eebd2536e7f1bc701810caf8"
        ],
        "deleted": [
            "a5e192aa298ce6d64c21eaedb9918c79",
            "0bc53f7cbf781d9534da503bf81919a2",
            "ff213cf4cdb71ff46a9b1ce41e7b18df",
            "826be5644e29c33aa5fdb06c7c6f7092",
            "ae511be1d40d88f0243030fe92a82880",
            "459e09c285ec4a1d55a1d256625b70a7",
            "ec030638eebd2536e7f1bc701810caf8"
        ]
    },
    "folderProcessDetail": {
        "processed": [
            "54b3b49a3d775b914d18ecd9c8860d77",
            "44b3b49a3d775b914d18ecd9c8860d78"
        ],
        "deleted": ["44b3b49a3d775b914d18ecd9c8860d78"]
    },
    "cannotDeleteModels": [
        {
            "seedId": "4378273065bf4a13846d465ba3242c57",
            "container": ["container A"],
            "case": ["Case A"]
        }
    ],
    "cannotDeleteFolders": ["54b3b49a3d775b914d18ecd9c8860d77"]
}

```
![image](https://github.com/user-attachments/assets/061c3168-d14e-482a-a669-0f36febddcf1)
6. MQTTX client shows 12 messages received, but 7 messages displayed in the message box
![image](https://github.com/user-attachments/assets/b6c6bc16-055d-4546-8a2a-cc1ae76f4843)

Please see the video:
https://github.com/user-attachments/assets/f1a5ad75-2233-45fc-902f-859defd6504f

7. debug log
[mqttx_12_10.log](https://github.com/user-attachments/files/18070842/mqttx_12_10.log)

Supplementary explanation：
1. Publishing messages slowly will not trigger this issue
2. I do more research. Only one subscription can also have this issue as soon as messages received instantaneous

**Comment by ysfscream** [comment]
Thank you all, it should have been fixed https://github.com/emqx/MQTTX/releases/tag/v1.11.1, if there are new problems I will reopen this issue.
