### ISSUE TITLE
[Help] BAD_DECRYPT. How to add pass phrase in MQTT app?

### ISSUE THREAD

**Issue by letruonglamit** [emqx/MQTTX#1781]
#### How to add pass phrase in MQTTX app?

When I try to connect to my server by MQTTX, I got this error:
Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
![Screen Shot 2024-10-23 at 12 39 06](https://github.com/user-attachments/assets/1110f66d-fb02-4ece-8af3-5a193099e833)

I am thinking that I am using pass phrase for certs and I missed it. Because when I try to connect by mosquitto_pub, I need to enter pass phrase to make it work

How to I can add them in MQTTX app? Here is my configs
![Screen Shot 2024-10-23 at 12 42 58](https://github.com/user-attachments/assets/45588a7a-3271-4102-907d-1b2a1efabaf6)

**Comment by letruonglamit** [comment]
I want to close it. The solution that I need to convert client.key to a new key without pass phrase:
`openssl rsa -in client.key -out client-without-pass-phrase.key`

**Comment by ysfscream** [comment]
@letruonglamit glad to see you have found the solutions.
