### ISSUE TITLE
[Bug] Open MQTTX white screen

### ISSUE THREAD

**Issue by qq510768394** [emqx/MQTTX#1792]
#### What did I do

My computer installed MQTTX for the first time, but it turned on a white screen
![image](https://github.com/user-attachments/assets/ba4ad888-dc44-49f5-a968-9b01344f7a86)

#### What happened

I tried running as an administrator,
I tried uninstalling and installing a higher version
I tried to delete it    "C:\Users\{my_name}\AppData\Roaming\MQTTX\MQTTX.db" 
But none of them had any effect

#### Expected

Can open and use MQTTX normally

#### Environment

- OS: Windows 11 专业版 23H2
- MQTTX 1.09.x-x64.exe/1.10.x-x64.exe/1.11.0-x64.exe

#### More detail

![image](https://github.com/user-attachments/assets/ba4ad888-dc44-49f5-a968-9b01344f7a86)
I suspect it may be related to my local name being Chinese and containing Chinese symbols,
my local name is "中文。"

**Comment by ysfscream** [comment]
This issue looks quite strange. I wasn't able to reproduce it on Windows, and it seems you have already tried the previously suggested methods. Please check for any log files in the directory `C:\Users\{my_name}\AppData\Roaming\MQTTX\logs`, as shown in the screenshot below. If there are any, please share the contents with me.

<img width="679" alt="image" src="https://github.com/user-attachments/assets/de412972-9daf-4d2b-95f7-992f9768f5d8">

**Comment by qq510768394** [comment]
Thank you for your reply 
There is only one file named MQTTX.db （0kb）in the directory of "C:\Users\中文。\AppData\Roaming\MQTTX", and there are no other files

**Comment by qq510768394** [comment]
I seem to have found a solution. I copied the folder "D: \ AppData \ MQTTX" to "C: \ Users \ Chinese. \ AppData \ Roaming \ MQTTX"
It can be opened normally. I will try using it to see if there are any other issues
Thank you again for your answer

**Comment by qq510768394** [comment]
No, I'm pretty sure. I used the default directory generated by the installation file during installation

**Comment by ysfscream** [comment]
Thank you for your response. I will look into this bug later.
