### ISSUE TITLE
[Help] What is "Path" in the set up config

### ISSUE THREAD

**Issue by audas** [emqx/MQTTX#1798]
I am unsure of what Path is meant to be in the set up config to connect to my MQTT broker

The "path" is required however there is nothing I can put in.

There is nothing in the docs and this field does not appear in the guides graphics at all.
 

While we are here is "Name" specific or can it be anything.

![image](https://github.com/user-attachments/assets/95153c13-9369-42d2-b0ed-9fad8c48b527)

**Comment by Red-Asuka** [comment]
When connecting to an MQTT server using a client like MQTTX with ws (WebSocket) or wss (WebSocket Secure) protocols, you need to specify the "Path." This path refers to the endpoint on the server that handles WebSocket requests. The default path is usually `/mqtt`, but this can vary based on the configuration of your MQTT broker or server. If you are unsure about what path to use, refer to the broker/server documentation, or consult the system administrator managing the server.

**Comment by audas** [comment]
Thanks - I reverted to the desktop version. The webui was not able to connect.

**Comment by ysfscream** [comment]
If there are no other problems, I will close it first.
