### ISSUE TITLE
[BUG] Installing MQTTX CLI on windows 11 arm64 via SETUP does not seem to update the path (cannot find mqttx via cli)

### ISSUE THREAD

**Issue by oising** [emqx/MQTTX#1804]
#### What did I do

Install the mqttx cli for v1.11 

#### What happened

Restarted my shell, mqttx not on path?

#### Expected

mqttx should be found on the path

#### Environment

- w11 on arm64 (sl7)
- w11 24h2/26100

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Hi,

The MQTTX CLI on Windows doesn't automatically configure the PATH environment variable during installation. You have two options:

1. Manual PATH Configuration:
   - Find your MQTTX installation directory
   - Add it to the System PATH manually
   
2. Recommended Easier Method:
   Install via npm globally (this handles PATH configuration automatically):
   ```bash
   npm install mqttx-cli -g
   ```
   This will make `mqttx` command available globally in your terminal.

The npm global installation is recommended as it's more straightforward and handles the PATH configuration automatically.
