### ISSUE TITLE
[BUG] MQTTX CLI for windows on arm does not work when downloaded directly (not using setup installer)

### ISSUE THREAD

**Issue by oising** [emqx/MQTTX#1805]
#### What did I do

Downloaded mqttx-cli-win-arm64.exe directly and attempted to run on windows 11 arm64 (SL7)

#### What happened

Got this:

![image](https://github.com/user-attachments/assets/f87be55a-3783-4899-9767-c147948c748b)

#### Expected

No errors

#### Environment

- windows 11 arm64, 24h2/26100

#### More detail

More detail include `log` information or screenshot

**Comment by oising** [comment]
I tried installing `icu` globally but it seems invisible to the embedded nodejs (my system has v22 globally, but this tool has an embedded v18)

**Comment by ysfscream** [comment]
Try not to use a standalone “.exe” file. I suggest installing MQTTX CLI via npm. It will handle dependencies correctly:

```bash
npm install mqttx-cli -g
```

**Comment by oising** [comment]
> Try not to use a standalone “.exe” file. I suggest installing MQTTX CLI via npm or docker, It can eliminate some differences between systems. It will handle dependencies correctly:
> 
> ```shell
> docker pull emqx/mqttx-cli
> docker run -it --rm emqx/mqttx-cli
> ```
> 
> ```shell
> npm install mqttx-cli -g
> ```

![image](https://github.com/user-attachments/assets/f108d47e-3f09-469e-a27a-ac736069e6f9)

**Comment by oising** [comment]
Seems like you forgot to pack faker as a dependency -- running `npm install @faker-js/faker -g` got me past this for the moment.

**Comment by oising** [comment]
Hmm, connects ok (azure event grid mqtt5 broker) but just hangs afterwards :/

<img width="610" alt="image" src="https://github.com/user-attachments/assets/55699ee3-8c88-4d39-9cad-56a8bd029d7f">

**Comment by ysfscream** [comment]
> Seems like you forgot to pack faker as a dependency -- running npm install @faker-js/faker -g got me past this for the moment.

Sorry. 😓 Has been already fixed on #1801; release to the next version...

**Comment by ysfscream** [comment]
npm issue fixed.
