### ISSUE TITLE
[Bug] MQTTX CLI won't recognize topic -t or --topic when used with -lo for loading connection options

### ISSUE THREAD

**Issue by oising** [emqx/MQTTX#1809]
#### What did I do

![image](https://github.com/user-attachments/assets/f2aee174-0e15-403f-b3d9-e1591d7ee5f3)

#### What happened

Get an error.

#### Expected

mqttx should allow me to pick a topic? lol

#### Environment

as my other bugs, SL7, node 22, win11 on arm64.

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Fixed on npm package next version:

<img width="363" alt="image" src="https://github.com/user-attachments/assets/4faa9bbe-5979-473f-9141-e13b42f3811d">

**Comment by Red-Asuka** [comment]
@oising Thank you for your feedback! This is a confirmed bug, and it will be fixed in the next release.
