### ISSUE TITLE
[Bug] MQTTX CLI  -- mqttx conn hangs after connection

### ISSUE THREAD

**Issue by oising** [emqx/MQTTX#1810]
#### What did I do

Whether passing via explicit args, or using saved json config, `mqttx conn` hangs after connecting. Is this meant to hang, or open a shell? What is the point of this functionality? If it's meant to test connection, it should close once connected successfully. Very confusing.

#### What happened

mqttx hangs.

![image](https://github.com/user-attachments/assets/6125380f-93c0-423f-94fa-e08df50009ee)

#### Expected

Absolutely no idea.

#### Environment

windows 11 arm64, SL7, node 22

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
The `mqttx conn` behavior is working as intended. It's designed to establish and maintain an MQTT connection - MQTT is built around sessions and persistent connections. The "hanging" state indicates a successful active connection.

You can:
- Use Ctrl+C to disconnect when done
- Use `pub` for publishing messages
- Use `sub` for subscribing
- Try `bench` or `simulate` for advanced scenarios

If you just need to verify connectivity, you can Ctrl+C after a successful connection.

**Comment by oising** [comment]
You could make it more explicit my emitting "Press ctrl+c to exit"

**Comment by ysfscream** [comment]
> You could make it more explicit my emitting "Press ctrl+c to exit"

Good suggestions, thank you.

**Comment by ysfscream** [comment]
Try https://github.com/emqx/MQTTX/releases/tag/v1.11.1 Thanks.
