### ISSUE TITLE
[Help] Can't get MQTTX-CLI working on Apple Silicon mac

### ISSUE THREAD

**Issue by kamikaze2112** [emqx/MQTTX#1845]
#### Describe the problem you Confuse

Was using the CLI MQTTX on my intel mac with no issues.  Installed via homebrew.  When installing via homebrew on apple silicon, I get the following error when trying to run a shell script that uses mqttx:

`./powerON.sh: line 2: /opt/homebrew/bin/mqttx: Bad CPU type in executable`

So i figured it's installing an intel binary, and uninstalled via brew uninstall.

Tried reinstalling from the commands on the website, specifically: 

`curl -LO https://www.emqx.com/en/downloads/MQTTX/v1.11.1/mqttx-cli-macos-arm64
sudo install ./mqttx-cli-macos-arm64 /usr/local/bin/mqttx`

which gives me a reply of:

`install: /usr/local/bin/mqttx: No such file or directory`

Kind of at a loss as to what to do next.

#### More detail (optional)

The contents of my shell script:

`#!/bin/bash
mqttx pub -t 'deskPower' -h '10.0.1.25' -p 1883 -m 'ON'`

**Comment by ysfscream** [comment]
Hi @kamikaze2112! I've tested both installation methods on my M1 Mac laptop, and they work fine for me. And to help better debug this issue, could you please share:

1. Your macOS version
2. Your Mac model/chip information (you can find this in "About This Mac")

For the installation error with `sudo install`, we can try creating the directory first:
```bash
sudo mkdir -p /usr/local/bin
```
Then, run the installation command again.

If both methods still don't work, two alternative installation options shouldn't have CPU architecture issues (though they require some prerequisites):

1. Docker:
```bash
docker run -it --rm emqx/mqttx-cli
```
(Requires Docker installed)

2. NPM:
```bash
npm install mqttx-cli -g
```
(Requires Node.js installed)

Let me know which method you'd prefer to try, and I'll help you get it working.

<img width="650" alt="image" src="https://github.com/user-attachments/assets/47b69967-f29a-406d-8c61-260b62cf60fd" />

![image](https://github.com/user-attachments/assets/afda59ef-a18a-4dbe-bee1-78f474b3ce5f)

**Comment by kamikaze2112** [comment]
> Hi @kamikaze2112! I've tested both installation methods on my M1 Mac laptop, and they work fine for me. And to help better debug this issue, could you please share:
> 
>     1. Your macOS version
> 
>     2. Your Mac model/chip information (you can find this in "About This Mac")
> 
> 
> For the installation error with `sudo install`, we can try creating the directory first:
> 
> ```shell
> sudo mkdir -p /usr/local/bin
> ```
> 
> Then, run the installation command again.
> 
> If both methods still don't work, two alternative installation options shouldn't have CPU architecture issues (though they require some prerequisites):
> 
>     1. Docker:
> 
> 
> ```shell
> docker run -it --rm emqx/mqttx-cli
> ```
> 
> (Requires Docker installed)
> 
>     2. NPM:
> 
> 
> ```shell
> npm install mqttx-cli -g
> ```
> 
> (Requires Node.js installed)
> 
> ![image](https://private-user-images.githubusercontent.com/21299158/398502276-fe0b2084-66a3-465e-9c34-f11813f765e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTY5MTYsIm5iZiI6MTczNTA5NjYxNiwicGF0aCI6Ii8yMTI5OTE1OC8zOTg1MDIyNzYtZmUwYjIwODQtNjZhMy00NjVlLTljMzQtZjExODEzZjc2NWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAzMTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MThiNTI2YTg5NDYyYzUwNmE2ZDNkMjdhMTA4ZDRmZDY4ZGMzMDBjMWNjYzc4MGE0MWM1ZWU5NzMxNzY1MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZthHB7gTflOod4uv22OGiXHCzZzZvJ6S-PAmDhAozI8)
> 
> ![image](https://private-user-images.githubusercontent.com/21299158/398501499-afda59ef-a18a-4dbe-bee1-78f474b3ce5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTY5MTYsIm5iZiI6MTczNTA5NjYxNiwicGF0aCI6Ii8yMTI5OTE1OC8zOTg1MDE0OTktYWZkYTU5ZWYtYTE4YS00ZGJlLWJlZTEtNzhmNDc0YjNjZTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAzMTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OGFjMDNhMDg3NTcyZDU4NWU1MGYyZjYwMzFjZGM4ZjE1MGZmMmY2MWRhOTNhZjNlMTUxYWU1Mzg4OTMxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WiCHaA-LAGJJlgkb3_-l-qRGE83JoHIuDHHUMQLhVpg)

Hi there, and thanks for the help.  creating the directory `/usr/local/bin` first as suggested seems to have worked.  Not sure why I needed to do this, but maybe because it's a brand new Mac and nothing else had been installed that would have created the folder first perhaps.

**Comment by ysfscream** [comment]
GOT IT. Have a good day.
