### ISSUE TITLE
CA certificate is not certified

### ISSUE THREAD

**Issue by 02monkey** [emqx/MQTTX#207]
With MQTTX V3.1, SSL server certificate authentication is turned on.If the CA certificate is not valid, it can be successfully connected by importing any certificate.It is the same as the emqx server, and the CA certificate can be normally certified under MQTT.fx

**Comment by ysfscream** [comment]
@02monkey Hi, thanks for your report. After testing, it should be a BUG, I will fix it soon.

**Comment by ysfscream** [comment]
The [v1.3.1](https://github.com/emqx/MQTTX/releases/tag/v1.3.1) may have solved this problem, You can enable the `Strict Validate Certificate` option, and then strictly certify your certificate. If you have any questions, you can discuss it here. Thank you for your feedback. :)
