### ISSUE TITLE
[FEATURE] Display content as hex values

### ISSUE THREAD

**Issue by perotom** [emqx/MQTTX#216]
Many constrained devices which use MQTT, use a binary message format. It would be great if it is possible to display the received content as hex values.

**Comment by ysfscream** [comment]
@perotom OK, this is a great suggestion. I will add the feature of format conversion of the received message content in the future version, Thank you!

**Comment by ysfscream** [comment]
Hi, This feature has been supported in [v1.3.3](
https://github.com/emqx/MQTTX/releases/tag/v1.3.3), thank you for your feedback, Hope to have a good experience :)
