### ISSUE TITLE
Impossible to send empty publish

### ISSUE THREAD

**Issue by davideferre** [emqx/MQTTX#218]
It seems there's no way to send an empty publish always in plaintext mode.
Can be removed the check that require at least a char to publish on a topic?

**Comment by ysfscream** [comment]
Hi @davideferre, if the "Retain" value is checked when sending the payload, you can send empty publish.

**Comment by davideferre** [comment]
Ok thank you so much! What’s the retain meaning? What’s his behavior?

**Comment by ysfscream** [comment]
A retained message is a normal MQTT message with the retained flag set to 1. The broker stores the last retained message and the corresponding QoS for that topic.  It's makes sense when you want newly-connected subscribers to receive messages immediately (without waiting until a publishing client sends the next message).

Send a retained message with a zero-byte payload on the topic where you want to delete the previous retained message.

So usually in most cases, it is not recommended to send an empty publish.

This may be a helpful article, you can read about MQTT.
https://www.emqx.io/blog/message-retention-and-message-expiration-interval-of-emqx-mqtt5-broker

**Comment by davideferre** [comment]
In the company where I work for  we use empty publish to request a device update, so we need an empty publish, but I don’t know if this is an anti-pattern.

**Comment by ysfscream** [comment]
Okay, maybe this is your business need and I don’t think it’s an anti-pattern. After the discussion, we think that some usage aspects may be too strict, and we should allow empty payload to be sent. I will remove this verification in the next version, just recently, if released, I will tell you here, thank you! :)

**Comment by davideferre** [comment]
Ok, thank you so much!

**Comment by ysfscream** [comment]
Hi, this issue has been resolved in [v1.3.1](https://github.com/emqx/MQTTX/releases/tag/v1.3.1), thank you so much for your suggestion, I will close this issue.

**Comment by davideferre** [comment]
> Hi, this issue has been resolved in [v1.3.1](https://github.com/emqx/MQTTX/releases/tag/v1.3.1), thank you so much for your suggestion, I will close this issue.

Thanks, I'm waiting the update through the ubuntu software center.

**Comment by ysfscream** [comment]
> > Hi, this issue has been resolved in [v1.3.1](https://github.com/emqx/MQTTX/releases/tag/v1.3.1), thank you so much for your suggestion, I will close this issue.
> 
> Thanks, I'm waiting the update through the ubuntu software center.

Already updated!
