### ISSUE TITLE
Allow empty port

### ISSUE THREAD

**Issue by morganwu** [emqx/MQTTX#224]
I've deployed EMQ server behind Nginx, and use 80 for WS connection and 443 for WSS. I can connect to server in web pages using Javascript client, but can not connect with MQTTX, no matter via 80 or 443. As the port is required, I can't leave it blank neither. So is it possible to make it optional? Thanks.

**Comment by ysfscream** [comment]
@morganwu Hi, I'm sorry for late reply. But I'm not sure if you don't enter the port, the default will be 1883. Is your JavaScript client connection using port 80 or 443?

**Comment by morganwu** [comment]
@ysfscream Thanks for your feedback, I think I'm using 443, here is my configuration for Nginx, FYI.
```
server {
    server_name  mq.xxxx.com;
    location /{
        proxy_set_header   Host    $host;
        proxy_pass http://localhost:18083;
    }
   location /mqtt {
        proxy_pass http://localhost:8083;
        proxy_redirect off;
        proxy_set_header Host localhost:8083;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Sec-WebSocket-Protocol mqtt;
        more_clear_headers Sec-WebSocket-Protocol;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/xxx.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/xxx.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

**Comment by ysfscream** [comment]
OK, first of all, your 443 port configuration should be forwarded to `http://localhost:8084` instead of `http://localhost:8083`. Then, I’m not sure if you entered the port in the JavaScript client in the web page. If no input, the port default value may be used.

**Comment by ysfscream** [comment]
I hope you have solved this problem well. I will close this issue, thanks :)
