### ISSUE TITLE
[FEATURE] Add support for labels on topics 

### ISSUE THREAD

**Issue by Metachemix1** [emqx/MQTTX#295]
I'm using this tool now for a few days, but still it lacks a feature that would be very handy for my usecases.

I have a couple topics open every day, to monitor them. However its not clear which topic is coming from which target. So the ability to add labels to a topic would make it visible that topic 1 is coming from target X and so on..

What do you think?

**Comment by ysfscream** [comment]
Sorry for the late reply.
> However its not clear which topic is coming from which target.
I don’t really understand what this target is. Maybe you mean to add a name to each topic?

**Comment by Metachemix1** [comment]
> Maybe you mean to add a name to each topic?

Let me clarify it a bit more in detail. Usually the MQTT targets that I'm connected to are using a generated UUID as prefix.

![image](https://user-images.githubusercontent.com/6442840/91006112-d1932700-e5d8-11ea-9bb9-7114b425ab84.png)

It would be handy to add a label to the topics so I can mark them, in the attached image for example, apollo would be target X and the second would be target Y (names are only for reference this should be free format)

**Comment by ysfscream** [comment]
Okay, thanks for your explanation. I probably understand it now. To put it simply, you need a label to explain what this topic is?

There may be some people who need this feature.

I will implement it in a later version.

**Comment by Metachemix1** [comment]
Correct and eventually the option to filter them on label would be nice as well :)

Great! Looking forward to it! Thanks for the feedback!

**Comment by ysfscream** [comment]
Now available in [v1.3.4](https://github.com/emqx/MQTTX/releases/tag/v1.3.4), thanks :)
