### ISSUE TITLE
[FEATURE] Supports right-clicking to copy all message content

### ISSUE THREAD

**Issue by supermareo** [emqx/MQTTX#299]
### 1. The content in the message bubble supports right-clicking to copy all content

At present, you need to select the text to copy, it is difficult to copy all the content when the message is very long

The above are some inconvenient places found in use, I hope to add related functions, thank you🌹🌹🌹

**Comment by ysfscream** [comment]
@supermareo Hi, thanks for your suggestion. First, I will help you translate the content into English, in order to let more people see.

I have planned this feature into the next version, but it may take a while. :)

**Comment by ysfscream** [comment]
Now available in [v1.3.4](https://github.com/emqx/MQTTX/releases/tag/v1.3.4), thanks :)
