### ISSUE TITLE
config export and connection file export function

### ISSUE THREAD

**Issue by BlueCompiler** [emqx/MQTTX#300]
when I switch into a new computer, and I still in use MQTTX tool, so I hope could export all the config I used easylly, and in another computer just do inport the config file of MQTTX tool.
But now, all the MQTTX config I used needs me type on keyboard one by one on another computer, the work is too much.

**Comment by ysfscream** [comment]
@BlueCompiler Yes, this is a good ideal. It's planned for the next version. It provides data backup function, import and export `json` or `csv` files, etc. Thanks! :)

**Comment by BlueCompiler** [comment]
> @BlueCompiler Yes, this is a good idea. It's planned for the next version. It provides data backup function, import and export `json` or `csv` files, etc. Thanks! :)

That is GREAT, when the new version issued, please you note me, thanks

**Comment by ysfscream** [comment]
Now available in [v1.3.4](https://github.com/emqx/MQTTX/releases/tag/v1.3.4), thanks :)
