### ISSUE TITLE
Version update viewing function

### ISSUE THREAD

**Issue by BlueCompiler** [emqx/MQTTX#301]
I hope MQTTX could with "Version update viewing function". Or  MQTTX itself check the new version. So we client could be always use the new feature of MQTTX.

**Comment by ysfscream** [comment]
This feature has always existed, you can turn on the automatic check function in the settings.

![image](https://user-images.githubusercontent.com/21299158/91634241-71a9df80-ea21-11ea-91b4-e24f74e89189.png)

Check for updates every time you open the software.

**Comment by ysfscream** [comment]
If there are no problems, I will close this issue. Thanks :)
