### ISSUE TITLE
cannot open multiple windows

### ISSUE THREAD

**Issue by motto123** [emqx/MQTTX#311]
I hope open multiple windows or create multiple connect.thank u.

**Comment by motto123** [comment]
I find that it create multiple connect.so I closed the question.

**Comment by ysfscream** [comment]
OK, it does not matter, I think multiple windows are also a good idea.

**Comment by motto123** [comment]
Yeah, it`s good idea.

**Comment by ysfscream** [comment]
Closed via [v1.4.0](https://github.com/emqx/MQTTX/releases/tag/v1.4.0)
