### ISSUE TITLE
clean history, subscribe list will also be cleaned

### ISSUE THREAD

**Issue by YiuTerran** [emqx/MQTTX#333]
As Title.

Another problem is that, topic should be auto trimed, or highlight the spaces at front or tail.

**Comment by ysfscream** [comment]
Hey, as you said, Trim topic should be added, I will fix it. But I don’t think all subscriptions should be cancelled when clean history, this is only for messages.

**Comment by YiuTerran** [comment]
Sorry. I created a wrong bug for the subscribe list.

The real problem is: the subscribe list will be cleaned after disconnecting. How can i remember them?

**Comment by ysfscream** [comment]
You can try to set `Clean Session` to `False`.

**Comment by YiuTerran** [comment]
oh, i got it. thank you!
