### ISSUE TITLE
Hope to integrate mqtt-cli command line mode, support import and export commands, similar to postman's export API

### ISSUE THREAD

**Issue by workcheng** [emqx/MQTTX#344]
As the title, I hope to add this function so that a use case can be formed for testing.

**Comment by ysfscream** [comment]
Hello, thanks for your suggestion. The following is my point:

1. But I think MQTT X is originally a graphical tool, and the newly added CLI mode is not incompatible with software design

2. Currently MQTTX already supports import and export functions, the current version only supports JSON files, the next version already supports XML, CSV and Excel.

We can continue the discussion here.

**Comment by ysfscream** [comment]
Thank you for your support of MQTTX, I hope your problem has been solved. Next, the import and export of payload will be implemented. I will close this issue. :)
