### ISSUE TITLE
Changed the custom port, but still connect to port 1883

### ISSUE THREAD

**Issue by ckforce** [emqx/MQTTX#358]
System: windows10

**Comment by ckforce** [comment]
![image](https://user-images.githubusercontent.com/22431888/99183757-26c67b00-2779-11eb-834c-2e7a49cd24a4.png)

**Comment by ysfscream** [comment]
Yes, this is a bug, sorry about that, but it has been fixed now, you need to download the installation package again.

**Comment by ysfscream** [comment]
Yes, this is a bug, sorry about that, but it has been fixed now, you need to download the installation package again.

**Comment by ckforce** [comment]
thx. where to download the new version?

**Comment by ysfscream** [comment]
Thanks for your feedback. If there are no problems, I will close this issue.
