### ISSUE TITLE
Build error - production

### ISSUE THREAD

**Issue by benricok** [emqx/MQTTX#366]
Hi, I found interest in this project an decided to try it. I did all required steps stated in the readme but got an error when I ran: `yarn run electron:build`

#### Output:
yarn run v1.22.5
$ vue-cli-service electron:build --win --linux --mac
 INFO  Bundling render process:

Building modern bundle for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
Building modern bundle for production...

 ERROR  Failed to compile with 1 errors                           

 error  in /home/<username>/Nextcloud/Documents/Projects/MQTTX/src/router/index.ts

ERROR in /home/<username>/Nextcloud/Documents/Projects/MQTTX/src/router/index.ts
5:33 Cannot find module '@/views/Connections/types' or its corresponding type declarations.
    3 | import routes from './routes'
    4 | import { loadConnections } from '@/utils/api/connection'
    5 | import { ConnectionModel } from '@/views/Connections/types'
       |                                                      ^
    6 | 
    7 | Vue.use(Router)
    8 | 

 ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 

#### `yarn install --check-files` gives me:
yarn install v1.22.5
[1/5] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder  version=21.2.0
Done in 3.21s.

### System specs:
OS: Arch Linux x86_64 
Kernel: 5.8.10-arch1-1 
CPU: Intel i7-4860HQ (8) @ 3.600GHz 
RAM: 16GB

**Comment by ysfscream** [comment]
Hello, what is your `Node` version? Can it run in developer mode? Please make sure to install dependencies before running. Or check if the file directory has been changed by you.

**Comment by benricok** [comment]
Hi my node version is v14.12.0. When running `yarn run electron:serve` it compiles successfully and throws the same error but it does successfully open the application in development mode. Will check if I can communicate with my mqtt broker now and update this conversation.

**Comment by benricok** [comment]
> Will check if I can communicate with my mqtt broker now and update this conversation.
I can confirm that I can send and recieve mqtt messages with the application running in development mode

**Comment by oceanlvr** [comment]
> 
> 
> I can confirm that I can send and recieve mqtt messages with the application running in development mode

Hi! I got same problem, and I find it's because system's file watchers limit.[https://github.com/gatsbyjs/gatsby/issues/11406#issuecomment-458769756](https://github.com/gatsbyjs/gatsby/issues/11406#issuecomment-458769756)

This commands maybe can help you.

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
