### ISSUE TITLE
Add log system

### ISSUE THREAD

**Issue by ysfscream** [emqx/MQTTX#367]

**Comment by oceanlvr** [comment]
Implement a log information system that can record connection information, subscription information, errors, and warnings.

* Quickly locate errors
* Record connection information
* Convenient to analyze the connection process

solution?

* Lib [log4js-node](https://github.com/log4js-node/log4js-node) (temporarily)
* log UI

log item example?

normal:

```
${time} ${LogLevel}-${Event-name}:   ${detail}
```

error/warning/undefined behavior

```
${time} ${LogLevel}-${Event-name}:   ${detail}
${error/warning/undefined behavior content}
```


Where I should record to log?

* Before and after calling external interface (call other libs)
* occur error or warning (something wrong append)
* System entrance and exit 
* System status change (disconnect/connect)
* Unexpected behavior


ref document: [https://www.jianshu.com/p/a6c643a87ef9](https://www.jianshu.com/p/a6c643a87ef9)

**Comment by ysfscream** [comment]
You can also refer to this package.

https://www.npmjs.com/package/electron-log

**Comment by oceanlvr** [comment]
solution:

0. Create a new log file
1. Appender add log information to file
2. Log page spy on the newest log file
3. Trigger update event for log page

**Comment by ysfscream** [comment]
Finished on https://github.com/emqx/MQTTX/releases/tag/v1.5.0
