### ISSUE TITLE
Append timestamp to MQTT client id (Optional)

### ISSUE THREAD

**Issue by ysfscream** [emqx/MQTTX#394]

**Comment by oceanlvr** [comment]
@ysfscream Hi! Can we close this issue now? :raised_hand::raised_hand:

**Comment by ysfscream** [comment]
@oceanlvr No now, close it when the new version package containing this issue is released.

**Comment by ysfscream** [comment]
Fixed on [v1.4.2](https://github.com/emqx/MQTTX/releases/tag/v1.4.2)
