### ISSUE TITLE
mqttx can not connection emqx broker

### ISSUE THREAD

**Issue by sdhzlzhk** [emqx/MQTTX#425]
![深度截图_选择区域_20201224211401](https://user-images.githubusercontent.com/7436812/103090764-fce05e00-462c-11eb-9b7f-3bb5904f86f3.png)
I snap install mqttx 1.4.2 version, I got the "UnhandledPromiseRejectionWarning"  info when I launcher。please tell me why and how to solve it.
##############the consonle output##################
(node:20739) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN api.github.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
(node:20739) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20739) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by oceanlvr** [comment]
Hi, Thank you for your support for `mqttx`.
For your question, I downloaded the latest version with `snap` on `vbox` and it works fine.

![image](https://user-images.githubusercontent.com/36698124/102734112-fb3b3f80-4379-11eb-80a4-6d734fb271d9.png)

and it works normally:

![image](https://user-images.githubusercontent.com/36698124/102734244-52d9ab00-437a-11eb-9df3-4d63dd5de01e.png)

![image](https://user-images.githubusercontent.com/36698124/102734281-6dac1f80-437a-11eb-9acd-5ac4f0bff158.png)


It works for me in `ubuntu18/debian` environment:

```shell
sudo snap install mqttx
```

Could you please tell me more about your environment information?

please follow this template:

```markdown

## what did I do

something you have done.

## what happened

get an error

## environment

- ubuntu

## log/Screenshot/context

xxxxx

```

**Comment by oceanlvr** [comment]
I think it might be a DNS lookup timed out error means it is either a network connectivity error or some proxy related error. Try resolving your proxy settings and check you have a decent internet connection or not.

DNS can't resolve the `api.github.com`.

**Comment by sdhzlzhk** [comment]
thank you @oceanlvr , I used lantern proxy ,  so I closed lantern and unset http_proxy,https_proxy, but never solved. so bad lucy

**Comment by oceanlvr** [comment]
Hi, @sdhzlzhk.
I am sorry that you cannot solve your problem from the limited information.`MQTTX` currently does not have a log system,(I am building this part). So I cannot accurately get the context of your error.

But I am pretty sure that it is because your MQTTX cannot be resolved `api.github.com`. This is the relevant code part:[updateChecker.ts](https://github.com/emqx/MQTTX/blob/bef5db02353f41fcdafe5338128f76b455f4ba81/src/main/updateChecker.ts#L23)

Maybe it will work after reinstalling, Thank you again for your support to `MQTTX`.

**Comment by oceanlvr** [comment]
![image](https://user-images.githubusercontent.com/36698124/103122473-5f803b00-46bb-11eb-8b4f-dc4880c76f4a.png)

**Comment by oceanlvr** [comment]
ref 
* [https://github.com/npm/npm/issues/15059](https://github.com/npm/npm/issues/15059)
* [https://github.com/sendgrid/sendgrid-nodejs/issues/927](https://github.com/sendgrid/sendgrid-nodejs/issues/927)
