### ISSUE TITLE
wildcard topics were not supported.

### ISSUE THREAD

**Issue by ShankzPatil** [emqx/MQTTX#426]
Topic on the broker | Subscribe Topic 
-- | --
a/b/c/d/something | a/b/# 
a/b/c | a/b/+

**Comment by ysfscream** [comment]
Hi, sorry for the late reply. May I ask what version and operating system you are using. After my test, I did not find this problem.

![image](https://user-images.githubusercontent.com/21299158/102730602-2e78d100-4370-11eb-92ad-b69af38e26d8.png)

**Comment by ysfscream** [comment]
Thank you for your support to MQTTX. Hope your problem has been solved, I will close this issue.
