### ISSUE TITLE
how to upload the  protobuf data by use the mqttx client?

### ISSUE THREAD

**Issue by zth390872451** [emqx/MQTTX#440]
I want to use the mqttx client ,how to upload the protobuf data?

**Comment by ysfscream** [comment]
Sorry about that, Protobuf is currently not supported. But you can try sending in Plaintext mode, the data will be sent in Buffer format.

**Comment by ysfscream** [comment]
Thanks for your support of MQTTX, I hope your problem has been solved, I will close this issue.
