### ISSUE TITLE
Cannot find module '@/views/Connections/types' or its corresponding type declarations. (on Linux)

### ISSUE THREAD

**Issue by linfengyong** [emqx/MQTTX#448]
Need to change file "src/router/index.ts" (line 5):

`import { ConnectionModel } from '@/views/Connections/types'`
change to
`import { ConnectionModel } from '@/views/connections/types'`

**Comment by oceanlvr** [comment]
Hi, @linfengyong 
Thanks for your feedback. And I don't understand the situation you describe. Could you please descript its details?
you can follow the `issue-template`, which will be better.

[bug-report-template](https://raw.githubusercontent.com/emqx/MQTTX/dev/1.4.3/.github/ISSUE_TEMPLATE/bug_report.md)

```
---
name: Bug report
about: Create a report to help us improve
title: "[Bug] the title of bug report"
labels: bug
assignees: ''

---

## what did I do

something you have done.

## what happened

get an error

## environment

- ubuntu

## log/Screenshot/context

xxxx
```

**Comment by linfengyong** [comment]
I want to install MQTTX on ubuntu, the commands likes:
`
git clone https://github.com/emqx/MQTTX
cd MQTTX
yarn install
`
change package.json file on line 9 to:
`
"electron:build": "vue-cli-service electron:build --linux"
`
now every thing is ok, but when I execute then build command, then an error occur:
`
yarn run electron:build
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                            9:55:14 AM

 error  in /home/yflin/tools/MQTTX/src/router/index.ts

ERROR in /home/yflin/tools/MQTTX/src/router/index.ts
5:33 Cannot find module '@/views/Connections/types' or its corresponding type declarations.
    3 | import routes from './routes'
    4 | import { loadConnections } from '@/api/connection'
  > 5 | import { ConnectionModel } from '@/views/Connections/types'
      |                                 ^
    6 | 
    7 | Vue.use(Router)
    8 | 

 ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
then, I modify then file /home/yflin/tools/MQTTX/src/router/index.ts on line 5:
`
import { ConnectionModel } from '@/views/Connections/types'
`
to
`
import { ConnectionModel } from '@/views/connections/types'
`
then rebuild it success.

**Comment by oceanlvr** [comment]
@linfengyong 
Thanks a lot for the report, this is indeed our fault, I will fix this right now. :)

**Comment by oceanlvr** [comment]
fixed: #451

**Comment by ysfscream** [comment]
@oceanlvr Please close this issue when the new package containing this fix is ​​released. :)

**Comment by ysfscream** [comment]
@linfengyong Fixed on https://github.com/emqx/MQTTX/releases/tag/v1.5.0 Thanks for your support of MQTTX.
