### ISSUE TITLE
Save subscriptions in between connections/sessions

### ISSUE THREAD

**Issue by zyphlar** [emqx/MQTTX#454]
I have a number of things I need to subscribe to, and typos cause auto-disconnection which is a real pain. Having my subscriptions persist would really help.

**Comment by ysfscream** [comment]
Hello agin. This is actually the case, the subscription will be saved, but when the `Clean Session` is `false`. If it's `true`, the subscribed topic will also be invalid, because it may not make sense to save.

**Comment by ysfscream** [comment]
Thanks for your support of MQTTX, I hope your problem has been solved, I will close this issue.
