### ISSUE TITLE
Save publish-topics historically

### ISSUE THREAD

**Issue by zyphlar** [emqx/MQTTX#455]
Much like a browser window with URLs, being able to quickly recall and publish to a past topic name instead of having to re-type every time would be very useful. Maybe a combo drop-down text box?

**Comment by ysfscream** [comment]
Hi, thanks for your support for `MQTT X`. This is a good suggestion worth discussing, there is already a plan that includes this feature #428 . The specific implementation may need to be redesigned, I will complete it as soon as possible.

**Comment by oceanlvr** [comment]
@zyphlar Hi, the next version will have support for the quick selection of historical records.
