### ISSUE TITLE
[Bug] After clearing the data, mqttx cannot find the log file

### ISSUE THREAD

**Issue by oceanlvr** [emqx/MQTTX#472]
## what did I do

cleaned the user data. Then when I close the `MQTTX`, the error report.

## what happened

get an error

## environment

- MacOS Big Sur 11.1
- MQTT x v1.5.0

## log/Screenshot/context

![image](https://user-images.githubusercontent.com/36698124/106085852-f1b4ac80-615b-11eb-9abf-c6da8882f422.png)

**Comment by ysfscream** [comment]
Fixed on https://github.com/emqx/MQTTX/releases/tag/v1.5.1
