### ISSUE TITLE
[Bug] JavaScript Uncaught Exception when closing MQTTX 1.5 or 1.5.1 on Windows

### ISSUE THREAD

**Issue by gm1168** [emqx/MQTTX#491]
#### What did I do

Close/Quit the MQTTX application (v1.5 or 1.5.1) running on Windows (Windows 10).

#### What happened

Received a JavaScript error on closing the application.

#### Expected

Application closure without error (as seen in v1.4.2).

#### Environment

- OS: Windows 10
- MQTTX version: 1.5 and 1.5.1
Used two different Windows 10 computers will the same result.

#### More detail

JavaScript error info received (example):

Error
A JavaScript error occurred in the main process

Uncaught Exception:
Error: EINVAL: invalid argument, rename
‘C:\Users\MYUSERNAME\AppData\Roaming\MQTTX/logs/log' ->
'C:\Users\MYUSERNAME\AppData\Roaming\MQTTX/logs/log/2021-01-29T1948.log'
at Object.renameSync (fs.js:619:3)
at
C:\Users\MYUSERNAME\AppData\Local\Programs\MQTTX\resources\app.asar\back...:193543
at H
(C:\Users\MYUSERNAME\AppData\Local\Programs\MQTTX\resources\app.asar\back...:193582)
at BrowserWindow.<anonymous>

**Comment by oceanlvr** [comment]
Thanks for your support, it seems like we don't deal with the path in windows. Sorry for the carelessness, I'll fix it right now.
@gm1168

**Comment by oceanlvr** [comment]
@gm1168 We have resolved the related issues and the changes will be attached to the next update version `v1.5.2`.
The current impact is that the history log cannot be saved correctly, and will not affect your other operations.

**Comment by ysfscream** [comment]
Thanks for your feedback! It's fixed on https://github.com/emqx/MQTTX/releases/tag/v1.5.2
