### ISSUE TITLE
[Bug] When the name is very long, the page layout is wrong

### ISSUE THREAD

**Issue by Adek06** [emqx/MQTTX#493]
#### What did I do

set a long host name

#### What happened

the host name covers the button

#### Expected

don't cover buttons 

#### Environment

- OS: OS version, e.g. MacOS Mojave 10.14.6
- MQTTX version, e.g. v1.5.1

#### More detail

![image](https://user-images.githubusercontent.com/25602645/106567081-2bc2eb80-656c-11eb-934a-0aec2f10f50d.png)

**Comment by ysfscream** [comment]
Fixed on https://github.com/emqx/MQTTX/releases/tag/v1.5.2
