### ISSUE TITLE
[Bug] Client disconnects before create a topic

### ISSUE THREAD

**Issue by moraesjeremias** [emqx/MQTTX#502]
#### What did I do

After successfully connect to my broker (AWS IoT Core) I tried to create a topic in order to send and receive messages

#### What happened

After hit confirm button the client simply disconnects with no error message at first, then shows 'Client not connected' warning.

#### Expected

It was supposed to create a pub/sub topic in MQQTX client

#### Environment

- OS: OS version, e.g. MacOS Catalina 10.15.7
- MQTTX version, e.g. v1.5.1

#### More detail
**Link to Youtube video:**
[![MQTTX topic creation bug](https://filebin.net/x1rsx1psfjd04zlx/thumb0001.jpg?t=rhtuz02s)](http://www.youtube.com/watch?v=RFe3cHqSCm0 "MQTTX topic creation bug")

More detail include `log` information or screenshot

**Comment by moraesjeremias** [comment]
Aparently It was not involved with MQTTX Client, in fact it was a misconfigured AWS IoT Core policy attached on my certificate.

The work around was to configure individually actions in the policy.

I'm closing this issue but maybe an enhancement could be discussed for further backlog: Disconnect messages with log links.

**Comment by ysfscream** [comment]
Hi, sorry for my late reply! Thanks for your support of MQTT X. We will continue to improve the log function in subsequent versions.
