### ISSUE TITLE
[Feature] Optimize log information viewing

### ISSUE THREAD

**Issue by ysfscream** [emqx/MQTTX#510]
I think every time a user opens the log page, the information they want to view is at the bottom.

If there is a lot of log information, users need to scroll for a long time to view the latest log, so I think we need to display the latest log to the bottom every time.

![image](https://user-images.githubusercontent.com/21299158/108169596-e7227d00-7133-11eb-985b-468f23b48fea.png)

**Comment by oceanlvr** [comment]
@ysfscream yes, it's friendly for users to look up the latest log file. I'll add this function.

**Comment by ysfscream** [comment]
@oceanlvr Thanks!

**Comment by ysfscream** [comment]
Finished on https://github.com/emqx/MQTTX/releases/tag/v1.5.2
