### ISSUE TITLE
[Feature] support Protobuf

### ISSUE THREAD

**Issue by Lua12138** [emqx/MQTTX#555]
#### Motivation

I hope that the plan supports the sending and displaying of Protobuf, or allows users to provide support for this type of payload through scripts

#### Detailed design

MQTTX supports payload of Protobuf type directly or allows it to be supported by script.

#### Alternatives

None

#### More detail (optional)

None

---

According #116 @ysfscream

**Comment by TommyDuc** [comment]
I have been heavily involved in projects that uses protobufs over MQTT as a macro-service broker.
Being able to see the protobufs as JSON or equivalent would be very much a welcome feature!

**Comment by jerrdasur** [comment]
Any news about that?
Maybe you need help with that? I'll be glad to provide draft PR for protobuf support, cos I need this too :)

**Comment by Red-Asuka** [comment]
@jerrdasur Hi there, thank you for your interest in our project. We appreciate your offer to help with the protobuf support and would be grateful for any contribution you can make. Your draft PR would be very welcome, as we are short on resources at the moment. We will review your PR as soon as possible and provide feedback. Thank you again for your willingness to support our project!

**Comment by ysfscream** [comment]
Hi, all. Thank you for your feedback. Currently, we have added support for it in https://github.com/emqx/MQTTX/releases/tag/v1.9.4.

**Comment by Lua12138** [comment]
@ysfscream 

I have some confusion.

I have a protobuf file like this:

```proto
syntax = "proto3";

enum ActionType {
    PingPong = 0;
}

message CommonInputMessage {
    ActionType Action = 1;
    string RelayTopic = 2;
    bytes Extra = 3;
}

message CommonOutputMessage {
    ActionType Action = 1;
    bytes Extra = 2;
}
```
I want to send `CommonInputMessage` and receive `CommonOutputMessage`, how should I set it up in MQTTX Desktop?

`Run Script` -> `Schema` chose the proto file -> What should I put in the `Proto name`?

**Comment by ysfscream** [comment]
Hi @Lua12138 👋,

Thank you for reaching out. Currently, the MQTTX Desktop version does not offer specific handling for using different protobuf messages for the publishing and subscribing ends. Regarding different topics, this issue is analogous to the one described in https://github.com/emqx/MQTTX/issues/1371

We have plans to optimize this in upcoming releases. For now, to address your needs, we recommend using MQTTX CLI. Here are the relevant commands:

```bash
mqttx pub -t 'yourInputTopic' -h yourBrokerURL -Pp ./yourProtoFileName.proto -Pmn CommonInputMessage -m "xxx"
mqttx sub -t 'yourOutputTopic' -h yourBrokerURL -Pp ./yourProtoFileName.proto -Pmn CommonOutputMessage
```

Thank you for your understanding and feedback. We're continuously working to improve.
