### ISSUE TITLE
[Bug] 无法删除订阅列表中的主题

### ISSUE THREAD

**Issue by chenzhiguo** [emqx/MQTTX#585]
#### What did I do

无法删除订阅列表中的主题

#### What happened

无法删除订阅列表中的主题，无任何提示

#### Expected

What is the expected result.

#### Environment

- OS: OS version, e.g. MacOS Big Sur 11.1
- MQTTX version, e.g. v1.5.0

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Hi, thanks for your report! Maybe you need to delete Topic only when the client is connected

**Comment by ysfscream** [comment]
Hi, thanks for using MQTT X. If there are no more questions, I will close the issue.
