### ISSUE TITLE
[Bug] toggle Subscriptions, the contents of the send box are cover

### ISSUE THREAD

**Issue by mengday** [emqx/MQTTX#593]
#### What did I do

Something you have done.

#### What happened

toggle Subscriptions, the contents of the send box are cover.
  
#### Expected

What is the expected result.

#### Environment

- OS: OS version, e.g. MacOS Big Sur 11.1
- MQTTX version, e.g. v1.5.0

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Hi! Thanks for your feedback! But could you please describe the problem more specifically? It is better to have a reproducible step.

**Comment by mengday** [comment]
> Hi! Thanks for your feedback! But could you please describe the problem more specifically? It is better to have a reproducible step.

step1: [step1](https://tva1.sinaimg.cn/large/008i3skNgy1grd8rkc0q7j31520u0n28.jpg)  

step2: [https://tva1.sinaimg.cn/large/008i3skNgy1grd8scutl0j31520u0q7t.jpg](url)    msg normal

step3 : [https://tva1.sinaimg.cn/large/008i3skNgy1grd8uwuv32j31520u043b.jpg](url)   msg cover

**Comment by ysfscream** [comment]
@mengday OK, thanks! I successfully reproduced it, sorry, this is a bug, we will fix it as soon as possible.

**Comment by ysfscream** [comment]
Hi, thanks again! It is now fixed at https://github.com/emqx/MQTTX/releases/tag/v1.6.0.
