### ISSUE TITLE
Please upgrade mqtt.js

### ISSUE THREAD

**Issue by gilbertwong96** [emqx/MQTTX#595]
Here is the bug report of MQTT.js which is bumped v4.2.1: https://github.com/mqttjs/MQTT.js/issues/1152.

And here is the bug fix PR: https://github.com/mqttjs/MQTT.js/pull/1162.

I hope you guys can follow the upstream of MQTT.js and fix bug asap.

**Comment by ysfscream** [comment]
Hi, thanks again! It is now fixed at https://github.com/emqx/MQTTX/releases/tag/v1.6.0.
