### ISSUE TITLE
[Help] emqx resend qos 1 message?

### ISSUE THREAD

**Issue by HiwayChe** [emqx/MQTTX#599]
#### Describe the problem you Confuse

Hi,  my java application use hive-mqtt-client-1.2.2(mqttV5 protocol) to sub emqx-4.2.2, my iot equipment use mqttV3.1 to pub to emqx, that means I use different mqtt protocols in clients to communicate with emqx, is it OK? 

sometimes there is error message in log:
`2021-06-09 19:29:30.806 [com.hivemq.client.mqtt-10-2] ERROR c.h.c.i.m.h.p.incoming.MqttIncomingQosHandler:51 - QoS 1 PUBLISH (MqttStatefulPublish{stateless=MqttPublish{topic=BGT1/1918BD000186/PeriodReportBin, payload=65byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=419, dup=false, topicAlias=0, subscriptionIdentifiers=[9]}) must not be resent (MqttStatefulPublish{stateless=MqttPublish{topic=BGT1/1918BD000186/PeriodReportBin, payload=65byte, qos=AT_LEAST_ONCE, retain=false}, packetIdentifier=419, dup=true, topicAlias=0, subscriptionIdentifiers=[9]}) during the same connection`

I also asked this question at `https://github.com/hivemq/hivemq-mqtt-client/issues/491`, @LBrandl said that `https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901236` `4.4 Message delivery retry`:
`When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. Clients and Servers MUST NOT resend messages at any other time [MQTT-4.4.0-1].`
this means emqx should not resend this message to subscriber?  is it caused by different mqtt protocols used by publisher and subscriber?

#### More detail (optional)

![image](https://user-images.githubusercontent.com/5837440/121652448-3ec36a80-cace-11eb-944f-95631673ad62.png)

**Comment by DDDHuang** [comment]
If qos 1 message ack timeout,  EMQ X resend message by dup message.

**Comment by HiwayChe** [comment]
@DDDHuang , thanks. your answer sounds reasonable, I did not find any details about message retry when ack timeout in mqtt spec doc, maybe I should use mqttV3 to subscibe.

**Comment by ysfscream** [comment]
Hi, If there are no more questions, I will close the issue.
