### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by yaobo-lab** [emqx/MQTTX#604]
#### What did I do

Something you have done.

#### What happened

Get an error.

#### Expected

What is the expected result.

#### Environment

- OS: OS version, e.g. win7
- MQTTX version, e.g. v1.5.5

#### More detail

More detail include `log` information or screenshot

1：不支持配置文件导出到另外一台脑使用
![image](https://user-images.githubusercontent.com/21329253/122527649-18fa1080-d04e-11eb-9138-b919c0711c14.png)

2：启动多几个客户端。后之前的连接，全部变空白，而且明明设置了中文，也重置了

![image](https://user-images.githubusercontent.com/21329253/122527870-4e066300-d04e-11eb-8a4b-8660e23d8838.png)

**Comment by ysfscream** [comment]
@yaobo-lab YES! You can refer to this document page for data management in the settings.

https://mqttx.app/zh/docs#%E8%AE%BE%E7%BD%AE
