### ISSUE TITLE
Edit subscriptions

### ISSUE THREAD

**Issue by tafo86awtech** [emqx/MQTTX#617]
#### Motivation

If a create a subscription and i want to modify it,  now I have to create a new one.
It's a problem if a many topics that change for a only word.

**Comment by ysfscream** [comment]
@tafo86awtech YES! This is a good suggestion, we will implement it in a future version.

**Comment by ysfscream** [comment]
Thanks for your suggestion. In https://github.com/emqx/MQTTX/releases/tag/v1.7.1 already support.
