### ISSUE TITLE
消息过期时间？

### ISSUE THREAD

**Issue by HiwayChe** [emqx/MQTTX#619]
https://zhuanlan.zhihu.com/p/121615643

> 消息过期间隔

> PUBLISH 报文可以设置消息过期间隔这一属性，消息过期间隔是一个四字节的整数，表示应用消息的生命周期，单位是秒。
> 如果 PUBLISH 报文不设置消息过期间隔，那么应用消息不会过期。

mqttV5支持message expiry interval，我发布消息的时候指定了messageExpiryInterval，
`client.publishWith().topic(device.getTopic()).messageExpiryInterval(120).qos(MqttQos.AT_LEAST_ONCE).payload(device.generateMessage().getBytes()).send()`
发完消息后启动消费者，这个时候消费者收不到消息。
是我对message expiry interval理解有误吗？ 还是哪里需要配置？
生产者发布消息的时候如果消费者不在线，这条消息就丢弃了？ 有没有办法让消息停留一段时间，因为这个时候消费者可能正在重启过程中。

**Comment by HiwayChe** [comment]
好像我的测试类有问题，我先改下。

**Comment by HiwayChe** [comment]
结论：
1. 消费者的clientId重启前后要保持不变。
2. 发布消息的时候，消费者session要存在，可以是disconnected状态。需要设置session expiry interval为一个合理的值。
3. 消费者再次连接的时候，要先注册监听再连接，不然连上了broker就推消息过来，这个时候消费者可能还没监听，导致消息丢了。https://github.com/hivemq/hivemq-mqtt-client/issues/368

**Comment by ysfscream** [comment]
It's good！Thanks for using MQTT X!
