### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by ve3344** [emqx/MQTTX#627]
#### What did I do

发送大量的消息（长按ctrl+enter）

#### What happened

一段时间后无法再发送新的消息
似乎是 C:\Users\luo\AppData\Roaming\MQTTX\db.json在大量写入时出现了问题
#### Environment

- OS: Windows10
- MQTTX version, e.g. v1.6.0

#### More detail

重新打开后，所有已保存的Connections 都丢失了

**Comment by ysfscream** [comment]
@ve3344 Hello, thanks for your feedback, this should be a known issue, perhaps a little similar is this issue: #524 

Some read and write problems exist when the received and sent messages are too large, we will consider methods such as replacing the Database to optimize the next.
