### ISSUE TITLE
payload format indicator missing for textual payload

### ISSUE THREAD

**Issue by MartinL0815** [emqx/MQTTX#637]
### Discussed in https://github.com/emqx/MQTTX/discussions/634

<div type='discussions-op-text'>

<sup>Originally posted by **MartinL0815** July 16, 2021</sup>
Dear devs,

I just care for a problem ticket of a customer in our simulation embedded client.
The customer complained, that JSON payload published is identified to be binary in our client.

Checking the MQTT properties of the published package I see, that the payload format identificator is missing  and the publish packet contains unspecified or application specifc data (handled as binary).

This is identical to providing the MQTT property "payload format indicator" with the value 0.

A payload format indicator of 1 tells the publish packet would contain an UTF-8 string as payload. An additional exiting MQTT property for the content-type may than detail the payload content format.

Did I miss something or is there a bug to be filed?

Here a cite from the specs I followed while implementing our embedded client:

> 3.1.3.2.3 Payload Format Indicator
> 1 (0x01) Byte, Identifier of the Payload Format Indicator.
> Followed by the value of the Payload Format Indicator, either of:
> * 0 (0x00) Byte Indicates that the Will Message is unspecified bytes, which is equivalent to not sending a Payload Format Indicator.
> * 1 (0x01) Byte Indicates that the Will Message is UTF-8 Encoded Character Data. The UTF-8 data in the Payload MUST be well-formed UTF-8 as defined by the Unicode specification [Unicode] and restated in RFC 3629 [RFC3629].
> 
> It is a Protocol Error to include the Payload Format Indicator more than once. The Server MAY validate that the Will Message is of the format indicated, and if it is not send a CONNACK with the Reason Code of 0x99 (Payload format invalid) as described in section 4.13.
>
> https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901063

If it is a bug, I would file it here in github.

Could we please connect and discuss this before I have to react to the customer?

Thanks!

Best regards

Martin</div>

In the original discussion I was already convinced, that an interactive client publishing a payload, where the customer clearly has chosen a textual format, should contain the payload format identificator with the value 1 (UTF-8 text) and the content-type, if a IANA MIME type is available for the user chosen textual format - e.g. "application/json" for JSON.

But the MQTTX client does not send a payload format indicator at all, so a receiving client must assume to receive application dependent/specific data without any help of the mentioned MQTT properties.

If the MQTTX client-broker connection is configured to use V5, I would expect the client to use such "helpers" to support other clients work.

You MQTX client is not the only client not using the payload format indicator and even those clients offer the customer to chose a format of the data to be posted/published, but not delivering the corresponding MQTT properties with the PUBLISH packets.

If it is e.g. about IoT communication, published messages,  do not expect a listinging client to be generic, so that the client should know the application specific data format to react on!
But in an interactive environment used e.g. for testing, … why not using the available MQTT features?

**Comment by ysfscream** [comment]
Hi, thanks to open the issue. We will discuss this in the discussion forum. I will close this issue.

https://github.com/emqx/MQTTX/discussions/634
