### ISSUE TITLE
[Bug] While downloading the MQTTX setup file for Windows, Microsoft Defender shows it as a potentially malicious file

### ISSUE THREAD

**Issue by nrd26** [emqx/MQTTX#643]
#### What did I do

Tried to download the MQTTX setup file for Windows

#### What happened

Microsoft Defender shows that it's a malicious file

#### Expected

It shouldn't be a malicious file

#### Environment

- OS: Windows 10
- MQTTX version v1.6.0

#### More detail

![Screenshot 2021-07-28 104542](https://user-images.githubusercontent.com/58399987/127267609-57399906-e73f-459f-a169-c7da5bcd4774.png)

Here's what Microsoft Defender considers as malicious files:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview

**Comment by oceanlvr** [comment]
@nrd26 Yes, we should offer `MQTT X` to Microsoft for review, it's OK, not enough I don't think it's necessary.

Thank you for your suggestion
