### ISSUE TITLE
[Feature] Please add arm64 build

### ISSUE THREAD

**Issue by m-ueberall** [emqx/MQTTX#653]
#### Motivation

While [emqx](https://github.com/emqx/emqx) builds are already available for arm64, [MQTTX](https://github.com/emqx/MQTTX) builds aren't yet (which is a bit unfortunate for users of arm64 desktop machines).

**Comment by ysfscream** [comment]
@m-ueberall Hi. Thanks for your suggestion, for now only the macOS version supports arm64, we continue to optimize the platform support later.

**Comment by ysfscream** [comment]
Hi! Sorry to come back to you after a long time, currently https://github.com/emqx/MQTTX/releases/tag/v1.7.2 has added more arm builds. Thank you for your suggestions and usage.
