### ISSUE TITLE
[Feature] Log of the subscribed topic

### ISSUE THREAD

**Issue by sushant-ht** [emqx/MQTTX#664]
#### Motivation

Log of the subscribed topic 

#### Detailed design

Kindly add a logging feature, where user can log the incoming data when subscribed to any topic and save logged data in txt or any file format with received timestamp and JSON/ received packet. It will help in analysing the packet like energy meter data or something.

#### Alternatives

Describe alternatives you've considered, what other designs have been considered? What is the impact of not doing this?

**Comment by ysfscream** [comment]
Hi, thanks for your feedback. Could you please give a specific example? Sorry, I still don't actually understand too well, the logs are there if you need to record the subscriptions, and if you want to export the data, it's available on the settings page.
