### ISSUE TITLE
[Bug] Typesetting characters overlap.

### ISSUE THREAD

**Issue by JimMoen** [emqx/MQTTX#674]
### What did I do

Click "新建连接" in main Tab.
![mqttx_issue_main_tab](https://user-images.githubusercontent.com/32241529/131658728-5e9e4cfe-c65b-4df3-bf1d-cdb8fbbb35ea.png)

### What happened

**Typesetting characters overlap.**

![mqttx_issue](https://user-images.githubusercontent.com/32241529/131658309-00e0c05e-5942-41b6-b4c1-e7bab787570a.png)

### Environment

- OS: ArchLinux, MQTTX Installed From [AUR. mqttx-bin](https://aur.archlinux.org/packages/mqttx-bin/)
- MQTTX 1.6.0
- Most fonts are mandatory to _"Sarasa Mono SC"_ in _"~/.config/fontconfig/fonts.conf"_ for Chinese ENV

**Comment by ysfscream** [comment]
@JimMoen Hi! It's weird that this problem appears on your operating system, I tested it on other operating systems, maybe it's related to fonts, let's check it out.

**Comment by JimMoen** [comment]
Thanks.
BTW, It's ok on MacOS(form homebrew).
So it may casued by fonts setting on my local.

**Comment by ysfscream** [comment]
If there is no problem, I will close this issue.
