### ISSUE TITLE
[Feature] Subscribe Flags

### ISSUE THREAD

**Issue by JimMoen** [emqx/MQTTX#688]
#### Motivation

It seems doesn't have any subscribe flag setting except `QoS` via `mqtt-v5.0` ?

#### Detailed design

The subscribe flags `Retain Handling`, `Retain as Published` and `No Local` can't be setting by user.

#### Alternatives

The falgs could be setting at the `Add Subscribe` Card. The unsupported falgs can't be setting while the protocal version is high.(With Comment)

**Comment by ysfscream** [comment]
Thank you, but not yet support, will support in the next.

**Comment by oceanlvr** [comment]
@JimMoen Hi, sorry for supporting this feature so late, we may release update next version.

**Comment by ysfscream** [comment]
Now we support these properties on https://github.com/emqx/MQTTX/releases/tag/v1.7.0

Thanks for your feedback!
