### ISSUE TITLE
[Bug] Compatibility issues with the sqlite package on apple M1 

### ISSUE THREAD

**Issue by Wster11** [emqx/MQTTX#690]
#### What happened
 node版本： v14.17.6
 
报错如下：
Launching Electron...
(node:82093) ExtensionLoadWarning: Warnings loading extension at /Users/zhaoliang/Library/Application Support/MQTTX/extensions/nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
(node:82093) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/error/DriverPackageNotInstalledError.js:11:28)
    at SqliteDriver.loadDependencies (/Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/driver/sqlite/SqliteDriver.js:128:19)
    at new SqliteDriver (/Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/driver/sqlite/SqliteDriver.js:29:15)
    at DriverFactory.create (/Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/driver/DriverFactory.js:45:24)
    at new Connection (/Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/connection/Connection.js:54:59)
    at ConnectionManager.create (/Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/connection/ConnectionManager.js:57:26)
    at /Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/index.js:219:66
    at step (/Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at /Users/zhaoliang/Desktop/work/MQTTX/node_modules/typeorm/node_modules/tslib/tslib.js:117:75
(node:82093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:82093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

#### Environment

- OS: MacBook Pro (13-inch, M1, 2020)  version: 11.4  Chip: Apple M1
- MQTTX version master

**Comment by oceanlvr** [comment]
I'm glad you chose to use MQTT X.
In the next release, we introduced sqlite3.(current master branch)
I think the reason for the problem is that the M1 chip doesn't support the sqlite3 package at the moment, I don't have an M1 chip Mac in my hand, and I'll try to find out the next answer in the community, and we'll keep this issue for the time being

**Comment by oceanlvr** [comment]
reference https://github.com/mapbox/node-sqlite3/issues/903

**Comment by ysfscream** [comment]
We have updated the SQLite dependencies so that the main branch can now be built on apple m1, you can try it again. Thanks.

**Comment by starplatinum3** [comment]
I also have this problem, but I'm not Apple M1
Equipment name  LAPTOP-1M8KR3GR
Processor 11th Gen Intel (R) core (TM) i5-11320h @ 3.20ghz 3.19 GHz
Machine ram 16.0 GB (15.8 GB available)
System type： 64 bit operating system, x64 based processor
Pen and touch： no pen or touch input available for this display

我也是这个问题，但是我并不是苹果M1
设备名称        LAPTOP-1M8KR3GR
处理器        11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz   3.19 GHz
机带 RAM        16.0 GB (15.8 GB 可用)
系统类型        64 位操作系统, 基于 x64 的处理器
笔和触控        没有可用于此显示器的笔或触控输入
