### ISSUE TITLE
[Bug] connect wss:// failed

### ISSUE THREAD

**Issue by JaosnHsieh** [emqx/MQTTX#721]
#### What did I do

connect to my broker via `wss://` protocol.

#### What happened

Get an error.

#### Expected

Connected successfully.

#### Environment

- OS: MacOS Big Sur 11.2
- MQTTX version, e.g. v1.6.0

#### More detail

this bug is in electron and has been fixed in newer verison. check [here](https://github.com/electron/electron/issues/31212)

**Comment by oceanlvr** [comment]
https://github.com/electron/electron/issues/31212#issuecomment-931641110

Could you please tell us more detail to reproduce？

Thanks for your feedback.

**Comment by JaosnHsieh** [comment]
> [electron/electron#31212 (comment)](https://github.com/electron/electron/issues/31212#issuecomment-931641110)
> 
> Could you please tell us more detail to reproduce？
> 
> Thanks for your feedback.

1. run a mqtt broker suppots `ws` on port `8888`, I use [aedes](https://github.com/moscajs/aedes/blob/main/docs/Examples.md#mqtt-server-over-websocket-using-server-factory)

2. use [Caddy](https://caddyserver.com/) as `wss://` reverse proxy.  I think any default certificate from [certbot](https://certbot.eff.org/) would work. 

/etc/caddy/Caddyfile
```
api.example.com:80 {
        reverse_proxy localhost:1337
}
api.example.com:443 {
        reverse_proxy localhost:1337
        
}
broker.example.com:8989 {
        reverse_proxy localhost:8888
}
```

3. use `mqttx` client. Now it can connect to `ws://broker.example.com:8888` but failed to connect to `wss://broker.example.com:8989`

4. `$ systemctl stop caddy` stop caddy 

5. `$ rm -rf /var/lib/caddy/.local/share` removes ssl certificates saved by `Caddy` 

6. change `/etc/caddy/Caddyfile` with different chain. refers to [here](https://github.com/electron/electron/issues/31212#issuecomment-931552257)

/etc/caddy/Caddyfile
```
api.example.com:80 {
        reverse_proxy localhost:1337
        tls {
        issuer acme {
            preferred_chains {
                root_common_name "ISRG Root X1"
            }
        }
    }
}
api.example.com:443 {
        reverse_proxy localhost:1337
        tls {
        issuer acme {
            preferred_chains {
                root_common_name "ISRG Root X1"
            }
        }
    }
        
}
broker.example.com:8989 {
        reverse_proxy localhost:8888
        tls {
        issuer acme {
            preferred_chains {
                root_common_name "ISRG Root X1"
            }
        }
    }
}
```

7. connect it with `mqttx` with `wss://` again, should work. if it didn't work, check caddy's logs. `$ systemctl status caddy`. It might not get the certificate correctly.

**Comment by oceanlvr** [comment]
It seems that we just upgrade electron would fix this issue, I'll reproduce this problem.
Thanks for letting me know.

**Comment by ysfscream** [comment]
This issue is maybe fixed on https://github.com/emqx/MQTTX/releases/tag/v1.7.0
