### ISSUE TITLE
Topic Alias don't show typed text

### ISSUE THREAD

**Issue by programmer131** [emqx/MQTTX#725]
when adding new topic, I tried to use Alias but it don't show typed text in front of Alias but text appears once topic is added, that means it takes affect but do not show up while adding new topic. issue isn't specific to v1.6.1, I also noticed it in previous versions but few times only.

#### Environment

- OS: win 10
- MQTTX version, v1.6.1

**Comment by oceanlvr** [comment]
@programmer131 Hi, we release v.1.6.2 please try the latest version.

https://github.com/emqx/MQTTX/releases

May fix this issue, waiting for your reply. :)
