### ISSUE TITLE
[Feature] Expose MQTT 5.0 properties on received messages

### ISSUE THREAD

**Issue by aaron-613** [emqx/MQTTX#727]
#### Motivation

There are very few public GUI MQTT 5.0 clients, this is a very nice one.  However, it appears to just _use_ an MQTT 5.0 library, but doesn't expose any additional functionality over MQTT 3.1  It would be GREAT to see various 5.0 properties/metadata that are available in received messages... either in the GUI, or via the logs / debug console.

#### Detailed design

When receiving a message via `client.on('message', function (topic, message, packet) {`  , which is specified in method `onMessageArrived` in views/connections/ConnectionsDetail.vue, line 1051... very little of the "packet" variable is used.  Only a small portion of the map is extrapolated, and stored in some data structure called `SubscriptionModel`: topic, qos, and optional alias, retain bit, and colour.  Similarly, the standard message bits and pieces are extracted and stored in the type `MessageModel` (line 156 of types/global.d.ts), specifically:

```
  interface MessageModel {
    id?: string
    createAt: string
    out: boolean
    payload: string
    qos: QoS
    retain: boolean
    topic: string
    color?: string
  }
```

In the MQTT.js library, the message object/packet you get from the broker has a bunch of cool 5.0 stuff:  (https://github.com/mqttjs/mqtt-packet#publish)
```
{
  cmd: 'publish',
  messageId: 42,
  qos: 2,
  dup: false,
  topic: 'test',
  payload: Buffer.from('test'),
  retain: false,
  properties: { // optional properties MQTT 5.0           <------------- new in 5.0
      payloadFormatIndicator: true,
      messageExpiryInterval: 4321,
      topicAlias: 100,
      responseTopic: 'topic',
      correlationData: Buffer.from([1, 2, 3, 4]),      <---- useful!
      userProperties: {                           <---- very useful!!
        'test': 'test'
      },
      subscriptionIdentifier: 120, // can be an Array in message from broker, if message included in few another subscriptions
      contentType: 'test'
   }
}
```

It would be great if this additional metadata and user properties are displayed or at least visible somewhere..?

Thank you!!

**Comment by ysfscream** [comment]
@aaron-613 Hey! 👋

Thank you for your super careful explanation and suggestions, I find your suggestions very useful and we will implement them in future versions.

**Comment by aaron-613** [comment]
Hello @ysfscream and @oceanlvr ..!  Thank you for the responses, and apologies for the delayed reply.

That is super excellent to hear that you plan to support the new MQTT 5.0 properties / metadata.  I was planning to try to hack/update the code myself, just to see if I could get it working, but I do not know JS that well.

I'm really excited to try this when it's available... as far as I know, you're the only open-source project that specifically would support 5.0 functionality.  I used to use Eclipse Paho JS utility (now gone: https://www.eclipse.org/paho/clients/js/utility ) but that was only 3.1.1, and also the HiveMQ test client is ok (http://www.hivemq.com/demos/websocket-client/) (also only 3.1), but yours is much prettier and if you have this additional 5.0 capability that would be a game changer.

Please let me know if there's anything I can do to help.  I work for a company called Solace and our broker supports MQTT 5.0.  I'm sure some of our field team would be happy to test this and maybe share with customers.  👍🏼

**Comment by oceanlvr** [comment]
@aaron-613 

Thank you for your support, we are now in the step-by-step combing and design of the`MQTT5` attributes that need to be supported, and we can build a design discussion about MQTT5 before we release it, and we are happy to receive feedback from users.

**Comment by ysfscream** [comment]
Hey! We are excited about the release of https://github.com/emqx/MQTTX/releases/tag/v1.7.0, which supports adding and displaying User Properties, and more. Thanks and welcome to download.
