### ISSUE TITLE
Icons in leftbar do not show tooltips

### ISSUE THREAD

**Issue by JanOonk** [emqx/MQTTX#731]
#### Motivation

Currently when you hover with the mouse over the icons in the leftbar for example connections, new connection, script, log, about or settings it doesn't display a tooltip. Only after clicking you will know to what screen it leads. I think it's more user friendly to show a tooltip with a description to what screen it leads.

**Comment by ysfscream** [comment]
Sorry, I don't think the tooltip display on the menu bar icon fits our design, although it's a good suggestion, thanks!
