### ISSUE TITLE
Form is empty when editing connection

### ISSUE THREAD

**Issue by JanOonk** [emqx/MQTTX#733]
#### What did I do

Make a new connection, fill in the field and press connect. Disconnect and and edit it by using the pencil top right (see 1). The fields are not filled with the connection values I used (not shown in screenshot because it's basically just the new connection screen).
Although when using the green dropdown (see 2) after connectionname you do see some values... but not all! You also can't see the advanced fields and last will and testament.

#### What happened

No, just empty fields or with default values.

#### Expected

The fields should have been loaded with the connection settings I used when creating it.

#### Environment

Windows 10

#### More detail
![mqtx](https://user-images.githubusercontent.com/13236774/136763204-8b9d34c6-27ac-4973-9149-a4be755b3d33.jpg)

**Comment by oceanlvr** [comment]
That's bad, I have reproduced. Start fixing it.

**Comment by ysfscream** [comment]
This issue is fixed on https://github.com/emqx/MQTTX/releases/tag/v1.7.0

Thanks for your feedback!
