### ISSUE TITLE
Inconsistent naming edit connection vs advanced config

### ISSUE THREAD

**Issue by JanOonk** [emqx/MQTTX#734]
When you created a new connection using + and want to edit it afterwards the pencil top right shows a inconsistent tooltip 'advanced config'. You would expect it to be named 'edit connection'.

**Comment by oceanlvr** [comment]
I have renamed it, THANKS !! @JanOonk :)

**Comment by ysfscream** [comment]
This issue is fixed on https://github.com/emqx/MQTTX/releases/tag/v1.7.0 Thanks!
