### ISSUE TITLE
Add save button for new connection

### ISSUE THREAD

**Issue by JannemanDev** [emqx/MQTTX#735]
#### Motivation

When you want to make a new connection and fill in some (but not necessarly all) fields you can't temporailty save it and  complement it later on. You can only choose Connect which is not always what you want.

Suggestion: add a save button next to connect.

**Comment by GuryYu** [comment]
And edit connection needs save button too.

**Comment by ysfscream** [comment]
Thanks for your feedback. It is now available at: https://github.com/emqx/MQTTX/releases/tag/v1.9.10. Welcome to try it.
