### ISSUE TITLE
Add duplicate connection feature

### ISSUE THREAD

**Issue by JannemanDev** [emqx/MQTTX#736]
#### Motivation

Often you want to make a new connection based off an existing one.

Suggestion: add a 'Duplicate' button to the right mouse click menu on a existing connection.

![new feature](https://user-images.githubusercontent.com/13236774/136764815-338e9cd0-372a-41b2-8926-4247b539daf9.jpg)

**Comment by ysfscream** [comment]
@JannemanDev Hi, thanks for your advance. This is very useful and has now been implemented at https://github.com/emqx/MQTTX/releases/tag/v1.8.0
