### ISSUE TITLE
Add ability to disable subscription instead of having it to delete

### ISSUE THREAD

**Issue by JanOonk** [emqx/MQTTX#741]
#### Motivation

Sometimes you want to temporarily disable one of your subscriptions for a connection. But they only way to do this is to delete it.

Suggestion: add disable option for example under the right mouse click of the subscription

**Comment by oceanlvr** [comment]
Yes, we may support disable the subscribe, great idea!
THANKS @JanOonk

**Comment by ysfscream** [comment]
Thanks for your suggestion. In https://github.com/emqx/MQTTX/releases/tag/v1.7.1 already support.
