### ISSUE TITLE
[Help Wanted] MQTTX-1.6.2 UI freeze & crush down issue

### ISSUE THREAD

**Issue by xshiyun** [emqx/MQTTX#749]
#### MQTTX-1.6.2 UI freeze & crush down issue

MQTTX-1.6.2.dmg 很卡

Click on the interface to get stuck, and then back to 1.6.0
界面上点击鼠标卡死，又换回1.6.0了

**Comment by programmer131** [comment]
same issue, even after clear history, hanging after every few seconds
![image](https://user-images.githubusercontent.com/12946496/141958317-b3c3fe7e-5a83-4871-b3b2-6499ef28630b.png)

**Comment by kukudemajia** [comment]
我也碰到了同样的问题,

**Comment by programmer131** [comment]
clear history feature isn't functional on windows 10, always around 5000 messages appear from history after mqtt connection is opened and keeps MQTTX hanging.

**Comment by oceanlvr** [comment]
@programmer131 

Have you upgraded to the latest version?

**Comment by culmencasa** [comment]
> @programmer131
> 
> Have you upgraded to the latest version?

go back to V1.6.0 i think would be the easiest way
