### ISSUE TITLE
[Bug] Retain message flashes problem when reconnecting

### ISSUE THREAD

**Issue by oceanlvr** [emqx/MQTTX#750]
#### What did I do

Retain message flashes problem when reconnecting.

https://user-images.githubusercontent.com/36698124/138407157-8605f737-69f5-4ad4-8510-9e1d2f402fd6.mp4

#### What happened

Get an error.

#### Environment

- OS: OS version, e.g. MacOS Big Sur 11.1
- MQTTX version, e.g. v1.5.0

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Fixed on https://github.com/emqx/MQTTX/releases/tag/v1.7.0
