### ISSUE TITLE
[Feature] Enable/Disable Auto-scroll

### ISSUE THREAD

**Issue by z01ne** [emqx/MQTTX#754]
#### Motivation

When there is a high rate of incoming data, I need to disconnect to review the messages then reconnect.

#### Detailed design

When you scroll to the last message enable auto-scroll, else disable it.

#### Alternatives

Make a switch button.

**Comment by ysfscream** [comment]
This feature is implemented on https://github.com/emqx/MQTTX/releases/tag/v1.7.0

Thanks for your suggestion, welcome to download.
