### ISSUE TITLE
[Feature] MQTT 5.0 Payload format indicator

### ISSUE THREAD

**Issue by MartinL0815** [emqx/MQTTX#764]
#### Motivation

MQTT v5 allows to distinguish between application specific and textual (UTF-8) data.
MQTTX does not allow to differentiate between this two payload formats, which can be signaled using payload format indicator in the MQTT properties sent with a PUBLISH packet.

#### Detailed design

In the UI there could be an additional check button indicating to send text or application specific data (binary).
To keep the current behavior, the check button would be unchecked, since MQTTX sent all data as application specific in the past.

If the user decides to send data in a specific format like plaintext or json the checked payload indicator check button would set the payload format indicator to 1.
Since the textual data is already sent in UTF-8 encoding, this would even make sense to be the default.

If the user decides to send base64 encoded data, the unchecked check button would allow the user to send those base64 encoded data as binary (decoded) with the payload format indicator set to zero, indicating "application specific" or binary data.
Otherwise the base64 data is sent as text and signal its format using the payload format indicator set to 1.

#### Alternatives

The payload format could be related to a specific topic, since data sent to a topic won't change its format easily, no matter which data is sent in what ever format.

**Comment by oceanlvr** [comment]
related discussions: https://github.com/emqx/MQTTX/discussions/634

**Comment by ysfscream** [comment]
Hey! We are excited about the release of v1.7.0 (release), which supports setting the Payload Format Indicator and content type. Thanks and welcome to download.
