### ISSUE TITLE
[Bug] Payload transform issue

### ISSUE THREAD

**Issue by MartinL0815** [emqx/MQTTX#765]
#### What did I do

I had three Chinese characters in the text box:

> 一个人

I tried to switch the format to Base64.

#### What happened

MQTTX didn't respond anymore.

#### Expected

Encoded Base64 data like (if those characters are UTF-8 encoded): 5LiA5Liq5Lq6

#### Environment

- OS: MS Windows 10 Enterprise Edition, Version 10.0.18363 Build 18363

- MQTTX version, e.g. v1.6.2

#### More detail

More detail include `log` information or screenshot:

> ![Hanging MQTTX](https://user-images.githubusercontent.com/525700/139669710-11d79e3e-998d-41b9-af0d-d821c92bc262.png)

**Comment by oceanlvr** [comment]
@MartinL0815   Hello, I have reproduced this problem, thank you for your feedback, we will fix it as soon as possible

**Comment by ysfscream** [comment]
This issue is fixed on https://github.com/emqx/MQTTX/releases/tag/v1.7.0

Thanks for your feedback!
