### ISSUE TITLE
[Bug] Editing an existing connection does not show the existing configuration, but is more like adding

### ISSUE THREAD

**Issue by linG5821** [emqx/MQTTX#766]
#### What did I do

当我点击高级配置编辑某个连接时不会回显数据,

#### What happened

编辑现有连接无法回显数据

#### Expected

应该回显现有连接的信息

#### Environment

- OS: Windows 10
- MQTTX version: v1.6.2

#### More detail

无

**Comment by zhanghuanchong** [comment]
Still has this bug in the latest version v1.6.2.

**Comment by ysfscream** [comment]
This issue is fixed on https://github.com/emqx/MQTTX/releases/tag/v1.7.0
