### ISSUE TITLE
[Bug] MQTTX 1.6.2 universal.dmg 安装后，启动无反应

### ISSUE THREAD

**Issue by dengyumin** [emqx/MQTTX#787]
#### What happened

通过 **MQTTX 1.6.2 universal.dmg** 安装后，启动无反应

#### Environment

- MacBook Air (M1, 2020)   **macOS Big Sur 11.2.3**
- MQTTX version, e.g. v1.5.0

#### More detail

最后通过 AppStore 安装运行成功

**Comment by oceanlvr** [comment]
原因是目前 node-sqlite 没有 M1 版本的二进制打包 

https://github.com/emqx/MQTTX/issues/690

**Comment by dengyumin** [comment]
好的，感谢:smile:

**Comment by oceanlvr** [comment]
不客气
