### ISSUE TITLE
[Bug] connections is empty when open MQTTX

### ISSUE THREAD

**Issue by alibbbian** [emqx/MQTTX#819]
#### What did I do

connections is empty when open MQTTX, and pop-up window with tips "Update to xxxx.xxx.xxx"

#### What happened

Get an error.

#### Expected

What is the expected result.

#### Environment

- Microsoft Windows 10 10.0.19043  x64-based PC
- MQTTX.Setup.1.6.0.exe

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Hi @alibbbian We just released https://github.com/emqx/MQTTX/releases/tag/v1.7.0, so we will prompt you to upgrade. If you don't need it, click Cancel and cancel the automatic check update in settings page.
