### ISSUE TITLE
[Bug] Location of application icon in v1.7.0 deb seems to be wrong

### ISSUE THREAD

**Issue by lidanger** [emqx/MQTTX#821]
Today, I installed v1.7.0 deb in deepin, then I found it dit not display correct in launcher.No icon was there.

I extracted the deb file, and found the icon file is located in /usr/share/icons/hicolor/0x0/apps.While I move it into /usr/share/icons/hicolor/512x512/apps, the application icon went well.

So, is it be a packaging mistake?

**Comment by ysfscream** [comment]
Hi! Thanks for your feedback! But I have no Deepin System, Could you please provide the screenshot or let me know how about the icon display before the 1.7.0.

**Comment by lidanger** [comment]
> Hi! Thanks for your feedback! But I have no Deepin System, Could you please provide the screenshot or let me know how about the icon display before the 1.7.0.

It remains in v1.7.1.Replay it like this:

![截图_deepin-terminal_20220116110315](https://user-images.githubusercontent.com/4464921/149645777-4ceb0f01-534e-407c-b386-bdfe4b81693a.png)

In deepin 20, the desktop file on desktop or launcher displays no icon.

![截图_选择区域_20220116110730](https://user-images.githubusercontent.com/4464921/149645792-93efd413-078a-42f9-918d-1a61d20f3bff.png)

**Comment by ysfscream** [comment]
Could you please install the AppImage file? or use download on https://flathub.org/apps/details/com.emqx.MQTTX?
