### ISSUE TITLE
[Help] 1.6.2->1.7版本升级后以前的连接只剩下文件夹了，内部的连接都空了

### ISSUE THREAD

**Issue by zhb0110** [emqx/MQTTX#823]
#### Describe the problem you Confuse

刚刚1.6.2升级1.7版本，以前的连接只剩下文件夹了，内部的连接都空了，如果格式变化，请在升级时说明下，不然没有备份

#### More detail (optional)
![image](https://user-images.githubusercontent.com/31426441/145791144-2cbd704a-5119-4abf-8fb7-8161533bc06f.png)

**Comment by ysfscream** [comment]
We are so sorry about that. It could be that we were fixing a bug that brought about a change in the data structure, but we didn't notice and test it. So there is no note about possible data loss. Maybe the data is still there, but there is no way to display it, try to export and delete the current data, and then import to see if the data could be recovered.

对此，我们感到非常抱歉。可能是我们在修复一个 BUG 时，带来的数据结构的修改，但是我们没有注意和测试到。所以没有备注可能会数据丢失的问题。或许数据还是在的，但是没有办法显示出来，尝试导出数据并删除当前数据，再导入看下能否恢复数据。

**Comment by zhb0110** [comment]
> 
无法导出当前数据，显示“暂无数据”。

**Comment by ysfscream** [comment]
Sorry again. We will pay attention to this issue in future tests, and I will close this issue.
