### ISSUE TITLE
[Feature] Support MQTT 5 Subscription Identifier

### ISSUE THREAD

**Issue by BlackOfMing** [emqx/MQTTX#828]
#### Motivation

I hope that the plan supports the Publication and Subscription of Subscription Identifier.

#### Detailed design

When create a new subscription, user can add a subscription identifier.  And you can see the subscription identifier in the text box of the received message.

#### Alternatives

No alternatives for Subscription Identifier.

**Comment by ysfscream** [comment]
Hello! @BlackOfMing Thanks for your suggestion. In fact, the Subscription Identifier is already supported, Please see PR: https://github.com/emqx/MQTTX/pull/824

It will be available in the next version v1.7.1
