### ISSUE TITLE
no connection: ECONNREFUSED

### ISSUE THREAD

**Issue by geieraffe** [emqx/MQTTX#830]
So Hi,

my problem is I can't get an connection 😄 
ok, I found the log, but unfortunately it doesn't give me more information then:
`[2021-12-16 19:19:35] [ERROR] Connect fail, MQTT.js onError trigger, Error: connect ECONNREFUSED 192.168.2.50:1883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)`

Is there some detailed log somewhere?
I'm sure the MQTT service is running on the local machine, because can send and receive topics over there.

Any Idea?

**Comment by ysfscream** [comment]
Hi! @geieraffe Thanks for using. Maybe this error message `Error: connect ECONNREFUSED` is already the only one the client can get.
However, the general cause of this error is most likely that the MQTT Broker cannot be connected. Because the MQTT Broker is not running.
Please check your IP address first. If you are sure the service is local, try using `localhost:1883` or `127.0.0.1:1883` to connect.

**Comment by geieraffe** [comment]
> However, the general cause of this error is most likely that the MQTT Broker cannot be connected. Because the MQTT Broker is not running.
> 
> Please check your IP address first. If you are sure the service is local, try using `localhost:1883` or `127.0.0.1:1883` to connect.

Ok, thanks. I was almost afraid of that.

I know that the MQTT broker runs correctly because I have it running on a raspberry. There I can also send and receive messages via the localhost.

But not on my desktop.
But the connection must be generally ok. I can connect via SSH etc.
The port is not blocked according to the firewall.

is there a way to check if Windows specifically blocks the connection of this program?

**Comment by ysfscream** [comment]
Sorry about that, I'm not too familiar with windows, but it should be a network connection problem.

What is your MQTT Broker? If it's the EMQ X, you might want to visit the Dashboard in your browser first: `${IP}: 18083`

**Comment by ysfscream** [comment]
Happy for you!
