### ISSUE TITLE
[Feature] need ipv6 support

### ISSUE THREAD

**Issue by cjoin** [emqx/MQTTX#849]
### Motivation

mqttx needs to support ipv6 domain name or ipv6 address
mqttx需要支持ipv6域名或者ipv6地址

#### Detailed design
When I enter a domain name that only has AAAA resolution, or enter a pure ipv6 address, I hope that the connection can be successful
当我输入一个只有AAAA解析的域名时，或者输入一个单纯的ipv6地址，期望可以连接成功

#### More detail (optional)

![image](https://user-images.githubusercontent.com/9362314/147347894-dd01d13e-96ad-4b29-9120-5a3dbc66ffea.png)

**Comment by cjoin** [comment]
sorry，mqttx is support ipv6. this error is my  emqx conf error.
this is error conf：listener.tcp.ipv6 = ::1:1883
this is right conf：listener.tcp.ipv6 = ::0:1883

**Comment by ysfscream** [comment]
Happy for your :)
