### ISSUE TITLE
[Feature] Inappropriate message box layout

### ISSUE THREAD

**Issue by hityb** [emqx/MQTTX#860]
#### Motivation

在收发mqtt消息的时候，消息会在一定长度换行，屏幕空间利用不足，

#### Detailed design

选择纯文本内容的时候，目前是收到的消息放在左面，发送的消息放在右面。希望在现实无格式内容（非json）的时候，消息能占满一行再换行，充分利用屏幕。
![image](https://user-images.githubusercontent.com/58910855/148017425-2071f733-2081-42ac-b513-344d32a4bcc0.png)

**Comment by ysfscream** [comment]
@hityb This is indeed a problem worth optimizing. Thanks!

**Comment by ysfscream** [comment]
We have done some optimization according to your suggestions, but not optimized to the best, we will continue to optimize the display UI part. Thanks!
