### ISSUE TITLE
[Bug] Message windows does not scale if MQTTX is fullscreen

### ISSUE THREAD

**Issue by tbird2020** [emqx/MQTTX#871]
Hei guys, 

i am sure this is an easy one ... i've got a pivot monitor to hold all the vertical-scrolling stuff like your MQTTX app. 

However, the app does not make usage of the extra vertical space, see here (sorry i had to blur some parts of the screen due to confidential stuff...): 

![image](https://user-images.githubusercontent.com/77832962/149885058-10b819cf-e89d-4bbb-acd0-1a26cfd57f11.png)

**Comment by ysfscream** [comment]
Hi, thank you for your feedback. I will test and verify, If it's a bug, we'll fix it soon. But you can try refreshing this page, or adjusting the height of the input box below.

**Comment by ysfscream** [comment]
I don't know if this issue is still there, we just released https://github.com/emqx/MQTTX/releases/tag/v1.7.2 If there are problems then reopen this issue Thanks!
