### ISSUE TITLE
[Bug] testtopic/# appear instead of subscribed topic

### ISSUE THREAD

**Issue by programmer131** [emqx/MQTTX#875]
#### What did I do

subscribed a new topic and added Alias as well

#### What happened

topic actually got subscribed in background, but MQTTX shows testtopic/# as newly added topic, and the one I added do not show up, but i see messages coming on that topic when I de-select testtopic 
#### Expected

it should show Alias in subscription windows, and not testtopic

#### Environment

- OS: win 10
- MQTTX version 1.7.1

#### More detail

![image](https://user-images.githubusercontent.com/12946496/150255157-66525fa4-4447-4e1e-9a83-5240e47916c8.png)

after sometime, that testtopic auto disappeared and now it shows correct topic that I subscribed, after I clicked info button to check version.

**Comment by ysfscream** [comment]
@programmer131 Hi, thanks for your feedback! Maybe it is a duplicate with #874 

Could you please update it to https://github.com/emqx/MQTTX/releases/tag/v1.7.2 to try?
