### ISSUE TITLE
[Feature] collapsable connections pane

### ISSUE THREAD

**Issue by garysb** [emqx/MQTTX#883]
#### Motivation

Provide the ability to collapse the connections pane as once connected, its wasted screen real-estate.

#### Detailed design

Once the connection is made, the connections pane stays open and has no way of collapsing / minimising it. It would be really handy to be able to reduce the nearly empty pane. This would allow me to focus on the content itself. Using a similar solution to the way the subscriptions pane can be expanded / contracted would suffice.

#### Alternatives

An alternative would be to allow the icon on the left (the two overlapping squares) to be clicked again to collapse the connections pane.

**Comment by ysfscream** [comment]
Sorry for my late reply, I was on vacation recently. What is a little unclear to me is which connections pane you want to collapse? Because MQTT X will still collapse the top content after a successful connection.

Maybe you can let me know through screenshots.

**Comment by garysb** [comment]
@ysfscream, no need to be sorry, hope you had a great vacation.

The connection details pane expands and contracts down from the top as you mentioned, but down the left had side, there is a connections list that can not be collapsed (it has the Title "connections" and the "New Connection" outline button (I think its ConnectionsList.vue in the code).


![Screenshot 2022-02-09 at 07 32 53](https://user-images.githubusercontent.com/292283/153135014-a1cf3663-2d77-47f8-8823-4707c2ba9f73.png)

**Comment by ysfscream** [comment]
Thanks for your feedback and detailed description of the issue.

But this pane I do not think it is necessary to collapse it on the connection after. Because I think this is part of the content display in the main window, not too willing to hide the content, imagine IM software, but I will still optimize here, at least the width of the connection list can be manually adjusted. Like this design: https://github.com/emqx/MQTTX/issues/505

**Comment by afeurra** [comment]
Upvoting this.
I often use MQTTX to debug my main MQTT-based app and to do so I split my screen in half. A big portion of the MQTTX half is filled with the connections list, which I don't need to watch.

Please think about this.

**Comment by ysfscream** [comment]
Sorry for waiting for a long time, and thanks for the feedback. Try the https://github.com/emqx/MQTTX/releases/tag/v1.9.9
