### ISSUE TITLE
[Bug] latest.yml is missing the hash codes of all exe files

### ISSUE THREAD

**Issue by Vixb1122** [emqx/MQTTX#895]
#### What did I do

I wan't to get hash code for [MQTTX-Setup-1.7.2-x64.exe](https://github.com/emqx/MQTTX/releases/download/v1.7.2/MQTTX-Setup-1.7.2-x64.exe) and [MQTTX-Setup-1.7.2-ia32.exe](https://github.com/emqx/MQTTX/releases/download/v1.7.2/MQTTX-Setup-1.7.2-ia32.exe) from [latest.yml](https://github.com/emqx/MQTTX/releases/download/v1.7.2/latest.yml)

#### What happened

No way.

#### Expected

List hash code for all exe files.

**Comment by ysfscream** [comment]
Sorry about that, I'll upload it later.

**Comment by ysfscream** [comment]
Please re-download it again! Thanks.

**Comment by Vixb1122** [comment]
Good Job!
