### ISSUE TITLE
[Feature] Send mqtt message in script

### ISSUE THREAD

**Issue by bekicot** [emqx/MQTTX#896]
#### Motivation

With this feature, allow mqttx to mock how the actual device response to a server request. 

#### Detailed design
Consider this example:
- Client subscribe to: `humidityRequest`
- Client received: `humidityRequest`
- Script parse the body and send feedback
	
```
function handlePayload(value) {
	  sendMessage(`humidity`, { timestamp: "", value: 1212 })
	  return(value)
}

execute(handlePayload)
```

#### Alternatives

No alternative.

**Comment by ysfscream** [comment]
Duplicate of #776 

YES! This is a good idea, but we haven't implemented it yet, sorry, stay tuned for a later version!

**Comment by bekicot** [comment]
Closing this and copy the detailed design as a comment on 776 for consideration.
