### ISSUE TITLE
[Feature] Remember the selected encode/decode type for saving

### ISSUE THREAD

**Issue by beautiful-ppi** [emqx/MQTTX#903]
#### Motivation

![微信截图_20220301143154](https://user-images.githubusercontent.com/45227186/156117348-92430313-2677-4869-b6d8-a52fadc0cf65.png)

1. Record decoding type: restarting \ switching tools will change the default value of plaintext, resulting in other encoded messages will be garbled
2. Dynamic adjustment of the width of the subscription bar: to facilitate a clear view of all subscribed messages

**Comment by ysfscream** [comment]
@beautiful-ppi Thank you for your suggestion, this will really help some, I will optimize in the later versions.

**Comment by alibbbian** [comment]
so many bug, drop it finally

**Comment by ysfscream** [comment]
@alibbbian Thank you for having used.

**Comment by LIN1JIARONG** [comment]
为什么我连接上后，在输入框输入后点击发送，会弹框显示“请输入TOPIC”，明明我已经写明 topic了
![Snipaste_2022-10-16_18-00-30](https://user-images.githubusercontent.com/62559599/196029334-aeb5551f-6a91-42ec-8607-0555d1bcc9db.png)

**Comment by LIN1JIARONG** [comment]
> 为什么我连接上后，在输入框输入后点击发送，会弹框显示“请输入TOPIC”，明明我已经写明 topic了 ![Snipaste_2022-10-16_18-00-30](https://user-images.githubusercontent.com/62559599/196029334-aeb5551f-6a91-42ec-8607-0555d1bcc9db.png)
这个问题解决了。不好意思，topic输错位置了，要输入在 “Topic"栏的。

**Comment by ysfscream** [comment]
@LIN1JIARONG The Topic is input on here.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/21299158/196070764-8334de6b-ea06-4688-acc3-44c24d01aae0.png">

**Comment by ysfscream** [comment]
Thanks for your feedback, now avalible at: https://github.com/emqx/MQTTX/releases/tag/v1.9.10
