### ISSUE TITLE
Not able to install emqx in macbook pro M1 chip 

### ISSUE THREAD

**Issue by thingslinker** [emqx/MQTTX#904]
./bin/emqx start
./bin/emqx: line 39: 45562 Segmentation fault: 11  "$BINDIR/$PROGNAME" -noshell -boot "$REL_DIR/start_clean" -s crypto start -s init stop
FATAL: Unable to start Erlang.
Please make sure openssl-1.1.1 (libcrypto) and libncurses are installed.
Also ensure it's running on the correct platform,
this EMQ X release is built for 24.1.5-3-x86_64-apple-darwin20.6.0-64-macos11

**Comment by ysfscream** [comment]
Yes, EMQX doesn't seem to provide an arm64 build for macOS. Perhaps you could use docker to install.

And it might be more useful to move this issue to emqx: https://github.com/emqx/emqx/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by thingslinker** [comment]
Thanks, worked for me.
