### ISSUE TITLE
[Bug] Unable to receive persistent messages

### ISSUE THREAD

**Issue by error0g** [emqx/MQTTX#907]
背景：

topic | Payload Qos:1
每次设置新会话之前另一个客户端都往topic发新的消息

之前的会话已经把clean seesion，开启持久化。当创建新的会话设置clean seesion设置为true时。当再次建立新会话设置clean seesion设置为false时，重新发送消息无法收到**持久化消息**。之后手动断开重新建立会话clean seesion设置为ture时可以收到消息。

OS:windows10
MQTTX Version: v1.7.2
Server:hiveMQ Windows v1.6

第二次设置clean seesion设置为false时，需要重新修改topic或者重新创建才可以收到新的持久化消息。

错误：
无法收到收到持久化消息

**Comment by oceanlvr** [comment]
路径有点复杂，也许你可以录个视频

**Comment by oceanlvr** [comment]
clean session 之后，topic 订阅列表没正常重订阅。可以看下你的setting里面配置吗？

**Comment by error0g** [comment]
> clean session 之后，topic 订阅列表没正常重订阅。可以看下你的setting里面配置吗？
这是clean session 之后的配置
![图片](https://user-images.githubusercontent.com/30723804/157354046-37b9852a-981e-4d36-bae7-6246ab803bce.png)
![图片](https://user-images.githubusercontent.com/30723804/157354064-d9d2a1e3-c59f-406e-a74b-24678c53b05f.png)
