### ISSUE TITLE
[Bug] The page cannot be displayed under Win10: Incorrect APPDATA Path Used

### ISSUE THREAD

**Issue by fouram** [emqx/MQTTX#909]
#### What did I do

Upgraded from 1.6.0 to 1.7.3

#### What happened

Window shows menu bar but remains blank otherwise. I do see the spinning logo but nothing but white after that. Developer panel will not open.

#### Expected

The program interface is displayed.

#### Environment

- OS: Windows 10 Pro 21H2
- MQTTX version: 1.7.3

#### More detail

![image](https://user-images.githubusercontent.com/533951/157072526-6cdc6a80-f8e1-41ea-9317-b603b3a40fd3.png)

Log only has one line: ```[2022-03-07 11:08:59] [INFO] APP init```

**Comment by ysfscream** [comment]
@fouram Sorry about that. After v1.6.0, we refactored the underlying data storage, there will be some data compatibility issues, such as the disappearance of the previous data.

Maybe you should remove MQTTX completely from your PC, including some cache files, and then try reinstalling it.

If it still doesn't work, roll back to v1.7.2 because I'm not sure if it's a bug from v1.7.3

**Comment by fouram** [comment]
OK, I found the issue - I've got my AppData\Roaming location moved. It's not on the C Drive, but on the D drive. (You can't move Local from the C drive but you can move Roaming). MQTTX is creating a DB in C:\Users\<my account>\AppData\Roaming\MQTTX\MQTTX.db when it starts up.

Replacing MQTTX.db with the copy that the installer places at the correct location allows the client to start successfully.

Windows 7 and up allow changing the location of the AppData\Roaming folder. This is especially important in domain-controlled environments where documents/pictures/Roaming etc might be mounted on smb/cifs shares. The MQTTX application should always read the path from the %APPDATA% environment variable rather than constructing it's own path based on %USERPROFILE%.

**Comment by fouram** [comment]
appdata-path has the following code:

```
function getForWindows() {
  return join(homedir(), "AppData", "Roaming");
}

```
That's a hardcode to a path. What a terrible library, it should be removed from npm.

Use process.env.APPDATA on Windows to get the proper path.

**Comment by ysfscream** [comment]
OK. We are glad that you found this issue and brought us this detailed information. So it's a matter of getting the data on the wrong path, right? Perhaps @oceanlvr can provide more detailed instructions on the use of this library.

**Comment by ysfscream** [comment]
Is this still an issue at the moment? Feel free to use https://github.com/emqx/MQTTX/releases/tag/v1.9.1, I will close the issue first, if it still exists you can reopen it.
