### ISSUE TITLE
[Bug] Self signed certificates need reconfiguring on every app launch?

### ISSUE THREAD

**Issue by elandesign** [emqx/MQTTX#913]
#### What did I do

I'm using MQTTX to connect to AWS' IOT MQTT servers, which require a self-signed TLS certificate for authentication.

#### What happened

I can create the connection and successfully connect, but when I quit and reopen the app, the connection fails with an `Error: EPERM: operation not permitted, open '/path/to/ca.pem` message

If I edit the connection and reselect the same files, in the same locations, _then_ connect, it succeeds.

I've tried storing the files in a couple of places to see if macOS was being funny with permissions, but nowhere seems to work.

#### Expected

Saved connection configuration should work after app relaunch

#### Environment

- OS: macOS Monterey 12.21 (both M1 and Intel versions)
- MQTTX 1.6.0

#### More detail

![MQTTX 2022-03-14 16-48-37](https://user-images.githubusercontent.com/21380/158220801-9f5313e2-212c-4b2e-b9ba-6dcbc090244f.png)

**Comment by ysfscream** [comment]
Hi @elandesign, this does seem a little strange, and is generally speaking there is no need to reconfigure.

Maybe you can change the access rights of the folder or application and try again. However, I see that you are using v1.6.0, so you may want to upgrade to the latest version and try it out. After upgrading, data may be lost, make a backup of your data first.

**Comment by elandesign** [comment]
Ah, my bad - hadn't realised the Mac App Store version wasn't up to date. Downloaded 1.7.3 and that's working perfectly. Thanks for the pointer.

**Comment by ysfscream** [comment]
Glad you solved this issue. And there are some problems with the update on the App Store, sorry about that.
