### ISSUE TITLE
[Feature] ALPN protocol support

### ISSUE THREAD

**Issue by overheat** [emqx/MQTTX#916]
#### Motivation

Many IoT Cloud service provider, like aws, need ALPN protocol for advance usage.
Refer here: https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

#### Detailed design

A text plain for input ALPN content. 

#### Alternatives

Describe alternatives you've considered, what other designs have been considered? What is the impact of not doing this?

**Comment by ysfscream** [comment]
@overheat Hi, thanks for your advice! We will look at and discuss the suggestions you provide.

**Comment by muhufuk** [comment]
@overheat It would be great If you implement ALPN support to MQTTX

**Comment by ysfscream** [comment]
Thank you for being so patient!

We have addressed and resolved this issue in the https://github.com/emqx/MQTTX/releases/tag/v1.9.6

It helps us continually improve our product. If you encounter any issues while using the new version, please do not hesitate to let us know.

Thank you once again!

For this issue, special thanks to @twankamp
