### ISSUE TITLE
[Bug] Long messages cannot be cleared

### ISSUE THREAD

**Issue by bingdianfeishui** [emqx/MQTTX#922]
#### What did I do

消息显示窗口有长消息（200KB Base64编码的图片）时，点击"清除历史记录"

When there is a long message (200KB Base64 encoded image) in the message display window, click "Clear History".

#### What happened

消息窗口无法完全清空，仍有部分长消息的内容显示残留，右键又无法删除。（没有刷新窗口？？）
待下次收到多几条短消息时，残留显示消失。

The message window is not completely cleared, and some of the contents of the long message are still displayed, which cannot be deleted by right-clicking. (No window refresh??)
When I receive more messages, the residue disappears.

#### Environment

- OS: Windows 11 家庭中文版 21H2
- MQTTX version, 1.7.3

**Comment by ysfscream** [comment]
@bingdianfeishui Hi, thanks for using. And could you please provide the screenshot? I can not reproduce this issue, and if you want to refresh the window, you can use the shortcut: `Ctrl + R`.

**Comment by ysfscream** [comment]
It's fixed on https://github.com/emqx/MQTTX/releases/tag/v1.8.0
