### ISSUE TITLE
断开重连订阅失效

### ISSUE THREAD

**Issue by LiJiaDong0922** [emqx/MQTTX#923]
复现步骤：
1.添加订阅后可以正常接收消息
2.断开连接，重新连接
3. 步骤1添加订阅就无法收到消息
4.重新添加同样名称的订阅，就可以继续接收到消息

**Comment by ysfscream** [comment]
@LiJiaDong0922 Hi, sorry for my late reply.

I'd like to ask you,  did you turn on the auto resubscribe setting? 

<img width="1022" alt="截屏2022-04-04 下午7 06 01" src="https://user-images.githubusercontent.com/21299158/161531312-6dd84848-b1bb-4ba4-8c0d-ab78de430e45.png">

Or you can see from the log whether the topic has been resubscribed.

<img width="850" alt="截屏2022-04-04 下午7 08 45" src="https://user-images.githubusercontent.com/21299158/161531838-6d43fd77-eddf-4bca-9855-ad733d412f3a.png">

**Comment by LiJiaDong0922** [comment]
原理如此，是我没有开启，不好意思。开启后就可以了
