### ISSUE TITLE
[Help] Auto reconnect seems not working?

### ISSUE THREAD

**Issue by whc2001** [emqx/MQTTX#929]
The Internet connection from my laptop to the MQTT server is somewhat unstable. I have turned on Auto Reconnect for my connection, and have set the Max Reconnection Times to a large enough value.

![image](https://user-images.githubusercontent.com/16266909/163658689-04d95365-d7cb-4a04-931d-1bcd7ab3aca7.png)
![image](https://user-images.githubusercontent.com/16266909/163658696-77f3be36-977a-4892-8491-1fa59cafee5a.png)

However every time after it disconnects, it does not auto reconnect. The log looks like this:

```
[2022-04-15 08:50:45] [ERROR] *SERVER* connect fail, MQTT.js onError trigger, Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
[2022-04-15 08:50:45] [INFO] *SERVER* connect close, MQTT.js onClose trigger
```

Did I do something wrong or the "auto reconnect" function is not what I think?

**Comment by ysfscream** [comment]
@whc2001 Hi, thanks for your using. it looks like an abnormal disconnection. If you actively disconnect from the MQTT server, does the current connection auto reconnect? I have no problem testing on my end.

<img width="414" alt="截屏2022-04-16 下午3 18 03" src="https://user-images.githubusercontent.com/21299158/163665831-53bdccc7-a5fd-445d-84dc-b71d391e79e4.png">

**Comment by whc2001** [comment]
I have tried kicking off the client from EMQX WebUI and seems like this time it auto reconnects just fine. During the time from when I send this issue to when you replied, it encounters another connection error that's not ECONNRESET and it fails to reconnect again:
```
[2022-04-16 02:28:19] [INFO] *SERVER* connect close, MQTT.js onClose trigger
[2022-04-16 02:28:20] [INFO] *SERVER* reconnect: 1 times retry
[2022-04-16 02:28:21] [INFO] *SERVER* connect success, MQTT.js onConnect trigger
[2022-04-16 02:45:50] [INFO] *SERVER* connect close, MQTT.js onClose trigger
[2022-04-16 02:45:51] [INFO] *SERVER* reconnect: 2 times retry
[2022-04-16 02:46:52] [INFO] *SERVER* connect close, MQTT.js onClose trigger
[2022-04-16 02:46:54] [INFO] *SERVER* reconnect: 3 times retry
[2022-04-16 02:47:15] [ERROR] *SERVER* connect fail, MQTT.js onError trigger, Error: connect ETIMEDOUT 81.69.28.102:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2022-04-16 02:47:15] [INFO] *SERVER* connect close, MQTT.js onClose trigger
```

So rather seems like this function only works in certain disconnection situations. This issue is now kinda turning into a feature request now. Is it possible to have it retry reconnection indefinitely on any type of disconnection?

**Comment by ysfscream** [comment]
And what is the reason for your disconnection?

**Comment by whc2001** [comment]
Mostly it's ECONNRESET which is a network issue. After that MQTTX won't auto reconnect. 

The problem is that I don't have a server to test it anymore. EMQX has SO MANY issues on my VPS. It always "half-starts" which the background process is up but the `emqx start` always return error. After I kicked MQTTX off with the WebUI, I was unable to connect again (after connection, subscribe to anything will cause a kicking off) and it reconnects constantly (yeah this time the auto reconnect really works). I tried to update to 4.4.2 and it completely killed all my existing config for unknown reason, and all the users and ACLs are lost. The HTTP API for configuring users and ACLs is a complete pain in the ass to use by hand so I decided to purge everything about EMQX and return to Mosquitto later.

I don't have time for now, so I'll close this temporarily. After migrating to Mosquitto as broker I'll see if the ECONNRESET still persists.

**Comment by ysfscream** [comment]
OK. Forgive me for not helping you with this issue, but I think maybe it's not a behavior problem with MQTTX, if you think you have some doubts about EMQX, maybe you can go to the EMQX repository or our community to consult and solve it, sorry!

EMQX: https://github.com/emqx/emqx/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

Ask EMQX: https://askemq.com/
