### ISSUE TITLE
Not Working in New Mac-book M1

### ISSUE THREAD

**Issue by dedhdude** [emqx/MQTTX#931]
Following is shown when i try to run application

<img width="652" alt="Screenshot 2022-04-16 at 11 19 25 AM" src="https://user-images.githubusercontent.com/22762075/163663650-5559484e-1c68-4c44-aa81-d4b8e2960e91.png">

**Comment by ysfscream** [comment]
@zmstone Thanks for transfer to here.

@dedhdude Hi, we already support running on M1, please download the correct installation package. Refer to the following links and screenshots.

Download here: https://github.com/emqx/MQTTX/releases/download/v1.7.3/MQTTX-1.7.3-arm64.dmg

<img width="339" alt="截屏2022-04-16 下午3 13 09" src="https://user-images.githubusercontent.com/21299158/163665641-e8c5bcbb-de4f-408a-863b-484d1d05c0f3.png">

<img width="355" alt="截屏2022-04-16 下午3 13 26" src="https://user-images.githubusercontent.com/21299158/163665648-3f1f6de6-18ac-4a07-a578-ff471ae0b9a5.png">

**Comment by ysfscream** [comment]
Hi, if there is no problem, I will close this issue. Thanks.
