### ISSUE TITLE
[Bug] Unable to connect to Mosquito's WebSocket

### ISSUE THREAD

**Issue by bicijinlian** [emqx/MQTTX#939]
#### 问题描述

使用MQTTX 以 websocket 方式连接 mosquitto 服务器时，报错。

不管是自建还是 mosquitto 在线测试服务器（test.mosquitto.org 8080端口），均不能连接；但使用其它客户端工具均能连接上，其中包括 EMQ X 管理web页面。

#### Bug 再现

使用MQTTX 连接在线服务器 test.mosquitto.org 8080端口

#### 期望

确认是否软件 bug, 解决方案！

#### Environment

- OS: Windows 11
- MQTTX version, e.g. v1.7.3

**Comment by ysfscream** [comment]
Thanks for your feedback, this is indeed a bug, but it seems to be due to the current version of MQTT.js, I seem to be able to connect using another WebSocket client tool: http://tools.emqx.io/, strangely this doesn't seem to have any effect on connecting to EMQX's Broker: broker.emqx.io

**Comment by bicijinlian** [comment]
您好，非常感谢您的回复。确实是可以用 WebSocket方式正常连接到 EMQX。但是 Mosquitto 时，无论设置 3.1、3.11 或者 5.0  都不可以；其它选项也试过，都不行。本机 RabbitMQ(web stomp 插件) 下，我本机环境也 不行； ActiveMQ HiveMQ 没有测试过。
| |
bicijinlian
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年5月20日 10:05 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [emqx/MQTTX] [Bug] 连接 WebSocket 错误 (Issue #939) |

Thanks for your feedback, this is indeed a bug, but it seems to be due to the current version of MQTT.js, I seem to be able to connect using another WebSocket client tool: http://tools.emqx.io/, strangely this doesn't seem to have any effect on connecting to EMQX's Broker: broker.emqx.io

**Comment by ysfscream** [comment]
OK, thanks! I will fix it.

**Comment by ysfscream** [comment]
After testing again, I found that it already works in https://github.com/emqx/MQTTX/releases/tag/v1.8.0, thanks for the feedback, I will close this issue.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/21299158/180489589-9c5e283d-2707-4f57-8d00-ee8ab74387a6.png">

**Comment by TheWaWaR** [comment]
v1.9.1 还是有同样的问题。点击 connect 转了一下小圈圈又回到原来的状态。
