### ISSUE TITLE
[Bug] Will message not to be sent

### ISSUE THREAD

**Issue by Eru1989** [emqx/MQTTX#945]
#### What did I do

我设置了遗嘱消息。

#### What happened

建立连接后再手动断开，设置的遗嘱消息没有从服务器发出来。

#### Expected

服务器应该发出遗嘱消息。

#### Environment

- OS: windows 7 旗舰版
- MQTTX version, e.g. v1.7.3

#### More detail

我使用python编写了脚本，就可以收到服务器发出来的遗嘱消息。

**Comment by Eru1989** [comment]
![1654672299179](https://user-images.githubusercontent.com/41880768/172554465-4de1a985-4c7d-4f92-8c76-b9994aec44fd.jpg)
设置截图

**Comment by ysfscream** [comment]
Hi, sorry for my later reply. Could you please tell me the details of the reproduction steps? For example how a will message is triggered?

However, manually triggering a disconnection will not trigger a probate message. Here is an article that you may wish to refer to. https://www.emqx.com/en/blog/use-of-mqtt-will-message

**Comment by ysfscream** [comment]
Hi, if there is no problem, I will close this issue. Thanks.
