### ISSUE TITLE
[Bug] White screen on fedora 36 with nvidia GPU ?

### ISSUE THREAD

**Issue by vlycop** [emqx/MQTTX#946]
#### What did I do

Trying to run mqttx both from flatpak and RPM, from the gnome desktop icon or the terminal fail.
I only get a white empty screen for a bit. Flatpak stay that way, rpm crash.
I run official nvidia driver 510.68.02 for a 3080ti on Fedora 36 Wayland and gnome.

#### What happened
Running both the RPM and Flatpak version from the termial give this error
```
~% mqttx 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[35190:0611/182103.113911:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
```
Googling it give no additional clue, but `vainfo` return the same error
```
~% vainfo       
libva info: VA-API version 1.14.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
vaInitialize failed with error code -1 (unknown libva error),exit
```

#### Expected

I if this is a lib missing, i would expect flatpak to still work, but since it's the first and only software bringing that error i would expect some more verbose error message.

#### Environment

- OS: Fedora 36, nvidia driver 510.68.02, wayland, gnome 42.2
- MQTTX version 1.17.3

#### More detail
It it very likely that there is something missing on my side but i would really appreciate help to figure it out, and maybe down the line some clear error message to guide future user

**Comment by ysfscream** [comment]
I'm very sorry, I'm actually not too familiar with the use of flatpak to give you more detailed information, as this is also supported by a third party, is it possible to download the installation package if you don't use the flatpak method of installation? https://github.com/emqx/MQTTX/releases/tag/v1.7.3

**Comment by vlycop** [comment]
hi @ysfscream, i've try both flatpak and RPM from the release page and as explained, both have the same issue :(
If you have any clue about starting to debug this with the RPM install i would be happy to try those

**Comment by ysfscream** [comment]
Could you please try v1.8.0 again?

**Comment by vlycop** [comment]
Sure :)
No crash but still a white screen with this error
`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`

**Comment by ysfscream** [comment]
Is this still an issue at the moment? Feel free to use https://github.com/emqx/MQTTX/releases/tag/v1.9.1, I will close the issue first, if it still exists you can reopen it.
