### ISSUE TITLE
[Feature] Clear all logs message in MQTTX application

### ISSUE THREAD

**Issue by tuantm055** [emqx/MQTTX#948]
After the application receive > 100k msg, GUI can't be load for clear msg

**Comment by ysfscream** [comment]
ok, yeah! This is a feature I forgot to add, sorry it does cause problems. And you can clear the logs manually by going to a directory like this, ${your-user-name}/AppData/Local/Programs/MQTTX/

**Comment by ysfscream** [comment]
Sorry, I misunderstood you earlier, did you mean that the messages on the page cannot be cleared? After clicking on clear history, do you still have it when you reopen the page?

**Comment by ysfscream** [comment]
I'm sorry to see this problem, but maybe you can only delete the `MQTTX.db` file in this path: `${your-user-name}/AppData/Local/Programs/MQTTX/` and restart it. Although the data will be lost, this should ensure you can reopen it.

This is really a nagging problem, MQTTX doesn't do a very good job of handling large numbers of messages, we are trying to fix this in the MQTTX-Next release, and hope you can understand.

**Comment by tuantm055** [comment]
I see it in C:\Users\tuantm76\AppData\Roaming\MQTTX. Thanks

**Comment by ysfscream** [comment]
You are welcome. We will continue to optimize. I close the issue.
