### ISSUE TITLE
[Bug] Always show white screen in Window 11

### ISSUE THREAD

**Issue by LonelystartO** [emqx/MQTTX#968]
#### What did I do

打开MQTTX，如下显示
![1656309522741_59737E8E-E72C-46db-A4C5-7A8D62502DDB](https://user-images.githubusercontent.com/28235447/175870059-fd627e8f-a7d5-475b-8775-14068b6e135d.png)

等待一定时间后白屏
![image](https://user-images.githubusercontent.com/28235447/175870108-938361c9-0831-4d5b-bc9f-e48d350c407b.png)

#### Environment

- OS: Windows 11 家庭中文版
- MQTTX version, 1.8.0

**Comment by LonelystartO** [comment]
> Hello, thanks for your feedback, could you please tell me what detailed actions were done before opening? Is this your first time installing MQTTX?

这不是我第一次安装MQTTX。之前安装的是1.7.3版本，当时还正常使用了几天。之后的某一天突然就变成白屏了。

我有尝试卸载重装，还是不行。

另外，我之前有尝试验证使用mqtt发送图片，并进行了压测。压测的方式是使用Nodejs编写了一个客户端发送图片（向一个Topic连续发送约10万张，每张1MB大小），使用MQTTX订阅了这个Topic。但是，我不能确定是不是在这期间MQTTX客户端出现的白屏异常😅。

**Comment by ysfscream** [comment]
OK, I suddenly understand why this is happening, MQTT X can't handle too much data and too many messages very well right now, there may be some formatting errors in the storage and it's not possible to get the data from the local database.

So, I'm sorry to see this problem, but maybe you can only delete the `MQTTX.db` file in this path: `${your-user-name}/AppData/Local/Programs/MQTTX/` and restart it. You can refer to this issue: https://github.com/emqx/MQTTX/issues/948

**Comment by LonelystartO** [comment]
> OK, I suddenly understand why this is happening, MQTT X can't handle too much data and too many messages very well right now, there may be some formatting errors in the storage and it's not possible to get the data from the local database.
> 
> So, I'm sorry to see this problem, but maybe you can only delete the `MQTTX.db` file in this path: `${your-user-name}/AppData/Local/Programs/MQTTX/` and restart it. You can refer to this issue: #948

按照你的指引已完美解决！

**Comment by HparkeY** [comment]
我也同样操作遇到同样问题，但是在${your-user-name}/AppData/Local/Programs/MQTTX/ 目录下没有发现 .db 文件

**Comment by ysfscream** [comment]
@HparkeY Try to delete the `%USERPROFILE%\AppData\Roaming\MQTTX\MQTTX.db` db file and reopen it again.

**Comment by ysfscream** [comment]
Apologies for the long wait, welcome to https://github.com/emqx/MQTTX/releases/tag/v1.9.1, that should solve the problem and I will close this issue.

**Comment by alexfangmann** [comment]
Hi, 
I have the same problem.

Complete new Installation of Version 1.9.1 64 bit 

Environment: 
Windows 11, Version 10.0.22621 Build 22621
![image](https://user-images.githubusercontent.com/42581625/217268842-833e2c7c-84f8-4f5d-9c49-1b102beba1b0.png)

**Comment by ysfscream** [comment]
@alexfangmann Try to delete the %USERPROFILE%\AppData\Roaming\MQTTX\MQTTX.db db file and reopen it again.

**Comment by alexfangmann** [comment]
@ysfscream It does not work in my case. The DB was recreated with a size of 0 kB.

**Comment by ysfscream** [comment]
@alexfangmann What? Is this going to be a permission issue?
