### ISSUE TITLE
[Bug] If a single topic contains symbol comma [,] it will be automatically separated into multiple topics when subscribing

### ISSUE THREAD

**Issue by shaojun** [emqx/MQTTX#969]
#### What did I do

我有一个topic需要订阅，此topic类似：

> /Applications.FDC.xxxxxx/Applications.FDC.xxxx,FdcSer_ac8a48af9b2ce04d_0/thing/event/abcdefg/post

**可见其中是有一个逗号字符**，则将它输入至sub窗口中时：
![image](https://user-images.githubusercontent.com/3241829/175896501-8955d79d-da45-4368-9172-e4111cab4bd7.png)

#### What happened

会被以逗号分隔成两个topic以分别sub：
![image](https://user-images.githubusercontent.com/3241829/175896680-81acc1f7-3728-4d5e-9523-4e694d023632.png)

#### Expected

应仍作为单一topic进行成功sub

#### Environment

- OS: Windows 11 (x64)
- MQTTX version, v1.8.0

**Comment by ysfscream** [comment]
Oh yes, the comma will be used as a separator to subscribe to multiple topics, I didn't realize there was a topic with a comma in it, maybe a switch could be provided to turn off the multi-subscription mode.

**Comment by ysfscream** [comment]
Now in the latest version https://github.com/emqx/MQTTX/releases/tag/v1.8.2, we have added a multi-topic subscription configuration, if you turn off this configuration on the settings page, you will be able to continue to subscribe to your topic that currently contains a comma.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/21299158/183042999-a33f3f8c-e91a-4f78-8350-c9301482b6a3.png">
