### ISSUE TITLE
 clients does not work well on linux

### ISSUE THREAD

**Issue by unicorn343** [emqx/MQTTX#974]
Mqttx often doesn't work under linux, especially when sending messages regularly and opening multiple clients.

**Comment by ysfscream** [comment]
Hi! Could you please provide details of the reproduction procedure and the specific environment in which it will be used?

**Comment by unicorn343** [comment]
The environment is ubuntu22.04 lts with 9700k cpu. No matter whether the package in deb format or the package in snap format is used, there are cases where there is no response when you open it and cases where you can't click the interface when you send it regularly, but the data is still being sent. Deb-formatted packages are stuck in a more ordinary way.

**Comment by ysfscream** [comment]
Thanks for the feedback, you can download AppImage directly to use or use MQTT X CLI, feel free to try again with https://github.com/emqx/MQTTX/releases/tag/v1.8.3
