### ISSUE TITLE
[Feature] hope connection bar can be collasped

### ISSUE THREAD

**Issue by lidanger** [emqx/MQTTX#983]
#### Motivation

I think 2 changes will make it better:

#### Detailed design

1. connection bar can be collasped
2. publish topic bar can be multiple, or collapsed, or can select recent topics instead of the most used ones

**Comment by ysfscream** [comment]
Hi, thanks for your feedback.

Sounds like a good suggestion, but my question is on the first point, does the connection bar refer to a list of connections?
