### ISSUE TITLE
view[Bug] the title of bug report

### ISSUE THREAD

**Issue by zlh66** [emqx/MQTTX#997]
#### What did I do

Something you have done.

#### What happened

Get an error.

#### Expected

What is the expected result.

#### Environment

- OS: OS version, e.g. macOS Big Sur 11.1
- MQTTX version, e.g. v1.5.0

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Could you give a more detailed description?

**Comment by ysfscream** [comment]
如果有什么问题，可以尝试新的版本：https://github.com/emqx/MQTTX/releases/tag/v1.8.1
