### ISSUE TITLE
[BUG] MQTT X exited unexpectedly on macOS

### ISSUE THREAD

**Issue by slgoing** [emqx/MQTTX#999]
![image](https://user-images.githubusercontent.com/27996742/180694284-35159e5a-6683-4f7f-99f8-e87593e3e875.png)

#### V1.8.0

I use it **every time** , it will give me such a prompt message:
(Figure above)
> "Mqttx" exited unexpectedly
> Click "reopen" to open the application again
> ...

Thanks!

**Comment by ysfscream** [comment]
Hi! This is a known bug and will be fixed in the next version. Thanks for your feedback.

**Comment by slgoing** [comment]
OK! Thanks!

**Comment by ysfscream** [comment]
Fixed in the https://github.com/emqx/MQTTX/releases/tag/v1.8.1
